### ISSUE TITLE
Add Support for GLTF Animations / Skins / Morphs

### ISSUE THREAD

**Issue by robertlong** [KhronosGroup/UnityGLTF#1]
Animations are currently deserialized into the GLTFRoot object, but not translated into a Unity Animation.

GLTF 2.0 Animation Spec
https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#animations

Unity Animation Component
https://docs.unity3d.com/ScriptReference/Animation.html

**Comment by stevenvergenz** [comment]
There's a bit of a problem with this on the roadmap. glTF has deliberately avoided specifying animation triggers/graphs/etc., so as a result glTF animation objects correspond roughly with Unity's AnimationClips. These can be created at runtime in Unity no problem. However, the AnimationController assets that use these clips cannot. So the usefulness of lone clips is limited. This needs to be addressed before this loader can be considered feature-complete.

^ @tparisi

**Comment by tufeixp** [comment]
Unitygltf is useless without animation support, anybody still working on it, and give a timeline please!

**Comment by blgrossMS** [comment]
This has been implemented as of #146

**Comment by AzadNezamdoust** [comment]
@blgrossMS Can you please give an estimate when animation issue will be resolved? My project is dependent on it. Thanks.
