### ISSUE TITLE
Animated GLB model not loaded

### ISSUE THREAD

**Issue by prathamsatam** [KhronosGroup/UnityGLTF#107]
Hi,

First of all Thanks for creating such a nice platform.
My issue is **Animated .glb model is not loaded**
The error is pointing to the serialization code means the plugin code.
**When I used our model Error is:**
ArgumentException: The requested value 'CUBICSPLINE' was not found.
System.Enum.Parse (System.Type enumType, System.String value, Boolean ignoreCase) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Enum.cs:692)
System.Enum.Parse (System.Type enumType, System.String value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Enum.cs:547)
GLTF.Extensions.JsonReaderExtensions.ReadStringEnum[InterpolationType] (Newtonsoft.Json.JsonReader reader) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Extensions/GLTFJsonExtensions.cs:367)
GLTF.Schema.AnimationSampler.Deserialize (GLTF.Schema.GLTFRoot root, Newtonsoft.Json.JsonReader reader) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Schema/AnimationSampler.cs:55)
GLTF.Schema.Animation+<>c__DisplayClass2_0.<Deserialize>b__1 () (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Schema/Animation.cs:39)
GLTF.Extensions.JsonReaderExtensions.ReadList[AnimationSampler] (Newtonsoft.Json.JsonReader reader, System.Func`1 deserializerFunc) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Extensions/GLTFJsonExtensions.cs:57)
GLTF.Schema.Animation.Deserialize (GLTF.Schema.GLTFRoot root, Newtonsoft.Json.JsonReader reader) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Schema/Animation.cs:39)
GLTF.Schema.GLTFRoot+<>c__DisplayClass18_0.<Deserialize>b__1 () (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Schema/GLTFRoot.cs:145)
GLTF.Extensions.JsonReaderExtensions.ReadList[Animation] (Newtonsoft.Json.JsonReader reader, System.Func`1 deserializerFunc) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Extensions/GLTFJsonExtensions.cs:57)
GLTF.Schema.GLTFRoot.Deserialize (System.IO.TextReader textReader) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Schema/GLTFRoot.cs:145)
GLTF.GLTFParser.ParseString (System.String gltfContent) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/GLTFParser.cs:123)
GLTF.GLTFParser.ParseJson (System.Byte[] gltfBinary) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/GLTFParser.cs:40)
UnityGLTF.GLTFSceneImporter+<Load>c__Iterator0.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:124)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

**And when I used KhronosGroup Sample animated model(AnimatedMorphCube.glb) it gives following error.**
ArgumentException: The requested value 'weights' was not found.
System.Enum.Parse (System.Type enumType, System.String value, Boolean ignoreCase) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Enum.cs:692)
System.Enum.Parse (System.Type enumType, System.String value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Enum.cs:547)
GLTF.Extensions.JsonReaderExtensions.ReadStringEnum[GLTFAnimationChannelPath] (Newtonsoft.Json.JsonReader reader) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Extensions/GLTFJsonExtensions.cs:367)
GLTF.Schema.AnimationChannelTarget.Deserialize (GLTF.Schema.GLTFRoot root, Newtonsoft.Json.JsonReader reader) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Schema/AnimationChannelTarget.cs:41)
GLTF.Schema.AnimationChannel.Deserialize (GLTF.Schema.GLTFRoot root, Newtonsoft.Json.JsonReader reader) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Schema/AnimationChannel.cs:35)
GLTF.Schema.Animation+<>c__DisplayClass2_0.<Deserialize>b__0 () (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Schema/Animation.cs:36)
GLTF.Extensions.JsonReaderExtensions.ReadList[AnimationChannel] (Newtonsoft.Json.JsonReader reader, System.Func`1 deserializerFunc) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Extensions/GLTFJsonExtensions.cs:57)
GLTF.Schema.Animation.Deserialize (GLTF.Schema.GLTFRoot root, Newtonsoft.Json.JsonReader reader) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Schema/Animation.cs:36)
GLTF.Schema.GLTFRoot+<>c__DisplayClass18_0.<Deserialize>b__1 () (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Schema/GLTFRoot.cs:145)
GLTF.Extensions.JsonReaderExtensions.ReadList[Animation] (Newtonsoft.Json.JsonReader reader, System.Func`1 deserializerFunc) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Extensions/GLTFJsonExtensions.cs:57)
GLTF.Schema.GLTFRoot.Deserialize (System.IO.TextReader textReader) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/Schema/GLTFRoot.cs:145)
GLTF.GLTFParser.ParseString (System.String gltfContent) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/GLTFParser.cs:123)
GLTF.GLTFParser.ParseJson (System.Byte[] gltfBinary) (at C:/Users/prathamesh/Desktop/UnityGLTF-master/GLTFSerialization/GLTFSerialization/GLTFParser.cs:40)
UnityGLTF.GLTFSceneImporter+<Load>c__Iterator0.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:124)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

**Can anyone suggest where is the exact issue or If I am missing something?**

**Comment by travelhawk** [comment]
I have the same issue after exporting a gltf file from blender and trying to import the same in Unity. Pls help.
