### ISSUE TITLE
Support for multiple materials

### ISSUE THREAD

**Issue by MephestoKhaan** [KhronosGroup/UnityGLTF#110]
I an trying to export a mesh that has multiple materials but just the first one is being exported. Is this unsupported for now or am I doing something wrong.

The model was working fine when I had all the mesh split in submeshes each one with each own material.

**Comment by Tshadow05** [comment]
This is happening to me too

**Comment by MephestoKhaan** [comment]
On the meantime I used this tool:
https://gist.github.com/mstevenson/4145716

To split a mesh per materials in Maya. That made GLTF go with it for the time being

**Comment by Tshadow05** [comment]
So I actually just updated to the latest commit of UnityGLTF and while there were a couple other bugs for me it did support exporting a mesh with multiple materials. So you may try updating if you haven't.
