### ISSUE TITLE
Pink Shaders with latest commit

### ISSUE THREAD

**Issue by Tshadow05** [KhronosGroup/UnityGLTF#116]
I just upgraded to the latest version of UnityGLTF and all of the GLTF shaders result in pink objects because of the same error:

`Shader error in 'GLTF/PbrSpecularGlossiness': undeclared identifier 'MetallicRough' at /Program Files/Unity/Editor/Data/CGIncludes/UnityStandardCore.cginc(210) (on d3d11)`

It looks like the shaders that include UnityStandard core end up with an error but I can't see why. Does anybody have any idea whats going on?

**Comment by stevenvergenz** [comment]
What version of Unity is this? The new glTF shaders use overloaded versions of 5.6's UnityStandardInput and UnityStandardShadow. I suspect the function prototypes changed between that and whatever you're on.

**Comment by Tshadow05** [comment]
I am Unity 2017.3 so that is probably the issue. For now I just switched it to use the Standard Shader on import.

**Comment by keveleigh** [comment]
I'm seeing the same thing in 2017.2. It looks like the fix from #90 was removed.
