### ISSUE TITLE
Compatibility with .NET 4.6 on Unity 2017?

### ISSUE THREAD

**Issue by Ryo-AugiDish** [KhronosGroup/UnityGLTF#119]
I'm getting reference errors with .NET 4.6 on Unity 2017:

> ASsets/UnityGLTF/Scripts/UniformMaps/MetalRoughMap.cs(3,31): error CS0012: The type 'System.Enum' is defined in an assembly that is not referenced. Consider adding a reference to assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Seems like it's looking for a lower runtime version of .NET.
Not sure how to "add a reference" to it on Unity or VS.

Could someone help me out?

**Comment by stevenvergenz** [comment]
When are you getting these errors? I just generated a build with .NET 4.6 on Unity 2017.2, and everything worked as expected. This is probably a local project bug.
