### ISSUE TITLE
Does not build for Android Platform Target

### ISSUE THREAD

**Issue by StephenHodgson** [KhronosGroup/UnityGLTF#125]
Unity 2017.2
Android Build target

```
Shader error in 'GLTF/GLTFStandard': '' : 'UNITY_STANDARD_SIMPLE' already defined at /Program Files/Unity 2017.2/Editor/Data/CGIncludes/UnityStandardCoreForward.cginc(6) (on gles)
Error building Player: Shader error in 'GLTF/GLTFStandard': '' : 'UNITY_STANDARD_SIMPLE' already defined at /Program Files/Unity 2017.2/Editor/Data/CGIncludes/UnityStandardCoreForward.cginc(6) (on gles)
```

**Comment by stevenvergenz** [comment]
Make sure you're using the latest version of UnityGLTF. That shader was replaced a few weeks ago.

**Comment by keveleigh** [comment]
I'm seeing the same error on Android with the new shaders, tested with Unity 5.6, 2017.1, and 2017.2.

```
Shader error in 'GLTF/PbrMetallicRoughness': '' : 'UNITY_STANDARD_SIMPLE' already defined at /Program Files/Unity/Editor/Data/CGIncludes/UnityStandardCoreForward.cginc(6) (on gles)



Compiling Vertex program with DIRECTIONAL

Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER SHADER_API_MOBILE UNITY_HARDWARE_TIER1 UNITY_COLORSPACE_GAMMA
```



```
Shader error in 'GLTF/PbrSpecularGlossiness': '' : 'UNITY_STANDARD_SIMPLE' already defined at /Program Files/Unity/Editor/Data/CGIncludes/UnityStandardCoreForward.cginc(6) (on gles)



Compiling Vertex program with DIRECTIONAL SHADOWS_SCREEN

Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER SHADER_API_MOBILE UNITY_HARDWARE_TIER1 UNITY_COLORSPACE_GAMMA
```

**Comment by alter-sachin** [comment]
Were any of you able to resolve this ? I am seeing the same issue using unity 2017 and building for android .

**Comment by smtabatabaie** [comment]
I'm also getting this error when building for android in Unity 2017.2.0 . Mostly something is defined multiple times. like
Assets/UnityGLTF/Scripts/UniformMaps/MetalRoughMap.cs(3,31): error CS0433: The imported type `GLTF.Schema.AlphaMode' is defined multiple times
Assets/UnityGLTF/Scripts/Cache/AnimationCacheData.cs(11,10): error CS0433: The imported type `GLTF.AttributeAccessor' is defined multiple times
Assets/UnityGLTF/Scripts/Cache/TextureCacheData.cs(7,22): error CS0433: The imported type `GLTF.Schema.Texture' is defined multiple times

I'm getting 35 errors like this that something is defined multiple times.

**Comment by reubenkcoutinho** [comment]
Facing this issue for 2018.2 as well

**Comment by taharaza16** [comment]
Facing this issue as well! Anyone found any got it working???

**Comment by reubenkcoutinho** [comment]
@taharaza16 try [this solution](https://github.com/KhronosGroup/UnityGLTF/issues/206#issuecomment-406800459)

**Comment by marcspraragen** [comment]
Check #540
