### ISSUE TITLE
Scripted Importer?

### ISSUE THREAD

**Issue by lmontoute** [KhronosGroup/UnityGLTF#131]
Hey folks!

First off, huge appreciation for the work here to get glTF in Unity! We're using part of this repo for an editor plugin ([thinksquirrel/chipmunk-unity](https://github.com/thinksquirrel/chipmunk-unity)) and added native import in the editor using the [ScriptedImporter](https://docs.unity3d.com/ScriptReference/Experimental.AssetImporters.ScriptedImporter.html) API:

![image](https://user-images.githubusercontent.com/1100891/36618749-ee60528c-18b1-11e8-8e52-60ab3cbc9e44.png)

Would this be of interest at all upstream? If so, I'd be happy to clean it up, base it off of the latest upstream and add a PR. The downside is that this would only supported in Unity 2017 or newer.

**Comment by sbtron** [comment]
This would be greatly appreciated!
