### ISSUE TITLE
repackaging GLTFSerialization as NetStandard package

### ISSUE THREAD

**Issue by vpenades** [KhronosGroup/UnityGLTF#135]
The GLTFSerialization project is a great implementation of GLTF, from which many more developers could benefit outside the Unity environment.

I did create a small csproj targeting NetStandard 2 and the whole code of GLTFSerialization compiles without issues. So it can be trivial to add a new project to compile GLTFSerialization as a nuget package.

I can try to fork and PR it if there's an agreement on this feature.

@bghgary

**Comment by blgrossMS** [comment]
This PR has been merged so I'll close the issue. Thanks again for the contribution.
