### ISSUE TITLE
Exported rotations appear different

### ISSUE THREAD

**Issue by JasperDre** [KhronosGroup/UnityGLTF#136]
Hi,
The exported glTF files don't seem to give the same rotation when importing them into any of the glTF viewers.
For example the following scene contains a capsule and quad:
![Unity scene](https://user-images.githubusercontent.com/6676026/36893217-7b5ea6ac-1e07-11e8-9fe1-8a70ecac8b0b.png)

The capsule is rotated by 90 degrees on the X-axis (Quaternion(0.7071068, 0, 0, 0.7071068).
The quad has a rotation of 0 on all axes.
However, in any other importer it seems that the rotations are different:
![Imported glTF](https://user-images.githubusercontent.com/6676026/36892799-31ae61ba-1e06-11e8-87b1-9a3f104e0bb6.png)

I don't know if they are all off by 90 degrees on the X-axis or if I missed something from the glTF specifications. Any ideas?

**Comment by JasperDre** [comment]
Nevermind, the rotations seem to be fixed in the latest version.

**Comment by keveleigh** [comment]
This sounds like the issue fixed by #129. Should be good now!

**Comment by JasperDre** [comment]
Yup, I cloned the project just before the commit, so I wasn't aware of the fix until yesterday.
