### ISSUE TITLE
Some textures do not get exported

### ISSUE THREAD

**Issue by ziedbha** [KhronosGroup/UnityGLTF#140]
I tried exporting some assets after runtime import (i.e Boombox from sample models), and a texture is not being exported (the baseColor). This also happens with other assets. Not sure if this is a WIP, or something we need to fix.

Steps to reproduce problem:
1. Open BinaryBoomBoxTestScene
2. Change url to asset to http://localhost:8080/glTF-Sample-Models/2.0/BoomBox/glTF/BoomBox.gltf given that you have the sample models on your local repo
3. Uncheck Use Stream
4. Run Scene
5. Select GLTFScene under the GLTF asset (wait for it to load as a child)
6. Export Selected using Export menu
7. You should get a .bin, a .gltf, and 3 textures (black, blue (normal), red (PBR))

If you run it on http://sandbox.babylonjs.com/, you will get this: 

![image](https://user-images.githubusercontent.com/21377039/36951961-b58f6060-1fd7-11e8-94f1-7c30f223af5f.png)

**Comment by bghgary** [comment]
The offending code is here:

````
                     switch (materialObj.shader.name)
                     {
                           case "Standard":
                           case "GLTF/GLTFStandard":
                                  material.PbrMetallicRoughness = ExportPBRMetallicRoughness(materialObj);
                                  break;
                           case "GLTF/GLTFConstant":
                                  material.CommonConstant = ExportCommonConstant(materialObj);
                                  break;
                     }
````
 
Here is the offending code. The shader name is “GLTF/PbrMetallicRoughness” which doesn’t match any of the values in the switch. Not sure what happened here. @stevenvergenz/@blgrossMS?
