### ISSUE TITLE
Android Build not completing when including shaderRetention in build 

### ISSUE THREAD

**Issue by nomercy0** [KhronosGroup/UnityGLTF#141]
`Shader error in 'GLTF/PbrMetallicRoughness': '' : 'UNITY_STANDARD_SIMPLE' already defined at /Program Files/Unity/Editor/Data/CGIncludes/UnityStandardCoreForward.cginc(6) (on gles)`

I am using latest version of unitygltf and also I have tested all possible solution in issues regarding to this problem in unity

**Comment by stevenvergenz** [comment]
What version of unity is this with? It works for me in 5.6, albeit slowly.

**Comment by nomercy0** [comment]
I am using 2017.3.0f3

**Comment by pennomi** [comment]
This is also affecting me. @nomercy0 did you ever find a workaround?

**Comment by alter-sachin** [comment]
Also affecting me . @nomercy0  Any help ?

**Comment by nomercy0** [comment]
@pennomi No. I can not find a workaround .

I am still hoping someone here can guide me to make this possible . @stevenvergenz Help Please !

**Comment by pennomi** [comment]
I found that one of my project's other shaders caused this conflict. I could have one or the other, but not both in the same Android build.

**Comment by SeekIsaac** [comment]
Also affected by this. Can't build and run to Android. I'm on Unity 2017.4.0f1

**Comment by m0gr84u** [comment]
Also affected by this. Can't build and run to Android. I'm on Unity 2017.4.0f1

**Comment by pennomi** [comment]
OK I just barely figured out how to fix this issue the right way. (It looks like it's a bug in some core Unity includes.)

First, create a new file called `UnityGltfStandardCoreForward.cginc` and paste in the following code:

```
#ifndef UNITY_STANDARD_CORE_FORWARD_INCLUDED
#define UNITY_STANDARD_CORE_FORWARD_INCLUDED

#include "UnityStandardConfig.cginc"

#if UNITY_STANDARD_SIMPLE
    #include "UnityStandardCoreForwardSimple.cginc"
    VertexOutputBaseSimple vertBase (VertexInput v) { return vertForwardBaseSimple(v); }
    VertexOutputForwardAddSimple vertAdd (VertexInput v) { return vertForwardAddSimple(v); }
    half4 fragBase (VertexOutputBaseSimple i) : SV_Target { return fragForwardBaseSimpleInternal(i); }
    half4 fragAdd (VertexOutputForwardAddSimple i) : SV_Target { return fragForwardAddSimpleInternal(i); }
#else
    #include "UnityStandardCore.cginc"
    VertexOutputForwardBase vertBase (VertexInput v) { return vertForwardBase(v); }
    VertexOutputForwardAdd vertAdd (VertexInput v) { return vertForwardAdd(v); }
    half4 fragBase (VertexOutputForwardBase i) : SV_Target { return fragForwardBaseInternal(i); }
    half4 fragAdd (VertexOutputForwardAdd i) : SV_Target { return fragForwardAddInternal(i); }
#endif

#endif // UNITY_STANDARD_CORE_FORWARD_INCLUDED
```

Then, in the `PbrSpecularGlossiness.shader` and `PbrMetallicRoughness.shader` files, replace all

```
#include "UnityStandardCoreForward.cginc"
```
with
```
#include "UnityGltfStandardCoreForward.cginc"
```

Let me know if this works for you guys.

**Comment by reubenkcoutinho** [comment]
Is there a workaround for 2018.2?

**Comment by aliahmad11403** [comment]
Hello Guys,

Hope so you are fine and keeping well. Attached is the log of unity android build and these two shaders are taking most of the size in the app. 

"58.9 mb	 8.3% Assets/UnityGLTF/Shaders/PbrSpecularGlossiness.shader
 55.7 mb	 7.9% Assets/UnityGLTF/Shaders/PbrMetallicRoughness.shader"

When I don't add them in the android build the build doesn't work so I have added them and now it has increased the size. Can please anyone help me @stevenvergenz 
 

![image](https://user-images.githubusercontent.com/32351459/62124799-998db780-b2e4-11e9-8fda-38f7f798a48d.png)
