### ISSUE TITLE
Mesh normals reversed in imported model and vertex colors are not supported with GLTF Shader

### ISSUE THREAD

**Issue by rawnsley** [KhronosGroup/UnityGLTF#142]
GLB files [exported from Minecraft](https://news.microsoft.com/en-gb/2017/10/12/this-is-how-you-turn-your-minecraft-creations-into-3d-models/) ([example file](http://avn.cloud/stJzu7)) are imported with their normals reversed so everything is black.

This was fixed by calling mesh.RecalculateNormals() in GLTFSceneImporter::CreateMeshPrimitive on the imported mesh. I don't understand the codebase well enough to raise this as a pull request. It may be a symptom of a more fundamental problem in the importer or it could be that the GLB file is somehow not standards compliant, but it does load OK into all other GLTF applications I've tried.

**Comment by sbtron** [comment]
Could you elaborate on why you think the normals are reversed? My guess is the vertex colors from the Model might not be coming through correctly.

**Comment by rawnsley** [comment]
Funnily enough some of the colours are also wrong: the grass and leaves should be green. So it's possibly the colour import. I tried to work out why today, but only got as far confirming the bitmap imports OK.

My clue on the normals was that when you run in the Unity Editor you can browse the properties of individual meshes and the outsides were black and the insides white. It was then reinforced by the fact that running RecalculateNormals fixed the problem. It strongly implies normals are at fault somehow, but I'm just guessing they are reversed as it's a common polygon fault.

**Comment by blgrossMS** [comment]
Can you attach your model so that we can investigate further?

**Comment by rawnsley** [comment]
The linked example file should exhibit the behaviour: http://avn.cloud/stJzu7

**Comment by blgrossMS** [comment]
I'll have to look further into the normal issue. Like you said running RecalculateNormals fixes it. We found the same issue with tangents and have to do further investigation. 

As to the color issue, the problem is that the Unity Standard Shader does not support vertex coloring by default. @stevenvergenz or I can look into enabling it soon.
