### ISSUE TITLE
Exporting assets without textures fails

### ISSUE THREAD

**Issue by ziedbha** [KhronosGroup/UnityGLTF#143]
I tried exporting some assets in the SampleModels folder, and some seem to be failing to export properly. Note that I am exporting the asset **after** importing it, so the issue might come from importing.

Try exporting the Buggy (binary or not). You will get the following files:
[buggy.zip](https://github.com/KhronosGroup/UnityGLTF/files/1790353/buggy.zip)

If you use the [glTF Validator](http://github.khronos.org/glTF-Validator/), you will get errors (and you won't be able to display it using BabylonJS):

![ba15b3b246fc7f29939a3eca2887b8a5](https://user-images.githubusercontent.com/21377039/37110395-c7d6f8ca-220a-11e8-969c-7abe64b6bc2b.png)
Most issues come from the accessors. The byte offsets seem to be off.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
