### ISSUE TITLE
Unity error CS0433 (34 times) when trying to build

### ISSUE THREAD

**Issue by glascanob** [KhronosGroup/UnityGLTF#147]
Hi I'm trying to build this project and I'm having 34 errors that are basically the same but in different files:
"Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs(755,48): error CS0433: The imported type `GLTF.Schema.Scene' is defined multiple times"
I tried to build the project exactly how it is when cloned from the repository after compiling the .sln file. I opened the project on Unity 5.6.5 I'm able to run the "TestSceneScene" streaming the .gltf objects with no errors, but when I build the game into windows, webGL or IOS it throws me those 34 errors.

I'm doing something wrong? or there is a problem with the repository?

Could you please check this please.

**Comment by keveleigh** [comment]
The GLTFSerialization project generates two DLLs: one specifically for UWP, and one for everything else. You should make sure the DLLs are properly marked for the platforms they're compatible with. Likely, Unity is trying to include both DLLs in whichever platform you're trying to build for.

I've also noticed that 5.6.5 seems to be ignoring "Any Platform + Exclude WSAPlayer", but explicitly checking "Include Platforms" works for me.

The correct settings are in the [readme](https://github.com/KhronosGroup/UnityGLTF#building), and pictured below.

![image](https://user-images.githubusercontent.com/3580640/37496528-43d38ff4-2870-11e8-860d-cde46800da76.png) ![image](https://user-images.githubusercontent.com/3580640/37496530-4a1c8190-2870-11e8-91e4-053c809067bd.png)

**Comment by glascanob** [comment]
It fixed the building issue!.
Thank you for the information. I checked out those ones but didn't realize that. I just checked the ones for GLTFSerialization, I'm not using WSA so that is fine.

When I try to build is not throwing me the previous errors, so that fixed the problem thanks!, but now I'm having the following errors on the build:

![image](https://user-images.githubusercontent.com/30094739/37497715-1f806baa-2888-11e8-9a77-628818a0f8cc.png)

Do you know what it could be?

**Comment by glascanob** [comment]
I made it work fine
