### ISSUE TITLE
ShaderNotFoundException: GLTF/PbrMetallicRoughness not found. Did you forget to add it to the build?

### ISSUE THREAD

**Issue by glascanob** [KhronosGroup/UnityGLTF#148]
I build one scene, and as soon as I play the build it throws me this error, which I don't really know what is it.

Could you help me with it?

**Comment by glascanob** [comment]
I just make it work! just added the shader to the build on the standar shader file.
Then I had another error with animation, so I had to use legacy ones and it works!

**Comment by top-man** [comment]
https://github.com/KhronosGroup/UnityGLTF/issues/206#issuecomment-406800459
This solution saved tons my time!
