### ISSUE TITLE
Missing animations on runtime

### ISSUE THREAD

**Issue by glascanob** [KhronosGroup/UnityGLTF#149]
I have a working project that loads basic objects with animations. I'm trying to load the buster_drone that is one of the demo .glTF files. When I rune the game the complete object is populated but with an error:

"IndexOutOfRangeException: Array index is out of range.
UnityGLTF.GLTFSceneImporter.ConstructClip (UnityEngine.Transform root, UnityEngine.Transform[] nodes, Int32 animationId) (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:685)
UnityGLTF.GLTFSceneImporter+<ConstructScene>c__IteratorD.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:775)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)"

When I inspect the model it has the animation component but in the list of animations there is no clips.

Why this could be happening?

Also I made a separate test, I create a basic object on blender (one cube with one cone on top) I animated the cone to rotate on top of the cube. At the beginning I had a lot of problems to at least make it work, but when finally I had the object being populated in the scene at runtime, the animation was made to the first object on the hierarchy (the cube instead of the cone). I had notice that the rotation works because it just rotates the first transform object.

There is something wrong on the code or I'm missing something?

**Comment by lexaknyazev** [comment]
Just to check if the model is okay, could you drop it into
http://github.khronos.org/glTF-Validator/ ?

**Comment by glascanob** [comment]
Yes I drop the file and it says it has animations:

{
    "uri": "busterDrone.gltf",
    "mimeType": "model/gltf+json",
    "validatorVersion": "2.0.0-dev.1.7",
    "validatedAt": "2018-03-16T21:24:15.678Z",
    "issues": {
        "numErrors": 0,
        "numWarnings": 1,
        "numInfos": 5,
        "numHints": 0,
        "messages": [
            {
                "code": "MATERIAL_ALPHA_CUTOFF_INVALID_MODE",
                "message": "Alpha cutoff is supported only for 'MASK' alpha mode.",
                "severity": 1,
                "pointer": "/materials/0/alphaCutoff"
            },
            {
                "code": "NODE_MATRIX_DEFAULT",
                "message": "Do not specify default transform matrix.",
                "severity": 2,
                "pointer": "/nodes/1/matrix"
            },
            {
                "code": "NODE_EMPTY",
                "message": "Empty node encountered.",
                "severity": 2,
                "pointer": "/nodes/4"
            },
            {
                "code": "NODE_EMPTY",
                "message": "Empty node encountered.",
                "severity": 2,
                "pointer": "/nodes/8"
            },
            {
                "code": "NODE_EMPTY",
                "message": "Empty node encountered.",
                "severity": 2,
                "pointer": "/nodes/9"
            },
            {
                "code": "NODE_EMPTY",
                "message": "Empty node encountered.",
                "severity": 2,
                "pointer": "/nodes/12"
            }
        ],
        "truncated": false
    },
    "info": {
        "version": "2.0",
        "generator": "Unity 2017.1.0f3",
        "resources": [
            {
                "pointer": "/buffers/0",
                "mimeType": "application/gltf-buffer",
                "storage": "external",
                "uri": "busterDrone.bin"
            },
            {
                "pointer": "/images/0",
                "mimeType": null,
                "storage": "external",
                "uri": "Assets/Models/PBR/BusterDrone/Materials/Boden_baseColor.png"
            },
            {
                "pointer": "/images/1",
                "mimeType": null,
                "storage": "external",
                "uri": "Assets/Models/PBR/BusterDrone/Materials/concrete_044_metalGloss_converted_metalRoughness.jpg"
            },
            {
                "pointer": "/images/2",
                "mimeType": null,
                "storage": "external",
                "uri": "Assets/Models/PBR/BusterDrone/Materials/concrete_044_normal1024.jpg"
            },
            {
                "pointer": "/images/3",
                "mimeType": null,
                "storage": "external",
                "uri": "Assets/Models/PBR/BusterDrone/Materials/body_albedo2048.png"
            },
            {
                "pointer": "/images/4",
                "mimeType": null,
                "storage": "external",
                "uri": "Assets/Models/PBR/BusterDrone/Materials/body_metalgloss2048_converted_metalRoughness.jpg"
            },
            {
                "pointer": "/images/5",
                "mimeType": null,
                "storage": "external",
                "uri": "Assets/Models/PBR/BusterDrone/Materials/body_normal.jpg"
            },
            {
                "pointer": "/images/6",
                "mimeType": null,
                "storage": "external",
                "uri": "Assets/Models/PBR/BusterDrone/Materials/body_emissive.jpg"
            },
            {
                "pointer": "/images/7",
                "mimeType": null,
                "storage": "external",
                "uri": "Assets/Models/PBR/BusterDrone/Materials/body_AO.jpg"
            },
            {
                "pointer": "/images/8",
                "mimeType": null,
                "storage": "external",
                "uri": "Assets/Models/PBR/BusterDrone/Materials/leg_albedo.jpg"
            },
            {
                "pointer": "/images/9",
                "mimeType": null,
                "storage": "external",
                "uri": "Assets/Models/PBR/BusterDrone/Materials/leg_metalgloss_converted_metalRoughness.jpg"
            },
            {
                "pointer": "/images/10",
                "mimeType": null,
                "storage": "external",
                "uri": "Assets/Models/PBR/BusterDrone/Materials/leg_normal1024.jpg"
            },
            {
                "pointer": "/images/11",
                "mimeType": null,
                "storage": "external",
                "uri": "Assets/Models/PBR/BusterDrone/Materials/leg_AO.jpg"
            }
        ],
        "hasAnimations": true,
        "hasMaterials": true,
        "hasMorphTargets": false,
        "hasSkins": false,
        "hasTextures": true,
        "hasDefaultScene": true,
        "primitivesCount": 39,
        "maxAttributesUsed": 4
    }
}

**Comment by glascanob** [comment]
I'm looking at the code and its getting the error because on scene.nodes, which supposly should contain all transforms of the model, the count is = 1. so when the animation have to be applied to the node 68 it is out of range because the list of nodes just have 1

**Comment by Stridorz** [comment]
The scene node has the other nodes as children.

In ConstructClip in GLTFSceneImporter, it is trying to reference the animation nodes as if they were all flatly in the scene hierarchy, instead of referencing them by their index in the nodes list.
...
            foreach (var channel in animation.Channels)
            {
                var samplerCache = animationCache.Samplers[channel.Sampler.Id];
                var node = **_assetCache.NodeCache[channel.Target.Node.Id].transform;**
...
changing the last line here to use the NodeCache instead fixes it for loading at runtime.

I still can't get the clip to show up when loading using the import asset script.

**Comment by glascanob** [comment]
Hey yes I did that change and now is not throwing me that error. For me the clip is showing, but the problem now is that the animation is just taking like a random node. For example I have a cube and a sphere, and the animation is to rotate the sphere, well when it is imported the rotation is being applied to the cube rather than the sphere. How can I make them use the real index?

**Comment by glascanob** [comment]
Ok, for some reason in the code when setting the curves, it was setting them as -x and -y rotation, that is why I had negative rotations.
...
case GLTFAnimationChannelPath.rotation:

						for (int i = 0; i < input.AsFloats.Length; ++i)
						{
							var time = input.AsFloats[i];
							var rotation = output.AsVec4s[i];

							//curveX.AddKey(time, -rotation.X);
							//curveY.AddKey(time, -rotation.Y);
							**curveX.AddKey(time, rotation.X);
							curveY.AddKey(time, rotation.Y);**
							curveZ.AddKey(time, rotation.Z);
							curveW.AddKey(time, rotation.W);
						}
...

In the case of rotation I just changed the negative rotation to positive and works fine.
