### ISSUE TITLE
[glTF Validator] Accessor's total byteOffset 1126394 isn't a multiple of componentType length 4.

### ISSUE THREAD

**Issue by sonygod** [KhronosGroup/UnityGLTF#150]
[glTF Validator] Accessor's total byteOffset 1126394 isn't a multiple of componentType length 4.
[glTF Validator] Accessor's total byteOffset 1135226 isn't a multiple of componentType length 4.
[glTF Validator] Accessor's total byteOffset 1144058 isn't a multiple of componentType length 4.
[glTF Validator] Accessor's total byteOffset 1155834 isn't a multiple of componentType length 4.
[glTF Validator] Accessor's total byteOffset 1169438 isn't a multiple of componentType length 4.
[glTF Validator] Accessor's total byteOffset 1174526 isn't a multiple of componentType length 4.
[glTF Validator] Accessor's total byteOffset 1179614 isn't a multiple of componentType length 4.
[glTF Validator] Accessor's total byteOffset 1186398 isn't a multiple of componentType length 4.
glTF Property

The root object for a glTF asset.

![image](https://user-images.githubusercontent.com/748320/37646002-6a914eb4-2c63-11e8-9e31-714e6c619a34.png)
![image](https://user-images.githubusercontent.com/748320/37646019-7319a360-2c63-11e8-9974-d39bc5736bdc.png)

**Comment by sonygod** [comment]
[14.zip](https://github.com/KhronosGroup/UnityGLTF/files/1828721/14.zip)

**Comment by sonygod** [comment]
[testmodel2.zip](https://github.com/KhronosGroup/UnityGLTF/files/1832013/testmodel2.zip)
unity 2017.3.x

**Comment by ziedbha** [comment]
I'll look into this! This is I bug I also found :)

**Comment by Neuxxx** [comment]
[GLTFSceneExporter.zip](https://github.com/KhronosGroup/UnityGLTF/files/2026314/GLTFSceneExporter.zip)

I have run into the same Bug. In my case the Mixed-Reality-Viewer from Windows don't open my exported GLB Files.
I have add a little Methode to the exporter 
`private long AppendToBufferMultiplyOf4(long byteOffset, long byteLength)
		{
			var moduloOffset = byteLength % 4;
			if (moduloOffset > 0)
			{
				for (int i = 0; i < (4 - moduloOffset); i++)
				{
					_bufferWriter.Write((byte)0x00);
				}
				byteLength = _bufferWriter.BaseStream.Position - byteOffset;
			}

			return byteLength;
		}`

and call this from all Export Accessor Methodes

`			var byteLength = _bufferWriter.BaseStream.Position - byteOffset;

			byteLength = AppendToBufferMultiplyOf4(byteOffset, byteLength);

			accessor.BufferView = ExportBufferView((int)byteOffset, (int)byteLength);`
