### ISSUE TITLE
.glTF models don't show in the editor window

### ISSUE THREAD

**Issue by justinctlam** [KhronosGroup/UnityGLTF#154]
I noticed that the GLTF example scenes don't actually show the GLTF meshes in the editor window.
Is this a difficult technical problem? Wouldn't it be very useful to be able to see the models in the editor window not just at play time?

**Comment by TopRamenGod** [comment]
I'm attempting to do this as well, and gltf models to not show up in the editor at design time, nor can I drag and drop them into the scene or hierarchy. The only way to get models to show up is to type in the relative path to the asset in the StreamingAssets folder, and then Play the scene, making the models show at runtime. I've tried this on 2017.1.4f1, 2017.2.f1, and 2017.3.f1.

Is there a specific version of VS we need to be building this on?

**Comment by wisdomware** [comment]
Hi,
I just wanted to find out if this issue can be addressed in the next release.
Thanks!

**Comment by pfcDorn** [comment]
Fixed in latest release
