### ISSUE TITLE
Camera properties use incorrect casing according to glTF 2.0 spec

### ISSUE THREAD

**Issue by JasperDre** [KhronosGroup/UnityGLTF#156]
Hi,

While validating a glTF scene with a camera I encountered the following error:
![error](https://user-images.githubusercontent.com/6676026/38379627-8dcb8cc8-3901-11e8-938e-e4929618faab.PNG)

So in [CameraOrthographic.cs](https://github.com/KhronosGroup/UnityGLTF/blob/master/GLTFSerialization/GLTFSerialization/Schema/CameraOrthographic.cs) and [CameraPerspective.cs](https://github.com/KhronosGroup/UnityGLTF/blob/master/GLTFSerialization/GLTFSerialization/Schema/CameraPerspective.cs) the written properties are using camel casing. However, `xmag`, `xmag`, `znear`, and `zfar` should be lower case according to the [glTF 2.0 spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#cameras).

It might be useful to fix this before merging this camera implementation: (https://github.com/KhronosGroup/UnityGLTF/pull/153).

**Comment by ziedbha** [comment]
Fixed in #158. Thanks for pointing this out!
