### ISSUE TITLE
Load On Start disabled for all example scenes

### ISSUE THREAD

**Issue by dff180** [KhronosGroup/UnityGLTF#165]
The current master branch dc61bbd has GLTF Component "Load On Start" disabled for all example scenes which use the GLTF prefab.
This now has to be activated manually for each example scene to actually load the model when in play mode.

This seems to be have been introduced by commit 2ab2112 which changes the GLTF.prefab to have "Load On Start" disabled by default.

Tested with Unity 2017.2.1f1 and 5.6.4f1

**Comment by JohnCopicMS** [comment]
Sorry! I have a PR out re-enabling it in the prefab which should fix all of the test scenes.

**Comment by JohnCopicMS** [comment]
And the PR was merged, this should be fixed now in master.

**Comment by dff180** [comment]
Just checked master (051069c) and problem is fixed. Thanks a lot!
