### ISSUE TITLE
Import error for Box.glb from official Khronos glTF examples

### ISSUE THREAD

**Issue by dff180** [KhronosGroup/UnityGLTF#166]
This official Khronos sample file for an untextured box

https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Box/glTF-Binary/Box.glb

causes an import error for me when imported into Unity Editor (2017.2.1f1) via drag&drop (GLTFImporter):

+ GLTFHeaderInvalidException: File length does not match chunk header.

Observations:
+ File works when loaded at runtime via GLTF Component script
+ `ParseJson()` changes `stream.Position` when importing in Editor (>0)
+ `ParseJson()` does not change `stream.Position` when loading at runtime (=0)
+ The following Unity importer works fine with Box.gbl: https://github.com/thinksquirrel/chipmunk-unity
  + `ParseJson()` does not change here `stream.Position` when importing in Editor
+ Textured version BoxTextured.glb imports fine, untextured version Box.gbl has import problem

**Comment by pfcDorn** [comment]
Fixed in latest release
