### ISSUE TITLE
Support for draco extension

### ISSUE THREAD

**Issue by aashishagrawall** [KhronosGroup/UnityGLTF#174]
Recently I read  about draco extension on gltf,but I was not able to find out proper way to implement this exention on unitygltf repo.I am currently working on app that requires 3d object to be imported at runtime effectively and very fast.
I find draco extension is the only way to acheive this and I have gone through papers on internet but was not able to figure out how to implement this .Please anyone can assist how can I start implementing draco extension on gltf

**Comment by bghgary** [comment]
Have you tried using https://github.com/google/draco/tree/master/unity?

**Comment by tufeixp** [comment]
vote +1 for this extension support, Microsoft has used draco in it's Microsoft.glTF.CPP pipe-line.

**Comment by boblaublaw** [comment]
@bghgary That extension loads draco compressed geometry (.drc files), which does not include textures.  Supporting draco compression in gltf/glb would be a huge win for this module.

**Comment by bghgary** [comment]
@boblaublaw The original question is how to implement the draco extension in this project. The link I sent should help with that.

**Comment by BrahimHadriche** [comment]
So, is this on the roadmap?

**Comment by blgrossMS** [comment]
No one is actively working on it, but we always welcome contributions!

**Comment by iBicha** [comment]
Since draco is c++, I'm guessing it has to be built as a plugin for different platforms. What platforms should it include? Windows, macOS, iOS and Android for example?

**Comment by blgrossMS** [comment]
Yeah wrapping the existing plugins in the work from the repo that Gary linked would be a good start

**Comment by iBicha** [comment]
Well I looked around, for once, the existing plugin doesn't have a compressing method yet (only decompression) so it will need to be worked out.
Second, if I understand correctly, the extension is supposed to replace the bufferViews with their decompressed equivalent, which will need to be done in the loader and not the extension, which is weird and hacky. I guess the current architecture of UnityGLTF doesn't allow much flexibility to do things. Am I missing something?

**Comment by AlexPiro** [comment]
Hi guys ! If someone here is still looking for this extension (for a long time like me), take a look at this awesome GLTF importer alternative : [https://github.com/atteneder/glTFast](https://github.com/atteneder/glTFast)
I just found this and with simple fixes, I make it working ! 
Hope this helps ;)

**Comment by IsmaeelGoraya** [comment]
Any update on this?

**Comment by pfcDorn** [comment]
Import is now available in latest version. Export still not
