### ISSUE TITLE
Support mesh splitting when Mesh.vertices count is over 65000

### ISSUE THREAD

**Issue by sain801028** [KhronosGroup/UnityGLTF#175]
Support mesh splitting when Mesh.vertices count is over 65000 
![01](https://user-images.githubusercontent.com/17377422/39429366-4511f380-4cbd-11e8-99cf-4e261ab845bb.PNG)

**Comment by blgrossMS** [comment]
Unity added support for larger than 16 bit mesh indices in 2017.2, which we currently support in the repository. I will open a bug for the fact that we still have a limit.

**Comment by StephenHodgson** [comment]
Duplicate of #19

**Comment by blgrossMS** [comment]
Closing due to duplicate of #19
