### ISSUE TITLE
Replace dotnet 4.0 and 6.0 specific syntax

### ISSUE THREAD

**Issue by amenzies** [KhronosGroup/UnityGLTF#179]
What to folks think about replacing the 4.0 and 6.0 specific syntax as per this branch:
https://github.com/amenzies/UnityGLTF/tree/feature/net35_compatibility

While a bit uglier, this has the advantage that you can always just include the files from
[GLTFSerialization](https://github.com/KhronosGroup/UnityGLTF/tree/master/GLTFSerialization/GLTFSerialization) in the Unity project directly instead of building the DLL separately which may be a useful workaround in case folks have difficulty building the DLL for specific platforms or already have a project that is using a different version of Newtonsoft as per #178.

**Comment by StephenHodgson** [comment]
See #60 as well.

**Comment by ericob** [comment]
Can you make a pull request with your changes?

**Comment by amenzies** [comment]
You bet!

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
