### ISSUE TITLE
Animations working improperly

### ISSUE THREAD

**Issue by shekhar331** [KhronosGroup/UnityGLTF#181]
I have glTF models with animations. Although  the simple animations like single object translate and rotate do work properly the animations work properly in Unity. I have gltf models made from babylon glTF serialiser and they seem to animate in different manner then original ones. I have run the same Model on sandbox.babylonjs and works fine there.  Attached are the video references shwing model in Sandbox and another in Unity

[Captures.zip](https://github.com/KhronosGroup/UnityGLTF/files/2003719/Captures.zip)

**Comment by ericob** [comment]
This should be fixed in the latest version
