### ISSUE TITLE
Culling the wrong face with double sided=true

### ISSUE THREAD

**Issue by M1ntcraft3r** [KhronosGroup/UnityGLTF#189]
Some of the glb files I imported using g this great project appear to render the wrong face.
I checked the glb file and it has double sided set to true but the from faces are transparent and the rear faces (hidden) are visible.
Happy to try and play around with it if someone could point .e in the right direction.

May also be worth noting that the shaders actually set culling off.

Cheers

**Comment by AdamMitchell-ms** [comment]
Cleaning up old issues.  @M1ntcraft3r, is this still an issue for you?  If so, then please attach an example model so we can take a look.  Closing for now.

**Comment by boblaublaw** [comment]
Just saw a github notification about this.  I may have a sample model exhibiting the issue.  I was not previously aware of the double-sided property. Will investigate this property and my asset which is exhibiting this issue and let you know if I can reproduce.
