### ISSUE TITLE
Support mesh splitting when Mesh.vertices count is over 65000

### ISSUE THREAD

**Issue by robertlong** [KhronosGroup/UnityGLTF#19]
Currently the Scifi Helmet sample model doesn't render because it has too many vertices. I wouldn't recommend procedural generation of models with over 65000 vertices, but we should support this.

**Comment by stevenvergenz** [comment]
GLTF does not allow vertex indices longer than 32 bits without an extension anyway. It defines a primitive as one WebGL draw call, and WebGL needs the `OES_element_index_uint` extension to use 64-bit indices.

**Comment by ericob** [comment]
We're going to punt this (targeting newer version of Unity that doesn't have this limitation) @blgrossMS
