### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Rysm** [KhronosGroup/UnityGLTF#190]
The error

`NullReferenceException: Object reference not set to an instance of an object
LoadModel+<loadFromSF>c__AnonStorey0.<>m__1 (CI.HttpClient.HttpResponseMessage`1[T] s) (at Assets/Scripts/LoadModel.cs:122)
CI.HttpClient.Core.HttpBase+<RaiseResponseCallback>c__AnonStorey1`1[T].<>m__0 () (at Assets/HttpClient/HttpActions/HttpBase.cs:357)
CI.HttpClient.Core.Dispatcher.Update () (at Assets/HttpClient/Dispatcher/Dispatcher.cs:23)
`

occurs at :

` 
importer.setupForPath(gltfInput, _importDirectory, prefabName, true);
`

I know I have the gltfinput pointing at a .gltf 

prefab name is just a string name I made up

**Comment by ericob** [comment]
Are you still having this issue with the latest version of UnityGLTF?

**Comment by AdamMitchell-ms** [comment]
Cleaning up old issues.  Haven't gotten a response in a long time.
