### ISSUE TITLE
Importer duplicates accessors in memory for every mesh that references it, causing extreme memory usage

### ISSUE THREAD

**Issue by JoeyVrowl** [KhronosGroup/UnityGLTF#197]
There is a problem regarding shared accessors. If you have a single accessor containing all vertices for the .gltf file, but there are multiple meshes, then all vertices in that accessor will get loaded into every mesh. This is a big problem when you have a big .gltf with hundreds of meshes. For instance, we had a .gtlf with 150k tris, but when loading it, the importer would load 260 million verts because of the duplication. This caused Unity to sit at a whopping 10GB memory usage, in an empty scene with just that model.

Here is a simple example of 2 boxes. The caps are separate meshes, and the body is a single mesh. So 3 submeshes per box for body and caps, 48 vertices total in the accessor. This means 2*3*48=288 vertices loaded in Unity, where we would only expect 48 vertices loaded.
[incorrect.zip](https://github.com/KhronosGroup/UnityGLTF/files/2162254/incorrect.zip)

This problem came to light when exporting using the [Sketchup GLTF exporter](https://extensions.sketchup.com/en/content/gltf-exporter) by CentaurMare. This plugin puts all vertices in a single accessor to save a bit of file size. The author of that plugin was very helpful, and we had some back and forth to come to this conclusion. The author says he discussed the problem on https://gitter.im/KhronosGroup/glTF to check if shared accessors like that are part of the .gltf spec. Consensus was that it is, and so it should be a bug in the importer in Unity rather than the exporter in Sketchup. Maybe worth noting is that ksons Blender importer exhibits the exact same issue as the Unity importer, I will make a report there as well.

I've made a quick mitigation effort by filtering the unnecessary verts in GLTFSceneImporter.cs:1117 (ConstructUnityMesh) before it loads it into a Unity mesh, but this only makes a difference in video memory I think. The duplicates still get loaded into RAM somewhere, I assume in the .dll that you have to build. I have not gotten around to messing around in that. It does provide you with a bit of a starting point of where to look.

**Comment by foreverliu** [comment]
Has this problem been solved?

**Comment by foreverliu** [comment]
I have encountered this problem, but I do not know how to solve it?

**Comment by foreverliu** [comment]
@ericob Hello, I have encountered the same problem, is this problem being solved?

**Comment by foreverliu** [comment]
@ericob Hello,Got the same issue.. Any fixes???

**Comment by foreverliu** [comment]
Got the same issue.. Any fixes???

**Comment by foreverliu** [comment]
I noticed that Blender importer has modified this issue. I want to know if Unity importer has been fixed?

**Comment by foreverliu** [comment]
I noticed that Blender importer has fixed this problem. I want to know if Unity importer has been fixed?

**Comment by pfcDorn** [comment]
Fixed in latest release
