### ISSUE TITLE
Conflicts with native Unity Types

### ISSUE THREAD

**Issue by StephenHodgson** [KhronosGroup/UnityGLTF#200]
Right now there is a few classes that conflict with the native Unity Types, which makes it difficult to distinguish.

I'd like to propose updating the namespaces in the Assets/Scripts/Schema folder to: `GLTF.Schema` and rename a few classes.

- [x] GLTF.Animation-> GLTF.Schema.GLTFAnimation
- [x] GLTF.Camera-> GLTF.Schema.GLTFCamera
- [x] GLTF.Image -> GLTF.Schema.GLTFImage
- [x] GLTF.Material -> GLTF.Schema.GLTFMaterial
- [x] GLTF.Mesh -> GLTF.Schema.GLTFMesh
- [x] GLTF.Texture -> GLTF.Schema.GLTFTexture
- [x] GLTF.Scene-> GLTF.Schema.GLTFScene

**Comment by blgrossMS** [comment]
I'm for this change. Feel free to make a PR

**Comment by StephenHodgson** [comment]
Will do.

**Comment by StephenHodgson** [comment]
Not sure if we should also rename camera, animation, and scene.
