### ISSUE TITLE
No GLB With Images Encoded In Container

### ISSUE THREAD

**Issue by MackeyK24** [KhronosGroup/UnityGLTF#201]
Excuse Me... But I thought the whole point of GLB container files was to be able to PACK the json, bin and all images into the .glb

But I cant find NOT ONE example of encoding images into the glb. The ONLY thing I can find is SaveGLB with save the json and bin into the glb ... But writes the images as separate image files...

What is the point of that... Not much different than gltf json export you dont need a operate server call for the matching .bin... But that only the bin... What about the images ???

**Comment by janholo** [comment]
#186 This pull request addresses (and maybe already solved) the same problem.

**Comment by blgrossMS** [comment]
Our GLB exporting does not fully work yet, feel free to make a PR to fix the functionality.

**Comment by MackeyK24** [comment]
The fixes to images.cs works perfect. 
Somebody should add the ‘.Id’ to the the bufferView line and get that updated in the core GLTFSerialzation project
