### ISSUE TITLE
Importing animated models from Blender where skeleton = 0 crashes

### ISSUE THREAD

**Issue by enaraartetxe** [KhronosGroup/UnityGLTF#202]
Hi, I have animated an .obj in mixamo, downloaded as collada and exported to Gltf using Blender's exporter. The problem is that in GLTFSceneImporter the SetupBones method crashes on 
`renderer.rootBone = _assetCache.NodeCache[skin.Skeleton.Id].transform;` because the node that's trying to access is null. Looking at the Gltf file, Blender exports the skeleton as 0.

I've solved it by checking if the skeleton node is null and if so assigning the renderer.rootBone to the sceneObj created in ConstructScene, but not sure if it's the right solution. Can anyone confirm me this, please?

I attach the blend file and the exported gltf files.
[astronaut.zip](https://github.com/KhronosGroup/UnityGLTF/files/2183539/astronaut.zip)

**Comment by Yonerida0923** [comment]
I have same problem too.

**Comment by SubtleMetaphor** [comment]
This issue still isn't fixed.

[skinned mesh gltf bug.zip](https://github.com/KhronosGroup/UnityGLTF/files/2567820/skinned.mesh.gltf.bug.zip)

**Comment by AdamMitchell-ms** [comment]
I just tested this again because I put in a fix for a similar issue.  Unfortunately, now it has an infinite recursion bug.

**Comment by pfcDorn** [comment]
Fixed in latest release
