### ISSUE TITLE
Fresh pull from repository doesn't open properly in Unity

### ISSUE THREAD

**Issue by StephenHodgson** [KhronosGroup/UnityGLTF#203]
Master branch does not compile in Unity 5.6
Getting lots of errors about missing GLTF namespace reference.

**Comment by blgrossMS** [comment]
You just need to build the dll's from the GLTFSerialization

**Comment by StephenHodgson** [comment]
Not sure if that's an acceptable answer.

There's not documentation nor steps to accomplish this.

**Comment by StephenHodgson** [comment]
The unity project should open without compiler errors.

**Comment by blgrossMS** [comment]
It's in the Readme: https://github.com/KhronosGroup/UnityGLTF/blob/master/README.md 

The plan is to separate that project out to a separate repo and build the binaries on a build server (rather than a personal device)
