### ISSUE TITLE
How to Build Unity Game using UnityGLTF (Shaders problem)?

### ISSUE THREAD

**Issue by Vytek** [KhronosGroup/UnityGLTF#206]
This is my Unity config:

Versions
  Unity: 2017.3.1f1 (fc1d3344e6ea)
  VRTK: 3.3.0 (may not be correct if source is GitHub)
  SteamVR: 1.2.3
VR Settings
  Standalone: None, OpenVR
Scripting Define Symbols
  Standalone: VRTK_DEFINE_SDK_STEAMVR;VRTK_DEFINE_STEAMVR_PLUGIN_1_2_1_OR_NEWER;VRTK_DEFINE_STEAMVR_PLUGIN_1_2_2_OR_NEWER
  WSA: VRTK_DEFINE_SDK_WINDOWSMR
  WSA: VRTK_DEFINE_SDK_WINDOWSMR

I am workin on:
Version system:	macOS 10.13.6 (17G65)
Version kernel:	Darwin 17.7.0

In Editor all works fine. But when I am trying to build my demo I have in log:

07-20_08-56-30: Console Log (Exception): ShaderNotFoundException: GLTF/PbrMetallicRoughness not found. Did you forget to add it to the build?
UnityGLTF.StandardMap..ctor (System.String shaderName, System.Int32 MaxLOD) (at <6e2e72fb449c4779bd7a6f55349ab1e6>:0)
UnityGLTF.MetalRough2StandardMap..ctor (System.String shaderName, System.Int32 MaxLOD) (at <6e2e72fb449c4779bd7a6f55349ab1e6>:0)
UnityGLTF.MetalRoughMap..ctor (System.Int32 MaxLOD) (at <6e2e72fb449c4779bd7a6f55349ab1e6>:0)
UnityGLTF.GLTFSceneImporter.ConstructMaterial (GLTF.Schema.Material def, System.Int32 materialIndex) (at <6e2e72fb449c4779bd7a6f55349ab1e6>:0)
UnityGLTF.GLTFSceneImporter+<ConstructMeshPrimitive>c__Iterator11.MoveNext () (at <6e2e72fb449c4779bd7a6f55349ab1e6>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <4b58939e897a4c34942efe344ae250a9>:0)

So I am trying to include shader in "Graphics" settings as file:

![schermata 2018-07-20 alle 09 25 37](https://user-images.githubusercontent.com/2614303/42990303-99ea7d30-8c02-11e8-9432-a8fe75d352cf.png)

**But the build doesn't works.** Unity freeze on creating globalgamemanagers.assets:
https://answers.unity.com/questions/918996/unity-5-freezes-while-building.html

Now I include GLTF/PbrMetallicRoughness.shader in Assets/Resources dir, but I have seen that PBR Materials doesn't work fine :_( 

How to fix the issue? I would like to write a little guide of how create a perfect build with UnityGLTF.

Thanks you!

**Comment by Vytek** [comment]
GLTF Models of test:
https://gateway.ipfs.io/ipfs/QmerSDvd9PTgcbTAz68rL1ujeCZakhdLeAUpdcfdkyhqyx
https://gateway.ipfs.io/ipfs/QmPqQ7RANMBygjFREHhF41LDZ6zypHc4G3y3q4uuAyacmu

PBR Texture work fine in Editor NOT in Player Build:

![unity_2018-07-21_11-44-04](https://user-images.githubusercontent.com/2614303/43034378-9810bd88-8cdb-11e8-87f1-36e353e91ea2.png)

**Comment by Vytek** [comment]
### Perhaps i found hotw to fix the issue.

This works with (but I suppose also for other Unity versions):

![unity_2018-07-21_16-05-42](https://user-images.githubusercontent.com/2614303/43036340-3559f932-8d00-11e8-9596-6c50e2ff6594.png)

1) NOT USE:  NOT include GLTF/PbrMetallicRoughness.shader in (Edit -> Project Settings -> Graphics)  This configuration freeze Unity building in "globalgamemanagers.assets". You had to kill the process and restart Unity Editore.

2) NOT USE: copy GLTF/PbrMetallicRoughness.shader in Assets/Resources directory fix the log error, but the Unity Player not renderer PBR or alpha texture correctly (see previous images on other posts).

3) CORRECT: Create a ShaderVariants (Edit -> Project Settings -> Graphics) Save to Asset and load your shadervariants. Check in Editor Inspector if your shadervariants contains GLTF/PbrMetallicRoughness.shader , if not add it ;-)

![unity_2018-07-21_16-03-19](https://user-images.githubusercontent.com/2614303/43036507-a66056fa-8d03-11e8-9007-93e713a850bd.png)

![unity_2018-07-21_16-02-26](https://user-images.githubusercontent.com/2614303/43036509-aadf9218-8d03-11e8-9705-67d4e46513fe.png)

NOW ALL WORKS! 

Please confirm if my fix is corret and I will close the issue here.

**Comment by blgrossMS** [comment]
Sounds good. Send out a PR

**Comment by reubenkcoutinho** [comment]
This works on 2018.2. Managed to build the app for android!

**Comment by Vytek** [comment]
As request by @blgrossMS:

https://github.com/KhronosGroup/UnityGLTF/pull/213

**Comment by Giorat** [comment]
![schermata 2018-07-30 alle 16 10 21](https://user-images.githubusercontent.com/4527364/43402646-8043d1a6-9413-11e8-987b-4bb1bf2b7004.png)

I get black model with no textures after testing your steps @Vytek what am I doing wrong? The console/log doesn't give any error on mac or android.

**Comment by Vytek** [comment]
Which version of Unity? Check shader Variant perhaps it use also other shader? If not add it and retry!
Check my PR: https://github.com/KhronosGroup/UnityGLTF/pull/213

**Comment by Giorat** [comment]
I have just fixed my problem with the black textures on Android and Mac. I had to keep the shaders loaded in the build settings.

![schermata 2018-07-31 alle 10 49 46](https://user-images.githubusercontent.com/4527364/43448974-9468cd66-94af-11e8-8507-946074e67fee.png)

This flag should be required? By enabling it and fixing the load of the shaders will create any problem?

**Comment by Vytek** [comment]
I think so ;-)

**Comment by Giorat** [comment]
Think what?

**Comment by marcspraragen** [comment]
Noting that if you do use the saved shadervariants asset approach, the file needs to be refreshed if any new variants are introduced in GLTF files (MASK and BLEND alpha modes, in my case). Otherwise Unity might not include the new variants when building to Android.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
