### ISSUE TITLE
Add support for vertex colors

### ISSUE THREAD

**Issue by cdata** [KhronosGroup/UnityGLTF#210]
### Feature request

I am filing this issue as a formal request that the UnityGLTF plugin support vertex colors in GLTF models.

### Background

I have been loading some models from Poly into Unity using UnityGLTF. These GLTF models rely on vertex colors, but when I load them in Unity with the UnityGLTF plugin, the models are solid white.

I have been diving through the plugin and slowly uncovering the story behind the missing vertex colors in these models. Here are my findings:

 - Confirmed that models we are using rely on vertex colors (manual testing in browser).
 - Confirmed that the GLTF spec has an affordance for vertex colors (see attribute table [here](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes)).
 - Discovered that the Unity "standard" shader does not support vertex colors (particle shader does, though).
 - Confirmed that UnityGLTF plugin authors are aware of vertex colors problem ([discussion](https://github.com/KhronosGroup/UnityGLTF/issues/142#issuecomment-377867633)).
 - Discovered community forks of Unity "standard" shader to add vertex color support ([1](https://forum.unity.com/threads/standard-shader-with-vertex-colors.316529/), [2](https://github.com/H-man/UnityVertexColors); note that 2 is a fork of a fork)

**Comment by AdamMitchell-ms** [comment]
Fixed with #512
