### ISSUE TITLE
SimpleWebServer attempts to send response status after body content

### ISSUE THREAD

**Issue by cdata** [KhronosGroup/UnityGLTF#211]
The `SimpleWebServer` sometimes attempts to send a redundant 200 status at this [line](https://github.com/KhronosGroup/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/Examples/SimpleWebServer.cs#L212) after body content has been sent. The consequence of doing this is that an exception is thrown. The exception is caught [here](https://github.com/KhronosGroup/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/Examples/SimpleWebServer.cs#L217) and then another status is sent, causing another exception to be thrown.

This result is that often HTTP responses from the web server will hang indefinitely.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
