### ISSUE TITLE
More detailed ReadMe or Tutorial on design-time usage of glTF-Files?

### ISSUE THREAD

**Issue by vicung** [KhronosGroup/UnityGLTF#219]
Is there a more detailed Tutorial available somewhere on how to use the UnityGLTF library for design-time import of glTF-files?
In the Readme there's the run-time import/export and design-time import/export listed, so does design-time mean that I can actually drag and drop glTF-Models in my Unity Scene and work with them there (for example place or rotate them during the creation process of my scene) just like fbx-files? Because in the example scenarios there's only a plane in my scene view (except for the Exporter sample) and the glTF only shows up when pressing the Play-Button (I guess that is supposed to be the run-time scenarios).

In case you need more specific information on my project: 
I want to develop a geospatial Augmented Reality App in Unity therefore I want to combine an AR SDK, with .glTF 3D-Models, which were generated from 2D geo data, and spatial data structure i.e. 3D Tiles (tileset.json and .i3dm-files to define the node hierarchy and coordinate system). For the latter data types I also have to create a plugin/tool later on if I can manage to get my own glTF Objects running in Unity.

Any help is appreciated!

**Comment by vicung** [comment]
Just a small bump and trying to ask differently in hopes of getting an answer:

Is the UnityGLTF library or glTF-files in Unity even meant to be used on design-time? So can you edit the glTF-files in the Scene Editor in Unity and add interactive functionalities (with scripts or other components) instead of just loading them for display/viewing in the Game/App on run time?

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
