### ISSUE TITLE
Model without Tangent and Normal is Black

### ISSUE THREAD

**Issue by Giorat** [KhronosGroup/UnityGLTF#220]
Why does the model became almost black and you can't see the texture if you don't export the tangent and normal?

Looking at the same GLTF file with an online preview won't cause this issue.
![schermata 2018-08-22 alle 17 21 03](https://user-images.githubusercontent.com/4527364/44474924-1247b680-a634-11e8-909b-550e850075b1.png)

And seen online it's perfect: https://gltf-viewer.donmccurdy.com/

Here the GLTF model file as txt, rename it to .gltf to make it work: 
[noNormalorTangent.txt](https://github.com/KhronosGroup/UnityGLTF/files/2311082/noNormalorTangent.txt)

**Comment by emackey** [comment]
Sounds like normals are not being calculated.  Per [glTF spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0):

> Implementation note: When normals are not specified, client implementations should calculate flat normals.

**Comment by Giorat** [comment]
@emackey this should be fixable in the plugin side right?  Which file/class should calcolate them?

**Comment by emackey** [comment]
Sorry, I'm not a Unity expert.  Maybe one of the maintainers here can chime in.

**Comment by AdamMitchell-ms** [comment]
I just checked this on the latest and it renders correctly now.
