### ISSUE TITLE
ScriptedImporter interprets GLB file length incorrectly

### ISSUE THREAD

**Issue by naikrovek** [KhronosGroup/UnityGLTF#223]
I have a GLB here which validates OK but doesn't import when I drag it into the assets folder of Unity.  UnityGLTF complains with `GLTFHeaderInvalidException: File length does not match chunk header.`

A) Chunk headers don't define file length, the file header does that.
B) This glTF file (attached) loads fine everywhere I've tried.
C) This glTF file validates in Khronos' glTF-Validator with zero errors and zero warnings.

The scripted importer doesn't import valid GLB files.

[ToyWagon.zip](https://github.com/KhronosGroup/UnityGLTF/files/2318687/ToyWagon.zip)

**Comment by lmontoute** [comment]
Does this happen with runtime import as well, or just when dragging the glb into Unity?

**Comment by pfcDorn** [comment]
Fixed in latest release
