### ISSUE TITLE
Transparent materials turn opaque

### ISSUE THREAD

**Issue by MephestoKhaan** [KhronosGroup/UnityGLTF#225]
I have added a model to my iOS device that was working fine with old versions of this plugin. But now the glass is turning opaque. I am not changing the default shader.

I can even reproduce it in editor in a really weird way: https://gyazo.com/bcf71dce29334f6c0a3c28ed7c15147a

As soon as I unfold the material... they all turn opaque

**Comment by boblaublaw** [comment]
Any news here?  This is a major problem for our application.

**Comment by MephestoKhaan** [comment]
For starters, to fix the editor problem in `OBJLoader` line 147 where it says
```
currentMaterial.SetFloat("_Mode", 3);
```
it should be mode 2 (there are only 3 modes )

**Comment by AdamMitchell-ms** [comment]
I'm guessing that this could be a bug in Unity.  We correctly set the RenderType to Transparent in StandardMap.cs line 297.  But then the Unity inspector seems to set it to opaque again.

**Comment by blkot** [comment]
hey, dont know whether it is related but i sensed another weird thing that when the unity automatically set the rendertype to opaque for a material which should be transparent, if i click on anything of the material details in the inspector in UnityEditor Mode,  the material suddenly jump to be transparent and sometimes it is the other way round.
anyway what is the proper pipeline of importing a glb with different types of alpha settings?

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
