### ISSUE TITLE
Warning while exporting an object with texture 'Releasing render texture that is set to be RenderTexture.active!'

### ISSUE THREAD

**Issue by ivan2007** [KhronosGroup/UnityGLTF#226]
Exporting an object with texture produces the warning:
Releasing render texture that is set to be RenderTexture.active!
I think that the problem is this (class GLTFSceneExporter):

`destRenderTexture.Release()`

must be changed with:

`RenderTexture.ReleaseTemporary(destRenderTexture)`

**Comment by Jennilein1991** [comment]
I have the same problem :/

**Comment by Jennilein1991** [comment]
Textures with this warning will not be loaded.

**Comment by AdamMitchell-ms** [comment]
Fix is in now.
