### ISSUE TITLE
Unity 2018.1.5f1 compile errors, dotnet 4.7, 

### ISSUE THREAD

**Issue by iambumblehead** [KhronosGroup/UnityGLTF#227]
After copying the GLTFSerialization directory to my project, Unity logs several error messages to its console such as the following

> Assets/GLTFSerialization/GLTFSerialization/GLTFHelpers.cs(38,61): error CS1644: Feature `out variable declaration' cannot be used because it is not part of the C# 6.0 language specification

**Comment by kyasbal-1994** [comment]
I have similar problem `Assets/UnityGLTF/GLTFSerialization/GLTFSerialization/GLTFHelpers.cs(38,61): error CS1644: Feature `declaration expression' cannot be used because it is not part of the C# 6.0 language specification
`

**Comment by kyasbal-1994** [comment]
I've finally figured out we should add `"com.unity.incrementalcompiler": "0.0.42-preview.1"` into manifest.json then you need reimport all. I hope this information could be helpful for you.

**Comment by iambumblehead** [comment]
@kyasbal-1994 thanks for the advice. What I did, as an alternative to copying the GLTFSerialization directory... I opened UnityGLTF inside Visual Studio and rebuilt it and I ran the build script included with UnityGLTF to generate the .unity file, which I'm able to add to my existing projects.

**Comment by Jennilein1991** [comment]
> I've finally figured out we should add `"com.unity.incrementalcompiler": "0.0.42-preview.1"` into manifest.json then you need reimport all. I hope this information could be helpful for you.

Where i can find this manifest.json? :octocat:
