### ISSUE TITLE
How are GLB loaded at runtime?

### ISSUE THREAD

**Issue by iambumblehead** [KhronosGroup/UnityGLTF#229]
The best possible examples I found are [here][0] and [here.][1] I'd like to test the import functionality with a local file but am not sure how to do it.

Please excuse my novice code. This function is called from a UnityEditor Window in an attempt to load a glb file using UnityGLTF. No errors are emitted, even when the path the glb file is wrong. The Wolf does not appear in the scene.

```cs
    void LoadGLB ()
    {
        string Url = "file://Users/bumblehead/software/wolf/Wolf.glb";

        // https://github.com/KhronosGroup/UnityGLTF/blob \
        //    /03dd3739d9c08cb899f319032da53188a3c64da7 \
        //    /UnityGLTF/Assets/UnityGLTF/Scripts/Tests/Integration/GLTFTestComponent.cs
        ILoader loader = new WebRequestLoader(URIHelper.GetDirectoryName(Url));
        GLTFSceneImporter sceneImporter = new GLTFSceneImporter(
            URIHelper.GetFileFromUri(new Uri(Url)), loader);

        sceneImporter.LoadScene();
        Debug.Log("loaded");
    }
```
If I add the following code, it prints "GLTFNodes: 73". But I don't know how to add gltfRoot to the current scene.
```cs
        string GLB_PATH = "/Users/bumblehead/software/wolf/Wolf.glb";
        if (File.Exists(GLB_PATH))
        {
            FileStream gltfStream = File.OpenRead(GLB_PATH);
            GLTFRoot gltfRoot = GLTFParser.ParseJson(gltfStream);

            Debug.Log("GLTFNodes: " + gltfRoot.Nodes.Count);
        }
```

[0]: https://github.com/KhronosGroup/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/Examples/MultiSceneComponent.cs#L21-L24
[1]: https://github.com/KhronosGroup/UnityGLTF/blob/03dd3739d9c08cb899f319032da53188a3c64da7/UnityGLTF/Assets/UnityGLTF/Scripts/Tests/Integration/GLTFTestComponent.cs

**Comment by iambumblehead** [comment]
Please excuse my novice code. This function is called from a UnityEditor Window in an attempt to load a glb file using UnityGLTF.

```cs
    void LoadGLB ()
    {
        string Url = "file://Users/bumblehead/software/wolf/Wolf.glb";

        // https://github.com/KhronosGroup/UnityGLTF/blob/03dd3739d9c08cb899f319032da53188a3c64da7/UnityGLTF/Assets/UnityGLTF/Scripts/Tests/Integration/GLTFTestComponent.cs
        ILoader loader = new WebRequestLoader(URIHelper.GetDirectoryName(Url));
        GLTFSceneImporter sceneImporter = new GLTFSceneImporter(
            URIHelper.GetFileFromUri(new Uri(Url)), loader);

        sceneImporter.LoadScene();
        Debug.Log("loaded");
    }
```

**Comment by NDrexlAxonom** [comment]
I was able to get a GLB loaded by getting the streams ready and just used them instead of using the URL loading way.

In my case, I downloaded the GLB off the web, loaded the bytes I received in a MemoryStream and used that. FileStream should work fine too.

```
//'stream' being your filestream/memorystream
GLTF.Schema.GLTFRoot gLTFRoot = GLTF.GLTFParser.ParseJson(stream);
ILoader loader = null;
UnityGLTF.GLTFSceneImporter sceneImporter = new UnityGLTF.GLTFSceneImporter(
               gLTFRoot,
               loader,
               stream
               );
yield return sceneImporter.LoadScene(-1, false);
```

**Comment by iambumblehead** [comment]
@NDrexlAxonom thank you :) your sample works well for me, but leads me to a separate problem that I'll make a new issue for.
