### ISSUE TITLE
Export selected or scene causes runtime Null exception

### ISSUE THREAD

**Issue by iambumblehead** [KhronosGroup/UnityGLTF#231]
My scene consists of the default camera and light with a single model, [the wolf fbx found here.][0] When I try to export the scene or the selected wolf model, a runtime Null exception occurs. It appears to [originate here.][1]

using: _Unity 2018.1.5f1_

```
ArgumentNullException: Argument cannot be null.
Parameter name: shader
UnityEngine.Material..ctor (UnityEngine.Shader shader) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Shader.bindings.cs:97)
UnityGLTF.GLTFSceneExporter..ctor (UnityEngine.Transform[] rootTransforms, UnityGLTF.RetrieveTexturePathDelegate retrieveTexturePathDelegate) (at Assets/UnityGLTF/Scripts/GLTFSceneExporter.cs:89)
```

[0]: https://free3d.com/3d-model/wolf-rigged-and-game-ready-42808.html
[1]: https://github.com/KhronosGroup/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/Scripts/GLTFSceneExporter.cs#L89

**Comment by cpetry** [comment]
I have the same issue!

**Comment by andreasplesch** [comment]
#393 could be the same issue.

**Comment by pfcDorn** [comment]
Fixed in latest release
