### ISSUE TITLE
Missing references

### ISSUE THREAD

**Issue by Jennilein1991** [KhronosGroup/UnityGLTF#236]
Hello :)
After i cloned your project and opened it in Unity 2018.2.0b many error like "namespace name 'GLTF' could not be found". Any idea?

Thanks :)

**Comment by blgrossMS** [comment]
The project GLTFSerialization/GLTFSerialization.sln needs built to generate the dll's. Please refer to the instructions in the Readme.md. 

Let me know if that fixes the issue

**Comment by Jennilein1991** [comment]
I never before built a file in vs :/ 
When i open the sln file in vs2015 then it says: The project requires a platform SDK (UAP, Version=10.0.14393.0)

After installing the windows sdk this error does not disappear.

**Comment by blgrossMS** [comment]
The sln does need to be built using VS 2017 I believe. We do have a task out to make the dll's build via our build server.

**Comment by Jennilein1991** [comment]
now it works :) thanks

**Comment by BilxaoBS** [comment]
@Jennilein1991 Hi! can you please help me out here, how you resolved the issues?
