### ISSUE TITLE
Whitespace in Texture name

### ISSUE THREAD

**Issue by Jennilein1991** [KhronosGroup/UnityGLTF#241]
Hello :)
Today I exported a model into GLTF in which some texture names had a whitespace in it.
For example: Picture 9.png.
When exporting into gltf the uri is set to Picture%209.png. So when loading this gltf, these textures can not be found.

I guess the whitespace is encoded with %02.
Would be nice if it can be fixed somehow.

Thanks!

**Comment by emackey** [comment]
Hi @Jennilein1991, the glTF spec defines URIs [in this section](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#uris), and specifically allows percent-encoding of reserved characters in the URI.  So, `%20` is a valid encoded space, and generally un-encoded spaces are not allowed in URIs.  It is the job of the client/reader/viewer to decode the URIs correctly.

It's interesting that this topic has not come up more often.  I wonder if we need a sample model or validation or something to address this.  But at the very least, `%20` is allowed as an encoding.

**Comment by Jennilein1991** [comment]
Hi @emackey Thanks for your answer! Okay then i have to check my importer library if it can handle it somehow :)
