### ISSUE TITLE
UWP compiler error

### ISSUE THREAD

**Issue by calebcannon** [KhronosGroup/UnityGLTF#244]
https://github.com/KhronosGroup/UnityGLTF/blob/a0201a17abe24aefb48665cc330d5b9243f7693e/UnityGLTF/Assets/UnityGLTF/Scripts/Cache/AssetCache.cs#L97

Should probably be `bufferCacheData.Stream.Dispose();`

**Comment by ivan2007** [comment]
This is a duplicate of #240
