### ISSUE TITLE
RoughnessFactors of materials get ignored

### ISSUE THREAD

**Issue by tolen23** [KhronosGroup/UnityGLTF#251]
When loading a gltf for which a roughnessFactor has been specified under property pbrMetallicRoughness, this factor gets obviously ignored.

Example gltf: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/OrientationTest

The BaseCubeMesh there is associated with the following material:
```
"materials" : [
        {
            "name" : "BaseMaterial", 
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [
                    0.3401939868927002, 
                    0.6781029105186462, 
                    1.0, 
                    1.0
                ], 
                "roughnessFactor" : 0.5
            }
        },
        [...]
]
```

Expected behaviour after loading this into Unity would be to see Roughness set to 0.5. Instead it is always set to 1.0:

![material_shader](https://user-images.githubusercontent.com/43646039/46156658-3d987380-c27a-11e8-845e-2d68a03cb016.PNG)

This can also be reproduced with the standard material example from the gltf 2.0 spec:

```
"materials": [
        {
            "name": "gold",
            "pbrMetallicRoughness": {
                "baseColorFactor": [ 1.000, 0.766, 0.336, 1.0 ],
                "metallicFactor": 1.0,
                "roughnessFactor": 0.0
            }
        }
    ]
```

**Comment by AdamMitchell-ms** [comment]
Fixed in latest.
