### ISSUE TITLE
Not support  mesh animation morph

### ISSUE THREAD

**Issue by sain801028** [KhronosGroup/UnityGLTF#255]
I use [https://gltf-viewer.donmccurdy.com/](url) ,  
my model is normal :

<img width="1602" alt="screen shot 2018-09-28 at 11 42 18" src="https://user-images.githubusercontent.com/17377422/46186894-936d2a00-c313-11e8-9146-af837e439c94.png">

I use UnityGLTF error :
<img width="1841" alt="screen shot 2018-09-28 at 11 40 51" src="https://user-images.githubusercontent.com/17377422/46186859-64ef4f00-c313-11e8-85c8-a022b4c5ce51.png">

I use File:
[9b5de018fd8442f0ba37acc93d24138c641e62c0beed4a0c92499ec073646228.glb.zip](https://github.com/KhronosGroup/UnityGLTF/files/2426676/9b5de018fd8442f0ba37acc93d24138c641e62c0beed4a0c92499ec073646228.glb.zip)

**Comment by yaakovyitzchak** [comment]
Im also having this issue --- would be great to see some kind of solution, it somehow works for the example models, just not most normal models

**Comment by pfcDorn** [comment]
Fixed in latest release
