### ISSUE TITLE
Rotation flipped?

### ISSUE THREAD

**Issue by Jennilein1991** [KhronosGroup/UnityGLTF#256]
Hello :)
I like your GLTF Export tool!

I have a question:
When I export a gameObject with rotation (0, 180, 0), then UnityGLTF exports this object into a GLTF file with the rotation quaternion (0, -1, 0, 0).

But when I convert this quaternion to degree the converted rotations comes out: (0, -180, 0)

It should be like this or did i missunderstand it?

Thanks :)

**Comment by soadzoor** [comment]
Correct me if I'm wrong, but -180 and 180 degree rotations both seem to yield the same results to me (half of a full rotation). So unless it's done with an animation, it doesn't matter which way it turns 180 degrees.

**Comment by dave-hill** [comment]
I've just created PR #294 to add some comments to help explain how some of this math works.
