### ISSUE TITLE
BumpMap Export Incorrect

### ISSUE THREAD

**Issue by robertlong** [KhronosGroup/UnityGLTF#26]

**Comment by stevenvergenz** [comment]
Normal maps are technically exported, but they are converted to greyscale for some reason. Need to investigate.

**Comment by AurL** [comment]
Normal maps images can either be grayscales (bump maps) converted to normal maps by Unity or normal maps.
You can get this information using [TextureImporter object](https://docs.unity3d.com/ScriptReference/TextureImporter.html) and looking for `convertToNormalmap` as done [here](https://github.com/sketchfab/Unity-glTF-Exporter/blob/master/SceneToGlTFWiz.cs#L1119-L1134)

If you export the image without checking this, you will end with greyscale textures when "convertToNormalmap" is true (i.e original image is bump)

I hope it helps

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
