### ISSUE TITLE
Cannot Build for UWP - System.Threading - Unity 2018.1.0b13

### ISSUE THREAD

**Issue by Chalghouma** [KhronosGroup/UnityGLTF#260]
Those are the errors i'm getting when building for UWP/PC using : 

1. Windows SDK 10.0.17134 
2. .NET Scripting Backend
3. .NET 4.x as a Scripting Runtime Version / Api Compatibility Level

Most of the errors are related to non-existing Enums/Methods/Properties in System.Threading when building.

![image](https://user-images.githubusercontent.com/17048203/46339632-3df28f00-c62b-11e8-995d-eba42e7254c1.png)

**Comment by mhochk** [comment]
The UWP build is completing locally without error in 2018.4.14f1 as of #548.  If you are still running in to issues like these please open a new issue and I'll be happy to look in to it.

**Comment by Chalghouma** [comment]
Thanks a lot for the fix.
Keep rockin'
