### ISSUE TITLE
New shader needed for pbrMetallicRoughness

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/UnityGLTF#261]
Currently UnityGLTF uses a modified Unity Standard shader for its materials. This is a pain for several reasons:

1. The Standard shader is huge, and only a fraction of its code paths are actually used by UnityGLTF (many are for static/prebuilt setups). Getting all the shader variants that you need into a build is difficult and time-consuming.
2. The Standard shader is computationally expensive, and has no good low-fidelity fallbacks for mobile.
3. The Standard shader does not support several spec-mandated requirements: custom UV channels, GL-style normal maps, and side-by-side linear and sRGB textures.
4. It has a dependency on changing Unity cginc files, so engine upgrades become more complicated.

There has been some talk of porting the [glTF-DXViewer](https://github.com/Microsoft/glTF-DXViewer) from DX-flavored HLSL to Unity-flavored HLSL. That shader was originally ported from the GLSL [glTF-WebGL-PBR](https://github.com/KhronosGroup/glTF-WebGL-PBR), so there's a conversation to be had about whether to re-port from source or to port the port, assuming that we want to use this shader at all.

Any opinions on this? I'd like to tackle this in the near future.

**Comment by MaartenBreeedveld** [comment]
Just that it would be awesome!

Especially the forth point is a bit of an ugly workaround. Though I think it could be included in the default package right?
