### ISSUE TITLE
How to istantiate object GLTF in runtime

### ISSUE THREAD

**Issue by fral8** [KhronosGroup/UnityGLTF#263]
Hi to everybody. I want to download my GLB model from a server and instantiate it dinamically.
I've found  the example "AnimatedCube" that uses REST to locate the file.
I've used in param a local URI (for debugging) to locate  my GLB object.
![img1](https://user-images.githubusercontent.com/37425139/46422220-27842a80-c734-11e8-9844-b7dedf9574d3.PNG)
But when I try to load it, pressing START button, I obtain in console the following errors:
![img2](https://user-images.githubusercontent.com/37425139/46422305-58645f80-c734-11e8-8ced-e5e2aaf8f4e3.PNG)
I've not modified the script.
Please help me.
Frank

**Comment by MaartenBreeedveld** [comment]
Here it will also work if you set it to a location on your harddrive i.e. 
c:\SomeFolder\SomeModel.gltf  (the extension .glb) should also work..
