### ISSUE TITLE
GLTF loaded as a stream

### ISSUE THREAD

**Issue by Jennilein1991** [KhronosGroup/UnityGLTF#265]
Hei ! :)
When I import a GLTF model into Unity using your tool, the import is like a stream. So the model is constructed at runtime in Unity (can be seen in the Unity editor) and after some time the whole mode is constructed. 
Is there a way that the model can be imported in a direct way?

**Comment by ericob** [comment]
@dave-hill

**Comment by soadzoor** [comment]
How do you import your gltf model at all? I can't do it, nothing appears on my scene.. :(

**Comment by ericob** [comment]
What do you mean by direct? You can load it as a glb at design time.
