### ISSUE TITLE
Runtime load glb file and assgin AVPRO video mat  error

### ISSUE THREAD

**Issue by fingerx** [KhronosGroup/UnityGLTF#268]
when load glb file and assgin avpro video mat found material uv mess

1.  avpro v1.9.2
2. Unity GLTF 2.0
3. using 3dmax 2018 and Babylon export , model mat is max dafault mat

**Comment by ericob** [comment]
Hi @fingerx, could you provide more details about the scenario you're trying to accomplish? What error are you running into? Screenshots would be very helpful. Thanks!

**Comment by fingerx** [comment]
@ericob sorry,this avpro error.Thanks
