### ISSUE TITLE
GLTF.Schema.CameraType is defined multiple times

### ISSUE THREAD

**Issue by soadzoor** [KhronosGroup/UnityGLTF#269]
Hey,

I'm having troubles opening up the Unity Project, and also building the GLTFSerializer.
I've tried to do everything as it can be found in README, there may be some steps I'm missing. I'm using unity's latest version (2018.2.12f1), if that matters.

Here are a few screenshots about my problems:
![capture](https://user-images.githubusercontent.com/10392261/46909729-689bec00-cf37-11e8-8ff3-32e2fe9227b9.PNG)
![capture2](https://user-images.githubusercontent.com/10392261/46909731-6b96dc80-cf37-11e8-8898-72ad9bd25170.PNG)
![capture3](https://user-images.githubusercontent.com/10392261/46909752-b0227800-cf37-11e8-98c7-b14111b23e92.PNG)

And this is what happens when I try the "release" package:
![capture4](https://user-images.githubusercontent.com/10392261/46909903-aa7a6180-cf3a-11e8-9b2a-005c66ece579.PNG)

I'm a rookie when it comes to Unity, or to this tool.
Any help is appreciated!

**Comment by soadzoor** [comment]
No one? :(

**Comment by blgrossMS** [comment]
The build project is having problems it seems because the GLTFSerialization dlls in your plugins folder need to be marked as UWP vs Standalone/editor. 

The release version not working is a different issue

**Comment by soadzoor** [comment]
Thank you for answering @blgrossMS .
Finally, I was able to build the GLTFSerialization solution from VS 2017 community with checking the "Allow unsafe" checkbox for the projects. However, it doesn't seem to be working with the newest Unity version. I tried the older one mentioned in README (5.6.5f1), and with that, it seems to be partially working: exporting works. Importing doesn't give errors, but assets only appear on runtime. Is that a normal behavior?

Any reason why it doesn't work at all with the latest unity versions? Is it just me? Also, what does `dlls in your plugins folder need to be marked as UWP vs Standalone/editor.` mean? How do I mark them as UWP?

Thank you, and sorry for my noob questions

**Comment by soadzoor** [comment]
Hi @robertlong , thanks for the answer.

Okay, so that was one of the problems: there's no information in the README that I should import this dll straight into unity. Also, when I do, I get this window (as you can see I don't have SDK option to choose UWP):
![capture](https://user-images.githubusercontent.com/10392261/47493703-4156f000-d850-11e8-9c1e-1486cfe5fde0.PNG)

**Comment by robertlong** [comment]
Hmm. Maybe you don't have the UWP target installed and so it doesn't show up? You can just uncheck all the platforms then.

Hopefully there's a way to automate setting these properties on the dlls after they are compiled. I guess the packaging script can run a small C# script that sets all of those properties correctly Or you could modify the .meta file directly but that sounds a bit dangerous.

**Comment by soadzoor** [comment]
Thanks for getting back, and sorry for being so late with my answer. I'm pretty sure I checked the UWP checkboxes when I installed unity. Anyway, I finally got it working somehow. Although the `README` could be more "noob friendly", like step-by-step. I think that would help people like me, and also that would prevent these questions from coming up regularly

**Comment by ericob** [comment]
We now copy meta files from the built GLTFSerialization.sln. This should fix your issue.
