### ISSUE TITLE
UnityGLTF export gameobject without texture and mesh for custom prefab

### ISSUE THREAD

**Issue by paul-bonnel-fr** [KhronosGroup/UnityGLTF#277]
Hello everyone, 
I was able to make this project compile and run with my unity 2018.2.10f1. I played with the scenes you guys provided. Indeed it is very straightforward to export simple scene which contains cubes, cylinders, planes and capsules. 

It's gets a little bit more complicated when it comes to export a custom prefab with a complicated meshes and textures. Here is the gameobject I want to export in GTLF 
![image](https://user-images.githubusercontent.com/33127779/47344090-e97d8500-d6a7-11e8-9bb6-cfbbfc3ffac1.png)

The export itself works well but the files generated *.gltf and *.bin does not seems to contains the textures and the spider mesh. Here is the preview of the gltf generated by UnityGLTF
![image](https://user-images.githubusercontent.com/33127779/47344340-85a78c00-d6a8-11e8-8cc6-8c27bac5e19f.png)

It's like UnityGLTF plugin only allow simple mesh to be exported into GLTF. Did you guys notice this type of behavior ? Is there something I'm missing here ? 

Here is the model I tried to export in GLTF from unity : 
https://free3d.com/3d-model/spider-animated-low-poly-and-game-ready-87147.html

Thank you, 
Paul

**Comment by pfcDorn** [comment]
Fixed in latest release
