### ISSUE TITLE
Error loading JSON of gltf's GLB stream

### ISSUE THREAD

**Issue by alxdncn** [KhronosGroup/UnityGLTF#280]
I have a model that loads fine in Sketchfab but when I use the real-time library, I get the following error:

> Exception: Dictionary must be an object at: meshes[0].primitives[0].targets[0].NORMAL
GLTF.Extensions.JsonReaderExtensions.ReadAsDictionary[AccessorId] (Newtonsoft.Json.JsonReader reader, System.Func`1 deserializerFunc)
GLTF.Schema.MeshPrimitive+<>c__DisplayClass8_0.<Deserialize>b__1 ()
GLTF.Extensions.JsonReaderExtensions.ReadList[Dictionary`2] (Newtonsoft.Json.JsonReader reader, System.Func`1 deserializerFunc)
GLTF.Schema.MeshPrimitive.Deserialize (GLTF.Schema.GLTFRoot root, Newtonsoft.Json.JsonReader reader)
GLTF.Schema.GLTFMesh+<>c__DisplayClass4_0.<Deserialize>b__0 ()
GLTF.Extensions.JsonReaderExtensions.ReadList[MeshPrimitive] (Newtonsoft.Json.JsonReader reader, System.Func`1 deserializerFunc)
GLTF.Schema.GLTFMesh.Deserialize (GLTF.Schema.GLTFRoot root, Newtonsoft.Json.JsonReader reader)
GLTF.Schema.GLTFRoot+<>c__DisplayClass20_0.<Deserialize>b__7 ()
GLTF.Extensions.JsonReaderExtensions.ReadList[GLTFMesh] (Newtonsoft.Json.JsonReader reader, System.Func`1 deserializerFunc)
GLTF.Schema.GLTFRoot.Deserialize (System.IO.TextReader textReader)
GLTF.GLTFParser.ParseJson (System.IO.Stream stream, Int64 startPosition)
UnityGLTF.GLTFSceneImporter+<LoadJson>c__Iterator5.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:294) 

When I debug the stream, I get a JSON object for meshes[0].primitives[0].targets[0].NORMAL that is the following: 

> {"NORMAL":5,"POSITION":4,"TANGENT":6} 

I'm attaching the model as well for reference.
[test_gltf.zip](https://github.com/KhronosGroup/UnityGLTF/files/2521073/test_gltf.zip)

**Comment by pfcDorn** [comment]
Fixed in latest release
