### ISSUE TITLE
Expose asset cache to consuming applications

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/UnityGLTF#286]
When I load a glTF file, I want to be able to retrieve particular texture, material, and mesh assets from the (currently `protected`) cache. Any objection if I open a PR making the scene importer assetCache publicly read-only?

**Comment by blgrossMS** [comment]
There is currently a method for getting texture out of the cache. I think it would be better to write read methods from the cache rather than having direct access to the cache itself.

**Comment by stevenvergenz** [comment]
Works for me. I'll have a PR with that and some other stuff probably next week, maybe the one after.

**Comment by stevenvergenz** [comment]
Redundant after #345
