### ISSUE TITLE
GLTF Import without UnityGLTF

### ISSUE THREAD

**Issue by Jennilein1991** [KhronosGroup/UnityGLTF#289]
Hello :) 
After i exported my model with your UnityGLTF library i want to import it, but without using your own importer. 
But when i set the transform of the model in Unity to the same transform as it was before exporting, the model does not look like before.
Which adjustments do I need to apply to the transform so it looks the same?

**Comment by Jennilein1991** [comment]
I figured out that the model has the same orientation as the original model when flipping the x scale (mirroring). Any idea why this is the case?

**Comment by Jennilein1991** [comment]
Is the local coordinate system of the original model somehow modified when exporting to an GLTF?

**Comment by bghgary** [comment]
> flipping the x scale (mirroring). Any idea why this is the case?

Unity is left-handed, -z forward.
glTF is right-handed, +z forward.

To convert between the two, one can flip z and then apply a 180 degree rotation around Y. This ends up being the same as a flip in x.

See https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#coordinate-system-and-units
The model shown is here: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoomBoxWithAxes

**Comment by tommensink** [comment]
Do you perhaps mean
Unity is left-handed, +z forward, +y up.
glTF is right-handed, +z backward, +y up

A cheaper and accurater way of transforming between the two is: 
- Convert transform to matrix, 
- invert the 2nd ([1]) column and invert the 2nd ([1]) row of the matrix, 
- convert back to transform

**Comment by bghgary** [comment]
> Do you perhaps mean
> Unity is left-handed, +z forward, +y up.
> glTF is right-handed, +z backward, +y up

Can you elaborate? The spec says this:
> The front of a glTF asset faces +Z.

**Comment by tommensink** [comment]
Ok then y is pointing down I guess (or x pointing left). I was just trying to correct your comment which said the same for Unity and Gltf.
