### ISSUE TITLE
UnityGLTF Exporter - transformation of vertex positions etc.

### ISSUE THREAD

**Issue by Jennilein1991** [KhronosGroup/UnityGLTF#290]
Hello :),
when importing a GLTF model with your importer the function TransformAttributes will be executed to transform all the attributes. Will this also be executed when exporting a model? Or why is this transformation necessary?

When importing a GLTF model the following steps are down, right? : 

- the transform in the GLTF file will be transformed to Unitys coord system 

- all the attributes like vertex position etc. are adjusted based on Unitys coord system

But when exporting a GLTF model i can not see in the code that any attributes will be changed.

**Comment by bghgary** [comment]
I'll defer the exporter questions to @azakariaMSFT.

You have multiple questions here, so I'll just answer one of them first.

> why is this transformation necessary?

I just answered your other question [here](https://github.com/KhronosGroup/UnityGLTF/issues/289#issuecomment-438025826). The coordinate systems differences are the reason for these transformations.
