### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by wagnerpatriota** [KhronosGroup/UnityGLTF#291]
Some models that I try to load I get:

NullReferenceException: Object reference not set to an instance of an object
UnityGLTF.GLTFSceneImporter.InitializeAssetCache () (at Assets/UnityGLTF/Scripts/G LTFSceneImporter.cs:359)
UnityGLTF.GLTFSceneImporter+<_LoadScene>c__Iterator7.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:378)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

**Comment by ericob** [comment]
Could you share a model that runs into this exception?

**Comment by wagnerpatriota** [comment]
@ericob , here it is: http://wagnerpatriota.com/sample.zip

**Comment by tiancaipipi110** [comment]
Same here, here're the models that run into this exception:
https://sketchfab.com/models/c2f52afa064f44a6a8aa1e73bf92b4ae
https://sketchfab.com/models/2561a93bfad74575a8a420432c894080

**Comment by pfcDorn** [comment]
Fixed in latest release
