### ISSUE TITLE
MeshCache slow

### ISSUE THREAD

**Issue by tufeixp** [KhronosGroup/UnityGLTF#292]
For those models with large mesh count/number , ConstructAttributesForMeshes() works too slow!

**Comment by blgrossMS** [comment]
I have a change in staging which puts it on the background thread and removes the yields for performance gains. If you have further fixes feel free to contribute them! I know one area we can improve on here is reducing the copies between the attribute construction and loading it into Unity

**Comment by ericob** [comment]
The change is in, let us know if this alleviates your issue.
