### ISSUE TITLE
need bounds parameter before ConstructMesh

### ISSUE THREAD

**Issue by tufeixp** [KhronosGroup/UnityGLTF#293]
That's the only way we don't need to hide the mesh before loading complete. Anyway to get access to accessor.min/max ?

**Comment by ericob** [comment]
The accessor min and max will be in the GLTFRoot if you parse it yourself and then pass it into GLTFSceneImporter.

**Comment by FreakTheMighty** [comment]
@ericob I think this use case warrants a bit more discussion. My use case is similar. I am loading meshes that have custom vertex attributes as outlined in the glTF spec [here](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes). 

When using the `LoadScene` API, its not easy to access the `GLTFRoot`. The only way to access it is to essentially re-implement the `LoadScene` method which isn't really [that small a chunk of code](https://github.com/KhronosGroup/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/Runtime/Scripts/GLTFSceneImporter.cs#L293-L352).

A simple solution would be to make a read-only attribute, so it can be viewed on the importer after `onLoadComplete` is called.
