### ISSUE TITLE
Support UnityGLTF on HoloLens

### ISSUE THREAD

**Issue by yaqinh** [KhronosGroup/UnityGLTF#296]
**Describe the bug**
When use the GLTF submodule to import GLTF file at runtime in HoloToolkit, I find that it could not load the model at all when the project runs on HoloLens. Personally I believe it is because System.IO access (like FileStream would be denied by HoloLens system) 

**To Reproduce**
Link: https://github.com/yaqinh/Unity-HoloToolkit-GLTF-HoloLens
Please see the Readme file in the repo

**Expected behavior**
The duck.gltf model should appear in the scene and the textMesh should be "flag is true"

**Actual behavior**
The duck.gltf never loads in the scene and the textMesh is the path to the app local folder, which means the GLTF importer never finishs correctly

**Screenshots**

**Unity Editor Version**
2017.4.14F1

**Mixed Reality Toolkit Release Version**
2017.4.2.0

**Additional context**
Could you confirm that the API System.IO.File in Unity does not work at all on HoloLens? Do you have any suggestion about how to make GLTF importer work on HoloLens? Thanks!

**Comment by blgrossMS** [comment]
Hi @yaqinh,

You will want to use the [StorageFolder loader](https://github.com/KhronosGroup/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/Scripts/Loader/StorageFolderLoader.cs). System.IO is supported on the UWP platform, however it does not interface with RuntimeBroker which means that it cannot get access to most of the file system.

Additionally, with StorageFolders, if you want to access anything outside of app folders, you will need to include special permissions in your appxmanifest for the folders you want to access (like Pictures or 3D Objects). The way to access these at runtime is through [KnownFolders](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.KnownFolders). 

Hope this helps.

**Comment by yaqinh** [comment]
Hi @blgrossMS ,

Thanks for your quick reply. Is

**Comment by JSWorkspace1** [comment]
Hello @yaqinh @blgrossMS 
I am currently having the same Problem but I dont quite understand how to use the StorageFolderLoader. Could you please give me an example how to use it. 

My Current Code looks like this and works in the fine in the unity editor but not when build for the hololens:

                var path =Path.Combine(Application.persistentDataPath, "myObject.glb");
                var model = new GameObject(name);
                var gltfScript = model.AddComponent<GLTFComponent>();
                gltfScript.loadOnStart = false;
                gltfScript.GLTFUri =path;
                gltfScript.UseStream = true;
                gltfScript.Multithreaded = true;
                Task loadGLTF = gltfScript.Load();
