### ISSUE TITLE
NullReferenceException when loading skeletal animation

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/UnityGLTF#304]
This file is loaded by every other app just fine, and passes validation, but throws the below error in UnityGLTF: [altspace-cube - Copy.zip](https://github.com/KhronosGroup/UnityGLTF/files/2626960/altspace-cube.-.Copy.zip)

```
NullReferenceException: Object reference not set to an instance of an object
UnityGLTF.GLTFSceneImporter+<SetupBones>d__61.MoveNext () (at <a63ed9cb9b854f709fa6f4b9577efac1>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
```

I don't have time to track this down right now. Any ideas?

**Comment by yaakovyitzchak** [comment]
Im having a siilar issue with a simple skinned mesh exported from blender -- any ideas?

**Comment by InnoLuke** [comment]
I am also still having this issue

**Comment by julia1981** [comment]
me too

**Comment by InnoLuke** [comment]
I was having this issue with a GLB model exported with the built-in exporter in Cinema 4D. I worked around the issue by exporting the model as FBX instead, and then using https://github.com/facebookincubator/FBX2glTF to convert the FBX to a GLB, which then worked well with UnityGLTF.

**Comment by julia1981** [comment]
thank you @InnoLuke for the tip. unfortunately, I cannot use it in this form. Since I develop for Android. Are there no other possibilities? For me, it is important to fix this problem. Thanks a lot!

**Comment by yaakovyitzchak** [comment]
@julia1981  I just used siccity gltf ladder, a lot simpler and actually works

**Comment by julia1981** [comment]
@yaakovyitzchak Thank you very much, unfortunately you cannot export at runtime. 😪

**Comment by yaakovyitzchak** [comment]
Oh brutal, that is correct lol.. I guess someone needs to add it some way

**Comment by pfcDorn** [comment]
Fixed in latest release
