### ISSUE TITLE
how to do   UWP build        unity2017.4.5f1

### ISSUE THREAD

**Issue by kknsy** [KhronosGroup/UnityGLTF#313]
How to do

“the binaries in UnityGLTF\Assets\UnityGLTF\Plugins should be configured for everything but UWP. The binaries in UnityGLTF\Assets\UnityGLTF\Plugins\UWP should be configured for UWP”

not find Plugins\UWP      and    “error CS1704: An assembly with the same name `GLTFSerialization' has already been imported. Consider removing one of the references or sign the assembly”

**Comment by KermMartian** [comment]
I'm running into the same problem.

**Comment by blgrossMS** [comment]
Should now be fixed due to meta file copying I added in #315 . Let me know if this solves the problem.

**Comment by kknsy** [comment]
Thank you，There is still a little problem.
![image](https://user-images.githubusercontent.com/26211860/49503683-fdc1be00-f8b2-11e8-9c55-1b0234580632.png)
I deleted the extra files.
![image](https://user-images.githubusercontent.com/26211860/49504052-e59e6e80-f8b3-11e8-994b-5e87ad73ef76.png)

Import  HoloToolkit-Unity-2017.4.3.0.unitypackage

![image](https://user-images.githubusercontent.com/26211860/49503741-1a5df600-f8b3-11e8-8d33-9ef7b652acbf.png)
![image](https://user-images.githubusercontent.com/26211860/49503753-23e75e00-f8b3-11e8-89ef-29415a9b1cb2.png)
I blocked the code.
![image](https://user-images.githubusercontent.com/26211860/49503775-2e095c80-f8b3-11e8-8279-664770fb88d4.png)
No problem with build and deployment，But it is not loaded in HoloLens, I am still looking for the reason.
![image](https://user-images.githubusercontent.com/26211860/49503918-804a7d80-f8b3-11e8-88aa-9d838cd02a21.png)

![image](https://user-images.githubusercontent.com/26211860/49504004-bab41a80-f8b3-11e8-9c52-fa821262aaf0.png)

**Comment by kknsy** [comment]
@blgrossMS

**Comment by blgrossMS** [comment]
HoloToolkit doesn't work with the latest UnityGLTF due to API breaking changes.  You will need to change the creation of the GLTFSceneImporter to either have an AsyncCoroutineHelper or be null with a large BudgetPerFrameInMilliseconds so that it will load the controller synchronously. 

Also shader override is now specified via the CustomShaderName property on the GLTFSceneImporter. 

I would open an issue on the MRTK to update to later version of UnityGLTF if that would be useful to you. :)

**Comment by kknsy** [comment]
@blgrossMS  Thank you，I will try your suggestion

**Comment by kknsy** [comment]
@blgrossMS 
Now，I  shader override is now specified via the CustomShaderName property on the GLTFSceneImporter，The metal on the surface of the object is abnormal
![image](https://user-images.githubusercontent.com/26211860/50211230-118d1a00-03b3-11e9-870d-15e248f31db6.png)
In UWP ，Can load normally but The loaded model is not ideal
![image](https://user-images.githubusercontent.com/26211860/50211469-b0197b00-03b3-11e9-8048-b60387d4ca9f.png)
![image](https://user-images.githubusercontent.com/26211860/50211480-b7d91f80-03b3-11e9-8ca2-eb78354a4bf7.png)
