### ISSUE TITLE
NUnit needs to be in Editor only

### ISSUE THREAD

**Issue by kungfooman** [KhronosGroup/UnityGLTF#316]
Hi, Unity 2018.2.17f1 detects like 6 errors, so it cannot run without a few fixes:

![nunit_error](https://user-images.githubusercontent.com/5236548/49522134-3c517b80-f8a7-11e8-9542-9ae8d4c5f172.png)

I could make it work by simply commenting the tests out, but it probably should have a proper solution

https://answers.unity.com/questions/610988/unit-testing-unity-test-tools-v10-namespace-nunit.html

**Comment by blgrossMS** [comment]
These are intended to be play mode tests so they can't be editor only. There is a difference with Unity between 2018.2 and 2017.4 in how it handles tests. We will need to fix them to work properly in 2018.2
