### ISSUE TITLE
DamagedHelmet viewangle based black areas

### ISSUE THREAD

**Issue by kungfooman** [KhronosGroup/UnityGLTF#317]
Hi, is this a known bug or supposed to work? Used version: Unity 2018.2.17f1

![unitygltf_bug](https://user-images.githubusercontent.com/5236548/49524683-85f09500-f8ac-11e8-8983-307ae753435d.gif)

**Comment by blgrossMS** [comment]
This is not happening in Unity 2017. I'll have to check it out with 2018

**Comment by pfcDorn** [comment]
Fixed in latest release
