### ISSUE TITLE
Support KHR_lights_punctual

### ISSUE THREAD

**Issue by revyTH** [KhronosGroup/UnityGLTF#324]
When exporting a scene that contains lights, for example PointLight and then import back in three.js I found that the lights are imported as generic Object3D, instead of light type. Is this the expected behavior?

**Comment by stevenvergenz** [comment]
This is deliberate, as glTF does not have a native concept of lights. There is a [ratified extension](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual) for them, and I expect at some point UnityGLTF will support that, but progress is slow.

**Comment by revyTH** [comment]
Ah ok, thanks for the information

**Comment by ericob** [comment]
Updating the title of this to track support for this extension

**Comment by clstavros** [comment]
Hello, can you please confirm this is the active thread concerning including scene lighting in Unity GLB exports and if there is any update on status (or, if I should be looking elsewhere?).  thank you!

On a related note:  I have noticed the WaterBottle.glb example has nice lighting that looks to be scene driven.  But, I cannot figure out how that was achieved.  Does anyone have an idea how that lighting was accomplished?  

Thank you.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
