### ISSUE TITLE
cann't Load GLtf Files with size more than 10MB 

### ISSUE THREAD

**Issue by Qusai-Azzam** [KhronosGroup/UnityGLTF#327]
I got this exception when I tried to load Files with sizes more than 10 MB 

`ArgumentException: out of bounds
Parameter name: offset
System.ArraySegment`1[System.Byte]..ctor (System.Byte[] array, Int32 offset, Int32 count) `

how can we fix this ?

**Comment by boblaublaw** [comment]
I suspect your glTF has some corruption or other non-size related problem.  a 32 bit signed integer can handle offsets from −2,147,483,648 to 2,147,483,647,  which is much larger than the 10,485,760 required for 10MB.

Additionally, I have loaded glTF and glb files that are much larger than 10MB.

How was your gltf created?

**Comment by lexaknyazev** [comment]
Validating an asset with [online glTF-Validator](https://github.khronos.org/glTF-Validator/) may shed some light on the issue.

**Comment by blgrossMS** [comment]
@Qusai-Azzam, are you still having an issue? Can you send an example file so that we can test the problem?

**Comment by blgrossMS** [comment]
It's because it uses the KHR_materials_pbrSpecularGlossiness which was broken in a recent commit. I'm working on a fix now.

**Comment by blgrossMS** [comment]
Fixed in PR #332
