### ISSUE TITLE
UWP Material problem@blgrossMS

### ISSUE THREAD

**Issue by kknsy** [KhronosGroup/UnityGLTF#329]
Now，I  shader override is now specified via the CustomShaderName property on the GLTFSceneImporter，The metal on the surface of the object is abnormal
![image](https://user-images.githubusercontent.com/26211860/50211230-118d1a00-03b3-11e9-870d-15e248f31db6.png)
In UWP ，Can load normally but The loaded model is not ideal
![image](https://user-images.githubusercontent.com/26211860/50211469-b0197b00-03b3-11e9-8048-b60387d4ca9f.png)
![image](https://user-images.githubusercontent.com/26211860/50211480-b7d91f80-03b3-11e9-8ca2-eb78354a4bf7.png)

_Originally posted by @kknsy in https://github.com/KhronosGroup/UnityGLTF/issues/313#issuecomment-448529643_

**Comment by blgrossMS** [comment]
What is the exception that is happening?

**Comment by kknsy** [comment]
![image](https://user-images.githubusercontent.com/26211860/50389101-55d83b80-0760-11e9-9ddc-42a1ccc8adf2.png)

**Comment by kknsy** [comment]
![image](https://user-images.githubusercontent.com/26211860/50389301-b3ba5280-0763-11e9-8f7f-ac8e1ae3595b.png)
WebServer delete，No longer report exceptions，but  Different in UNITY_EDITOR
![image](https://user-images.githubusercontent.com/26211860/50389322-f11ee000-0763-11e9-8674-a4f349bebec8.png)
![image](https://user-images.githubusercontent.com/26211860/50389367-71454580-0764-11e9-8d43-a4a7bc09965b.png)
@blgrossMS

**Comment by kknsy** [comment]
https://github.com/KhronosGroup/UnityGLTF/issues/206
The problem is solved, thank you
