### ISSUE TITLE
Usage guide

### ISSUE THREAD

**Issue by bjornsyse** [KhronosGroup/UnityGLTF#330]
Hi

How can I use this to import a GTB/GLTF file into Unity.  I 've imported the unityasset but cannot understand how to import a file. 

Regards

- Björn

**Comment by blgrossMS** [comment]
Hi @bjornsyse,

You should be able to just add a glb file and if you are on Unity 2017.1+ it should be imported. Otherwise see the example scenes for runtime usage.
