### ISSUE TITLE
 NormalMap  Display is not normal  Compare with Microsoft 3D viewer

### ISSUE THREAD

**Issue by kknsy** [KhronosGroup/UnityGLTF#331]
![image](https://user-images.githubusercontent.com/26211860/50439772-3989f980-092e-11e9-9600-e31b7747d48e.png)

Microsoft 3D viewer
![image](https://user-images.githubusercontent.com/26211860/50440017-317e8980-092f-11e9-9ebd-2a80f663b0af.png)

**Comment by blgrossMS** [comment]
@kknsy can you share the model so we can investigate further?

**Comment by ws04100236** [comment]
这是我们用于测试的部分模型，模型在非Editor的情况下运行有明显的贴图效果差异.

[MS001.zip](https://github.com/KhronosGroup/UnityGLTF/files/2716193/MS001.zip)
[ID SP 000191.zip](https://github.com/KhronosGroup/UnityGLTF/files/2716186/ID.SP.000191.zip)
[light_01.zip](https://github.com/KhronosGroup/UnityGLTF/files/2716187/light_01.zip)
[MS001.zip](https://github.com/KhronosGroup/UnityGLTF/files/2716188/MS001.zip)
[MS002.zip](https://github.com/KhronosGroup/UnityGLTF/files/2716189/MS002.zip)

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/55668073-ffb68080-5896-11e9-9683-39ded2260231.png)


![image](https://user-images.githubusercontent.com/748320/55668079-16f56e00-5897-11e9-99a9-639c31f12236.png)

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
