### ISSUE TITLE
Fix build due to auth issues

### ISSUE THREAD

**Issue by blgrossMS** [KhronosGroup/UnityGLTF#339]
The travis build continuously fails due to some cert signing issue, it would be better to move to Appveyor because they support UWP builds, but we need to get that one up and running.

**Comment by ei2kpi-ptc** [comment]
Hey, looks like I need to get Appveyor / Azure pipelines working for #406 as well. Happy to help here but need to know what the latest context is on this

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
