### ISSUE TITLE
model with inline base64 uri buffer load fail

### ISSUE THREAD

**Issue by tufeixp** [KhronosGroup/UnityGLTF#340]
#306 changelist @blgrossMS break the support of inline base64 uri buffer!
Now unable to load those kinda models, which is legal in spec.

NullReferenceException: Object reference not set to an instance of an object
UnityGLTF.GLTFSceneImporter.ConstructMeshAttributes (GLTF.Schema.MeshPrimitive primitive, System.Int32 meshID, System.Int32 primitiveIndex) (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:627)
UnityGLTF.GLTFSceneImporter.ConstructMeshAttributes (GLTF.Schema.GLTFMesh mesh, GLTF.Schema.MeshId meshId) (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:323)
UnityGLTF.GLTFSceneImporter.ConstructBufferData (GLTF.Schema.Node node) (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:272)
UnityGLTF.GLTFSceneImporter+<_LoadNode>d__51.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:435)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
UnityGLTF.GLTFSceneImporter+<ConstructScene>d__62.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:877)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
UnityGLTF.GLTFSceneImporter+<_LoadScene>d__53.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:483)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
UnityGLTF.GLTFSceneImporter+<LoadSceneAsync>d__40.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:181)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <ac823e2bb42b41bda67924a45a0173c3>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Tas

**Comment by tufeixp** [comment]
A sample file:
[creoBox.zip](https://github.com/KhronosGroup/UnityGLTF/files/2736172/creoBox.zip)

**Comment by blgrossMS** [comment]
The issue was actually that the index buffer didn't get its buffer initialized. See #342. Hopefully that fixes your issue! Thanks for the sample model.

**Comment by tufeixp** [comment]
Thanks, it fixed the problem.
