### ISSUE TITLE
Nodes only files should not contains buffers

### ISSUE THREAD

**Issue by ultrasuperpingu** [KhronosGroup/UnityGLTF#341]
When exporting a hierachy of empty objects, the "buffers" attribute should not be exported and no bin file should be created because, in specification, the byteLength of a buffer can not be zero.

(I saw the problem with a gltf validator but I guess no importer will complain about it. So, imho, it is a very small problem but it is still a bug so I opened this issue (please don't be mad at me ;) )

**Comment by blgrossMS** [comment]
Definitely a valid bug! We should fix it. If the GLTFSceneExporter wrapped the GLBBuilder I wrote in the GLTFSerialization dll it would address this issue.

**Comment by pfcDorn** [comment]
Fixed in latest release
