### ISSUE TITLE
Get thumbnail (preview image) before importing GLTF models?

### ISSUE THREAD

**Issue by yaqinh** [KhronosGroup/UnityGLTF#348]
Given the GLTF file path , is it possible to get a thumbnail image before importing GLTF files? If not possible now, is there any plan to put this feature in the future release? Any suggestion about how to do this? I might develop this feature and do PR if you could give me any suggestion or let me know if this is even possible or not. Thanks!

**Comment by blgrossMS** [comment]
Thumbnails are not part of the glTF standard. See https://github.com/KhronosGroup/glTF/issues/1167 . What I have done on a project is post-process a thumbnail for the object, put it in the file, and then find it via a custom extension. A similar method may work for you.

**Comment by yaqinh** [comment]
I see. Thanks!
