### ISSUE TITLE
Applying animation to skeleton in GLB file

### ISSUE THREAD

**Issue by ayagodinsc** [KhronosGroup/UnityGLTF#349]
Is there a way to apply an animation to a character loaded into scene using GLTFComponent? I was able to load a character into my scene using the GLTFComponent, how I can interact with the encapsulated data it it now?

**Comment by blgrossMS** [comment]
GLTFComponent can be modified to access the animation and play it. We do not play animations by default.

**Comment by ayagodinsc** [comment]
@blgrossMS, got it! Thanks. Could you give some high level clues of how it can be done? General algorithm. I am new with GLTF and any directions to research would be very helpful.

**Comment by stevenvergenz** [comment]
A Unity Animation component is placed on the scene root GameObject. You should be able to simply `GetComponent<Animation>().Play()`.

**Comment by ayagodinsc** [comment]
Yeah, I did not realize that GLTFComponent rebuilds content of GLB file into Unity scene. Now it is simple and clear. Thanks.
