### ISSUE TITLE
Provide UnityWebRequest Headers options and Post method

### ISSUE THREAD

**Issue by vsantosu** [KhronosGroup/UnityGLTF#35]
Hello there, 

First of all, thanks so much for this loader, it is a great contribution!

Can you provide a HTTP headers dictionary as argumento to the Loader object?

I need to provide authentication token to the Web Server:

`   

    var www = UnityWebRequest.Get(_gltfUrl);

     foreach(KeyValuePair<string, string> entry in headersDictionary)
     {
        www.SetRequestHeader(entry.Key,entry.Value);
     }
`

Also, can be there an option to use Post instead of Get?

`    var www = UnityWebRequest.Post(_gltfUrl, postData);
`

Thanks in advanced!

**Comment by mastayoda** [comment]
Fixed in Pull Request [37](https://github.com/AltspaceVR/UnityGLTF/pull/37)

**Comment by blgrossMS** [comment]
Closed #37 So we need to make sure to get the idea of these changes back in.

**Comment by ericob** [comment]
Not high priority due to ILoader interface extensibility (close this @blgrossMS)

Feel free to make a pull request
