### ISSUE TITLE
Proble on creating dll

### ISSUE THREAD

**Issue by fral8** [KhronosGroup/UnityGLTF#353]
Hello all,
starting from project: **GLTFSerialization.sln** 
Opening it in VS 2017
Compiling it.
The process produces this outputs:
```
1>------ Inizio ricompilazione: Progetto: GLTFSerialization, Configurazione: Debug Any CPU ------
1>GLTFSerialization -> C:\Users\frana\Desktop\final2final\UnityGLTF-master(2)\UnityGLTF-master\UnityGLTF\Assets\UnityGLTF\Plugins\uap10.0.10586\GLTFSerialization.dll
1>GLTFSerialization -> C:\Users\frana\Desktop\final2final\UnityGLTF-master(2)\UnityGLTF-master\UnityGLTF\Assets\UnityGLTF\Plugins\netstandard1.3\GLTFSerialization.dll
1>GLTFSerialization -> C:\Users\frana\Desktop\final2final\UnityGLTF-master(2)\UnityGLTF-master\UnityGLTF\Assets\UnityGLTF\Plugins\net35\GLTFSerialization.dll
========== Ricompilazione: 1 completate, 0 non riuscite, 0 ignorate ==========
```

How can I import dll into Unity project? I have 3 different diles in 3 different folders and I don't know which one I ve to use.
Thank You,
Francesco

**Comment by stevenvergenz** [comment]
That depends on the platform. If you're building your app as a UWP you'll want the `uap10.0.10586` version. Otherwise you'll most likely want `net35`.

**Comment by fral8** [comment]
Ok, So after building the 3 dlls as before, I opened on Unity the project _UnityGLTF_. I tried various examples, some work other do not.
I have Unity 2017.4.5f installed.
I'm very sad about it, and I've worked all todey trying to make it works. 

Trying to import only the dll net 35 in an empty project, it returns 

`Unable  to open Assets/GLTFSerialization.dll: Check external application preferences.`


If I mantain the UnityGLTF project and trying to load a glb model, Unity get stucked and I can only close it. 

In my project I have to download a project from Opensource BIMServer and load it in unity using the .glb format.
For the download part there are not big issues but at the current status I'm not able to use the repository properly. 

When compile the project in VS 2017 I obtain the following warning:
`Impossible to add a reference to project 'GLTFSerialization'.	GLTFSerializationUWPTests			 ` .

While loading _UnityGLTF _ project I obtain these warnings in the console:


`Assets/Resources/GLTFSceneTests.cs(40,24): warning CS0219: The variable filename is assigned but its value is never used


Assets/Resources/GLTFSceneTests.cs(63,22): warning CS4014: The statement is not awaited and execution of current method continues before the call is completed. Consider using await operator or calling Wait
 method


Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs(673,7): warning CS4014: The statement is not awaited and execution of current method continues before the call is completed. Consider using await operator


Assets/UnityGLTF/Scripts/Loader/WebRequestLoader.cs(40,33): warning CS0168: The variable e is declared but never used


Assets/Resources/GLTFSceneTests.cs(27,64): warning CS0414: The private field GLTFSceneTests.cameras is assigned but its value is never used


Assets/Resources/Manifest.cs(7,23): warning CS0649: Field AssetGenerator.Manifest.Folder is never assigned to, and will always have its default value null


Assets/Resources/Manifest.cs(19,27): warning CS0649: Field AssetGenerator.Manifest.Model.FileName is never assigned to, and will always have its default value null


Assets/Resources/Manifest.cs(22,27): warning CS0649: Field AssetGenerator.Manifest.Model.Camera is never assigned to, and will always have its default value null


Assets/UnityTestTools/IntegrationTestsFramework/TestRunner/Editor/PlatformRunner/PlatformRunner.cs(123,27): warning CS0618: UnityEditor.BuildTarget.StandaloneOSXIntel is obsolete: StandaloneOSXIntel has been removed in 2017.3


Assets/UnityTestTools/IntegrationTestsFramework/TestRunner/Editor/PlatformRunner/PlatformRunnerConfiguration.cs(47,21): warning CS0618: UnityEditor.BuildTarget.StandaloneOSXIntel is obsolete: StandaloneOSXIntel has been removed in 2017.3


Assets/UnityTestTools/IntegrationTestsFramework/TestRunner/Editor/PlatformRunner/PlatformRunnerConfiguration.cs(48,21): warning CS0618: UnityEditor.BuildTarget.StandaloneOSXIntel64 is obsolete: StandaloneOSXIntel64 has been removed in 2017.3'
`

I never work on unity and C#..... So I'm a noob..... 

Can someone please help me?
Thank you,
F
