### ISSUE TITLE
Hardlocked editor in latest version of Unity (2018.3)

### ISSUE THREAD

**Issue by sebastianwibergmicrosoft** [KhronosGroup/UnityGLTF#358]
Latest version of Unity, latest version of this plugin.
Importing any GLB-file (dropping it in Project-folder) causes Unity to hardlock.

Some info: 
Removed uap-plugin folder because it didn't compile properly.

**Comment by blgrossMS** [comment]
Thanks for letting us know. We'll try to take a look soon.

**Comment by sebastianwibergmicrosoft** [comment]
Did some investigation.
First off, it hardlockes even in Unity 2017.4.20f2 (LTS).
I stepped through the code and the problem occurs in the method 
private async Task _LoadNode(int nodeIndex) in GLTFSceneImporter.cs

When isMultithreading is set to always be false, the editor doesn't hardlock for me.

**Comment by ericob** [comment]
Would be great to create a PR which fixes this

**Comment by sebastianwibergmicrosoft** [comment]
Sure, I have a branch ready, but I don't seem to have premission to push a branch.

**Comment by kolodi** [comment]
> Sure, I have a branch ready, but I don't seem to have premission to push a branch.

You should be able to fork the repo and create a branch that will allow you to submit a PR (see https://guides.github.com/activities/forking/)

**Comment by sebastianwibergmicrosoft** [comment]
Good info, I did this. My PR got some weird warning/issue that isn't related to the work I have done. The code is there anyways.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
