### ISSUE TITLE
GLTF external assets URI needs to be enconded

### ISSUE THREAD

**Issue by vsantosu** [KhronosGroup/UnityGLTF#36]
Hello,

All GLTF Uri must be enconded otherwise it won't find the correct path in the webserver. 

For example: 
model.gltf
model.bin
textures/model's texture.jpeg

The loader will fail to find 'model's texture.jpeg'

The GLTFLoader.cs file must enconde al URIs:

For example:
`
image.Uri = WWW.EscapeURL (image.Uri);
`

**Comment by mastayoda** [comment]
Fixed in Pull Request [37](https://github.com/AltspaceVR/UnityGLTF/pull/37)
