### ISSUE TITLE
Shaders do not compile for WebGL

### ISSUE THREAD

**Issue by kolodi** [KhronosGroup/UnityGLTF#361]
On WebGL build I have following error:
`ShaderNotFoundException: GLTF/PbrMetallicRoughness not found. Did you forget to add it to the build?`
So I have included 2 shaders in the graphics settings
1. PbrMetallicRoughness
2. PbrSpecularGlossiness
Then I was waiting for like 3 hours for building, then I realize that it repeats "compiling shader variants" infinitely:
<img src="http://i64.tinypic.com/2qd3bdx.jpg">

_Originally posted by @kolodi in https://github.com/KhronosGroup/UnityGLTF/issues/357#issuecomment-463976395_

**Comment by edumlauer** [comment]
I believe you would need one or the other, preferably PbrMetallicRoughness. It still takes some time to compile all the variants, but you will only need to endure this process once.

**Comment by kolodi** [comment]
Yes, I finally finished the first build. It took approximately 3 hours on my machine.

**Comment by FreakTheMighty** [comment]
Does anyone know what the artifacts of that build process are? Is that something that can be published and shared somehow?

**Comment by flecoq** [comment]
Hello,
I'm trying to compile for WebGL to.  So i've included GLTF/PbrMetallicRoughness in the Graphic Setting.
Unfortunatly, i get this compiling error:
GLTF/PbrMetallicRoughness has too many Shader variants(1359872).To resolve this, go to Project Settings > Graphics and remove this Shader from the Always Included Shaders list.For more explicit control over how Unity includes specific Shader variants in a build, use a ShaderVariantCollection.

Thk u for your help :)

**Comment by miketalbott** [comment]
@flecoq I was facing the same issue as you. I don't have a clean fix but I did figure out a workaround: Instead of including the shader in the the graphics include list, I just added a cube to my scene using a material set to the "GLTF/PbrMetallicRoughness" shader and I disabled the cube. This seems to include the shader without all the variants.
