### ISSUE TITLE
Do not create GameObjects for mesh primitives

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/UnityGLTF#370]
Instead, represent multiple mesh primitives as Unity submeshes. So instead of the post-load scene graph being like this:

* gltf_node => GameObject
    * gltf_mesh => GameObject
        * gltf_primitive => GameObject
            * mesh_data + gltf_material => Renderer
        * gltf_primitive => GameObject
            * mesh_data + gltf_material => Renderer

...it would look like this:

* gltf_node => GameObject
    * gltf_mesh_primitive[] + gltf_material[] => Renderer

See the documentation for [Mesh.SetTriangles](https://docs.unity3d.com/ScriptReference/Mesh.SetTriangles.html) for the backing structure.

**Comment by luizcarlosfx** [comment]
I agree, it should be an option to import them as a single mesh

**Comment by KermMartian** [comment]
I suspect this would have a significant positive effect on scene weight for us.
