### ISSUE TITLE
Cancellation not supported.

### ISSUE THREAD

**Issue by sanjeev3094** [KhronosGroup/UnityGLTF#373]
Loading a scene cannot be canceled. 
**Usecase**: Suppose I load a scene and then want to cancel the load operation(due to some requirement) then it cannot be done as cancellation tokens are not accepted as a parameter.
It would be great if there can be a support for cancellation.

**Comment by tufeixp** [comment]
I have added a token for exit, but I'm not sure if I can upload it.

**Comment by MephestoKhaan** [comment]
Not sure if that token is working for me? Used LoadAsync as a coroutine and set the token, and even tho the load was interrupted the memory did not go down.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
