### ISSUE TITLE
Unity crash importing big gltf in inspector

### ISSUE THREAD

**Issue by phanemy** [KhronosGroup/UnityGLTF#374]
I'm trying to import a big glb (65,5 Mo) file in unity using UnityGLTF 1.0, but at the end of the import unity crash and force me to force quit. when i restart i saw all asset are created (texture, material and mesh) but if i drag and drop the prefab in scene, material are missing and i cant add them manualy.

**Comment by blgrossMS** [comment]
What do you mean by UnityGLTF 1.0. The release in the releases folder? Does the issue repro on latest?

**Comment by phanemy** [comment]
Yes, i mean the release, but I hove take a look on more recent version but the GLTFImporter is the same and use the last version don’t change anything.

I have found and fixed my problem, at the end it isn't a crash just a huge amount of time to load.
This come from GLTFImporter.cs in editor, when you are fixing reference between texture and material, in your script you are creating a new Application.delayCall() for each material and in these delayCall you are, for all texture, looping on all material to know if the texture is for this material. And in my case i have 125 texture and 125 material so the looping part are take a huge amount of time and to this one we have to had the time for calling the 125 delayed Call.

I fixe this by calling after the material copy loop the delayCall to made all process in one call after textureImporter are kick off, and in this one instead of looping on all material for all texture i use a map beetween old material and new one to directly get the one we need from the texMaterialMap. It is still long to import but the huge DelayCall is made only one time instead of 125 so he doesn’t take 1 day to finish ^^

**Comment by phanemy** [comment]
I would like to apoligize, after retrying both versions (released 1.0 and actual master branche), i thinks I got lost in the versions, the last versions work fine. Sorry for inconvenience

**Comment by phanemy** [comment]
I have find another fix, you use SaveAndReimport the TextureImporter of each texture even if you don't modify importer's settings, i think it's not mandatory (maybe i'm wrong) and sould be done only when importer settings are change (normal or sprite texture)

**Comment by azakariaMSFT** [comment]
Can you share the asset you are trying to load? There are a number of performance enhancements in the master branch and it would be good to confirm if it resolves this

**Comment by phanemy** [comment]
Here is one of my file https://we.tl/t-Du4U6LOici.
I have try again master-branch version, it works again for small files, but for big one i still have endless delay.

**Comment by azakariaMSFT** [comment]
I tried to load the asset an runtime and it takes less than 5 seconds to load 
When importing in editor. I see that the editor is stuck in an infinite loop trying to regenerate hashes for the new files long after the files are created. It seems to be an issue with unity. the file system metafile doesn't appear to be touched while this is happening
...
Hashing assets (1 files)... The thread 0xd478 has exited with code 0 (0x0).
0.005 seconds
  file read: 0.001 seconds (1.338 MB)
  wait for write: 0.000 seconds (I/O thread blocked by consumer, aka CPU bound)
  wait for read: 0.000 seconds (CPUT thread waiting for I/O thread, aka disk bound)
  hash: 0.003 seconds
Updating Assets/UnityGLTF/import/Textures/0000 (Clone) (32).png - GUID: 34333e6c387d5984f91b29a1ff989be0...
 done. [Time: 371.866700 ms] 
Script Compilation Pipeline Post Process Assets time: 0.000021s
Assembly Updater Post Process Assets time: 0.000268s
Refreshing native plugins compatible for Editor in 1.96 ms, found 3 plugins.
Preloading 1 native plugins for Editor in 0.32 ms.

Hashing assets (1 files)... The thread 0xdf90 has exited with code 0 (0x0).
0.009 seconds
  file read: 0.002 seconds (3.259 MB)
  wait for write: 0.000 seconds (I/O thread blocked by consumer, aka CPU bound)
  wait for read: 0.001 seconds (CPUT thread waiting for I/O thread, aka disk bound)
  hash: 0.006 seconds
Updating Assets/UnityGLTF/import/Textures/0000 (Clone) (33).png - GUID: 65230e41086a011479a8875c8c265e49...
 done. [Time: 707.955900 ms] 
Script Compilation Pipeline Post Process Assets time: 0.000019s
Assembly Updater Post Process Assets time: 0.000231s
Refreshing native plugins compatible for Editor in 1.06 ms, found 3 plugins.
Preloading 1 native plugins for Editor in 0.20 ms.
...

**Comment by pfcDorn** [comment]
Fixed in latest release
