### ISSUE TITLE
Export to GLTF 1.0

### ISSUE THREAD

**Issue by Jennilein1991** [KhronosGroup/UnityGLTF#377]
Hei !
I recently have the problem that i can not load gltf 2.0 files in an android application.
So my question is : Does UnityGLTF also provide a mechanism to export to the gltf 1.0 format?

Thanks!

**Comment by blgrossMS** [comment]
We do not support the glTF 1.0 format. What issues are you seeing regarding gltF 2.0 on android?

**Comment by Jennilein1991** [comment]
I'm using TriLib (https://assetstore.unity.com/packages/tools/modeling/trilib-model-loader-package-91777) to load models in runtime into a unity application. TrilIib uses functions from Assimp (http://www.assimp.org/) to load these models. 
When i load a gltf 2.0 model with TriLib, the app crashes and i get the following error code: 
![image](https://user-images.githubusercontent.com/12052402/54549639-c6cb7000-49aa-11e9-8898-cd27033a40fe.png).

I think it is an error in the trilib or assimp library so i posted already in these forums.
Would be nice if i can export into gltf 1.0, so i can just load some gltf models.

**Comment by blgrossMS** [comment]
glTF 1.0 is quite divergent so it is not on the roadmap to support. I would recommend using UnityGLTF to load glTF/GLB over assimp. I believe the perf will be better as well.

If you are still having issues with this, it would be great if you could share your asset if comfortable, and we can try debugging it further

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
