### ISSUE TITLE
TlsException when loading GLTF From https URI

### ISSUE THREAD

**Issue by spacecheeserocks** [KhronosGroup/UnityGLTF#380]
Loading a GLTF file from a HTTPS URL fails with `TlsException: The authentication or decryption has failed.`

It looks like someone has already attempted to fix this issue by adding a Certificate Validation Callback at [WebRequestLoader.cs:82](https://github.com/KhronosGroup/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/Scripts/Loader/WebRequestLoader.cs#L82) in commit 52d1e09723c68aab9e06a6e13d748b9fa346bde3

But this validation callback is not actually ever invoked.

Some online research seems to suggest that the Mono implementation of HttpClient does not support TLS 1.2, which could be the cause of this issue. https://stackoverflow.com/a/47664746

Tested in Unity 2017.4.23f1 - i would assume that 5.6 would also have this issue.

Some previous version of the WebRequestLoader class used UnityWebRequest and worked fine.

**Reproduction Steps**
* Create a UnityGLTF Component, setting the GLTFUri to a gltf file on a HTTPS Server using TLS 1.2
* Observe the "Loading failed, retrying" warnings until the TlsException is thrown.

**Comment by spacecheeserocks** [comment]
My proof that the Certificate Validation Callback is not actually used is probably not flawless, but I used the following steps:
* Breakpoint [WebRequestLoader.cs:30](https://github.com/KhronosGroup/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/Scripts/Loader/WebRequestLoader.cs#L30) to ensure the callback is being assigned
* Breakpoint [WebRequestLoader.cs:83](https://github.com/KhronosGroup/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/Scripts/Loader/WebRequestLoader.cs#L83) to check if the callback is ever invoked (breakpoint is never hit)
* Added the following lines into the callback (the error is not fired, the player does not pause)
```cs
            UnityEngine.Debug.LogError("Running Cert Validation Callback...");
            UnityEngine.Debug.Break();
```

**Comment by lostintriangulation** [comment]
Can we get some focus on this? This is a real problem for us as well!

**Comment by AdamMitchell-ms** [comment]
Thanks for reporting this issue.  We're happy to accept contributions to fix this issue.  If you have a fix, please send us a PR and we'll review it quickly.

**Comment by spacecheeserocks** [comment]
Just a little update for anyone stumbling across this issue. I don't know which unity version that this changed exactly, but I recently tested this behaviour in 2018.4 and this issue no longer seems to be the case. 

Basically, if you're targeting 2018.4 or higher, it seems safe to use HttpClient. If you're targeting lower, you should test if HttpClient works with HTTPS first. 

If you still need old unity code, it should be reasonable to replace the HttpClient code with UnityWebRequest, which does support HTTPS.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
