### ISSUE TITLE
UPM (Unity Package Manager) compliant package

### ISSUE THREAD

**Issue by ei2kpi-ptc** [KhronosGroup/UnityGLTF#384]
It would be nice to have UPM compliant packages created as part of releases in addition to .unitypackage.
This will be useful for people to use UnityGLTF packages from local disk for now and eventually when Unity supports external packages in their store.

Already have a pull request ready for this.

**Comment by ei2kpi-ptc** [comment]
@blgrossMS thanks for accepting the Pull request. 
Do you think we could trigger another official release so that the UPM-compliant package is generated and uploaded into the releases page?

**Comment by blgrossMS** [comment]
I've tagged it which should trigger a package being created it. See release: https://github.com/KhronosGroup/UnityGLTF/releases/tag/v1.0.1

**Comment by ei2kpi-ptc** [comment]
Thanks!

**Comment by kolodi** [comment]
Please note somewhere that the script should be launched from the root folder in order for $(pwd) to be resolved correctly.
