### ISSUE TITLE
ILoader.LoadedStream is Confusing

### ISSUE THREAD

**Issue by rferrese** [KhronosGroup/UnityGLTF#389]
In the ILoader interface, the LoadedStream variable gets replaced with the last Stream.  This behavior is confusing based on the variable names.

A possible solution to this would be:
- Change `Task LoadStream(...)` to `Task<Stream> LoadStream(...)`
- Rename `Stream LoadedStream` to `Stream LastSyncLoadedStream`
- Dont populate the new LastSyncLoadedStream variable from LoadStream

**Comment by mhochk** [comment]
Resolved with #532
