### ISSUE TITLE
Move GLTFComponent into Example Code

### ISSUE THREAD

**Issue by rferrese** [KhronosGroup/UnityGLTF#390]
The GLTFComponent script is set up as sample code, and should be moved into the Example code folder as a template for developers to build on in their individual projects.  In this move, the namespace should also be updated.

if GLTFComponent is expected to be used in production, the architecture should be changed to make it more extensible to allow it to be useful without modification.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
