### ISSUE TITLE
Add more options for the importer

### ISSUE THREAD

**Issue by luizcarlosfx** [KhronosGroup/UnityGLTF#391]
The importer could have toggles to choose how to import some features:
- Bones
- Animations
- Combine primitives
- Materials
- Textures

In my case I don't want to import animations, nor bones. I added those options myself, but it's not that good since I want to receive your future updates without trouble. Also, your `GLTFSceneImporter` could be splited by module like (MaterialImporter, MeshImporter, HierarchyImporter, TextureImporter, AnimationImporter) that way it would be easier to maintain the code, the class now has 2000+ lines of code.

Thanks for the good work, you're doing an amazing job!

**Comment by sonygod** [comment]
good suggestion +1

**Comment by blgrossMS** [comment]
Thank you for the suggestion! We have a proposed architecture #259 that does show how we want to split the classes up easier. We may have some time coming up to implement it!

**Comment by pfcDorn** [comment]
Please update to the latest version. When you still missing some options, please open a new issue. Thanks!
