### ISSUE TITLE
Support for texture tiling

### ISSUE THREAD

**Issue by clstavros** [KhronosGroup/UnityGLTF#396]
When exporting to glb we are finding that if a tiling value is set in Unity for the texture it is not honored at render time.  Based on our tests it looks like that is not supported, can anyone confirm, please?  Is it a limitation of the gilt format or the exporter?

If not I would like to vote for that enhancement.

Thank you.

**Comment by blgrossMS** [comment]
@stevenvergenz  who may know more about this

**Comment by pfcDorn** [comment]
Fixed in latest release

**Comment by clstavros** [comment]
wow, you guys rock I forgot about this, thank you! cheers.
