### ISSUE TITLE
Textures Now Defaulting to Aliased

### ISSUE THREAD

**Issue by KermMartian** [KhronosGroup/UnityGLTF#403]
Previous versions of the UnityGLTF plugin defaulted to antialiasing textures embedded in GLTF models; now, no antialiasing appears to be applied (c.f., for example, these building roofs):

![image](https://user-images.githubusercontent.com/1566659/55970785-381add80-5c4e-11e9-8f1f-775bad7b268a.png)

Is there a flag somewhere to control this, and/or a suggested shader to use to remedy this?

**Comment by blgrossMS** [comment]
We did recently update our samplers to better follow the standard guidelines. Is this different behavior than you see in other viewers?

**Comment by KermMartian** [comment]
Yes, my experience is that most viewers will antialias textures, but if there's another way I can achieve this if you're planning to stick with the un-antialiased texturing (including changing the shaders that I'm using), I'm happy to go that route instead.

**Comment by blgrossMS** [comment]
Can we get an example of your model so we can investigate these issues further?

**Comment by AdamMitchell-ms** [comment]
This was fixed by #421
