### ISSUE TITLE
Texture memory leak

### ISSUE THREAD

**Issue by rferrese** [KhronosGroup/UnityGLTF#410]
There is a texture memory leak in the GLTF Scene Importer where textures are not cleaned up properly between AssetCache and RefCountedCacheData.

It may be worthwhile to refactor the texture reference handling code to reduce the edge cases and prevent future memory leaks.

**Comment by rferrese** [comment]
This is partly addressed by PR #409 and fixes all the memory leaks I have found, but we should still consider better handling of texture references.

**Comment by MephestoKhaan** [comment]
The fix certainly help but I am still leaking a few textures and I really can't find where is this happening. I am forcing to dispose the cache and then destroying the LastLoadedScene is there anything I am missing?

I am loading big models (~2GB in memory) and I am leaking around 500 MB everytime

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
