### ISSUE TITLE
Loading animation issue

### ISSUE THREAD

**Issue by PedroBGDev** [KhronosGroup/UnityGLTF#411]
Hi,
I'm trying to load some glTF files with animations with the latest UnityGLTF version and I always get errors when try to load it. I used an glTF viewer to see if there is any problem with the animation schema, but it works, so I think that is an bug at the importer.

The error that Unity shows is this, and there seems to be something uninitialized:
`NullReferenceException: Object reference not set to an instance of an object
UnityGLTF.GLTFSceneImporter.BuildAnimationSamplers (GLTF.Schema.GLTFAnimation animation, System.Int32 animationId) (at Assets/GLTF/UnityGLTF/Scripts/GLTFSceneImporter.cs:792)
UnityGLTF.GLTFSceneImporter.ConstructClip (UnityEngine.Transform root, UnityEngine.GameObject[] nodes, System.Int32 animationId) (at Assets/GLTF/UnityGLTF/Scripts/GLTFSceneImporter.cs:885)
UnityGLTF.GLTFSceneImporter+<ConstructScene>d__66.MoveNext () (at Assets/GLTF/UnityGLTF/Scripts/GLTFSceneImporter.cs:1063)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
UnityGLTF.GLTFSceneImporter+<_LoadScene>d__55.MoveNext () (at Assets/GLTF/UnityGLTF/Scripts/GLTFSceneImporter.cs:555)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
UnityGLTF.GLTFSceneImporter+<LoadSceneAsync>d__43.MoveNext () (at Assets/GLTF/UnityGLTF/Scripts/GLTFSceneImporter.cs:229)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
UnityGLTF.GLTFComponent+<Load>d__16.MoveNext () (at Assets/GLTF/UnityGLTF/Scripts/GLTFComponent.cs:127)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
UnityGLTF.GLTFComponent+<Start>d__15.MoveNext () (at Assets/GLTF/UnityGLTF/Scripts/GLTFComponent.cs:50)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:112)
UnityEngine.UnitySynchronizationContext.Exec () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:73)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:94)`

The page that i use to view the glTF model is this, where I can see it:
https://gltf-viewer.donmccurdy.com/

This is the file with the animation:
[SimpleAnimation.zip](https://github.com/KhronosGroup/UnityGLTF/files/3088284/SimpleAnimation.zip)

**Comment by AdamMitchell-ms** [comment]
Hi @PedroBGDev,

Thanks for filing this issue.  It looks like a buffer isn't being created before it's used.  I'll look into this further tomorrow or Friday.

Adam

**Comment by yaakovyitzchak** [comment]
Hi im also having a  similar problem can you let me know if there is an easy way to fix this for skinned meshes?

**Comment by AdamMitchell-ms** [comment]
Hi,

I know that some skinned meshes do animate properly.  For example this sample model: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Monster.

I'm not sure what causes the above linked SimpleAnimation.zip to fail while others succeed.  I haven't gotten time to look into it but I expect to have some time in the next week or two.

@yaakovyitzchak , can you attach another example of a file that is failing?  Having more examples will help me determine the root cause of the issue.

**Comment by yaakovyitzchak** [comment]
@AdamMitchell-ms  hi see this issue here:
https://github.com/KhronosGroup/UnityGLTF/issues/428
I tried to fix it basically by just searching _assetCache.NodeCache for a non-null type and replacing it with that, if _assetCache.NodeCache[skin.Skeleton.Id] is null, which it usually is for some reason.

The models that didn't work were just a basic mesh (even default cube) in blender (2.8), that is simply parented to a single armature with "automatic weights" -- try it and see if you get the same error

**Comment by AdamMitchell-ms** [comment]
@PedroBGDev and @yaakovyitzchak ,

I have a proposed fix in my branch.
https://github.com/KhronosGroup/UnityGLTF/tree/u/adam/animation-crash

Can you pull that and confirm that it fixes it for you?  It's an API-breaking change, so I need to determine if I should put it into master or create a v-next branch to start accumulating these changes and others.

**Comment by yaakovyitzchak** [comment]
@AdamMitchell-ms  hey I just tried your new code but I still can't load https://drive.google.com/open?id=1fRrXIrQ_JH_VpdjGwNqiEY-LqvHJhpRH

I get this error:

> 
> NullReferenceException: Object reference not set to an instance of an object
> UnityGLTF.GLTFSceneImporter+<SetupBones>d__76.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:1349)
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> UnityGLTF.GLTFSceneImporter+<ConstructMesh>d__79.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:1427)
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> UnityGLTF.GLTFSceneImporter+<ConstructNode>d__71.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:1215)
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> UnityGLTF.GLTFSceneImporter+<ConstructNode>d__71.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:1233)
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> UnityGLTF.GLTFSceneImporter+<_LoadNode>d__56.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:578)
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> UnityGLTF.GLTFSceneImporter+<ConstructScene>d__70.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:1163)
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> UnityGLTF.GLTFSceneImporter+<_LoadScene>d__57.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:606)
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> UnityGLTF.GLTFSceneImporter+<LoadSceneAsync>d__45.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs:267)
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> UnityGLTF.GLTFComponent+<Load>d__20.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFComponent.cs:129)
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.TaskAwaiter.GetResult () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> UnityGLTF.GLTFComponent+<Start>d__19.MoveNext () (at Assets/UnityGLTF/Scripts/GLTFComponent.cs:51)
> --- End of stack trace from previous location where exception was thrown ---
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <23c160f925be47d7a4fd083a3a62c920>:0)
> System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <23c160f925be47d7a4fd083a3a62c920>:0)
> UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:115)
> UnityEngine.UnitySynchronizationContext:ExecuteTasks()
> 
>

**Comment by AdamMitchell-ms** [comment]
Ok @yaakovyitzchak,

I've pushed more changes to my branch.  I'm able to load your model with my latest changes.  But it doesn't seem that your model actually animates in UnityGLTF or any other viewer I tried (babylon.js and Windows 3D Viewer).

Adam

**Comment by yaakovyitzchak** [comment]
@AdamMitchell-ms  Ah very nice! I simply pasted in your new code, and on the exact same unity instance that showed the error before, I simply re-played the scene and the model loaded perfectly! 
And yes I believe the animation problems were a second issue.

So far it looks like it all works -- but I'll let you know if there are any other errors

**Comment by AdamMitchell-ms** [comment]
Ok, great.  I have pull #429 to address this issue in master.
