### ISSUE TITLE
UnityGLTF v1.0.1 release does not contain Resources folder

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/UnityGLTF#416]
... and thus exporting doesn't work at all (conversion shaders missing etc.). I guess that's just an oversight when creating the package?

**Comment by andreasplesch** [comment]
see #393

**Comment by soraryu** [comment]
I recommend changing the title of #393 to reflect the issue. With that title it's no wonder I didn't find it when searching :)

**Comment by andreasplesch** [comment]
Well, the cross-references now may suffice.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
