### ISSUE TITLE
SaveGLB doesn't embed images

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/UnityGLTF#418]
When running these two lines right after another
```
// save gltf + bin
exporter.SaveGLTFandBin(Path.Combine(wwwPath, sceneName), sceneName);
// save glb file directly
exporter.SaveGLB(Path.Combine(wwwPath, sceneName), sceneName);
```
I get very different output. Save gltf+bin produces gltf,bin and images with a total size of ~3MB; save glb stores, well, a single GLB file (as expected) which is only 30KB and doesn't work in any viewer.

**Expected:** I would expect the output of SaveGLB to be identical to what an external GLB packer produces when putting the files in, e.g. https://glb-packer.glitch.me/

Is there anything I need to configure to even get images to be stored inside the GLB?
(tested with both the latest release version and the latest master)

**Comment by andreasplesch** [comment]
Could be due to #393 if you see the shader value null message in the console.

**Comment by soraryu** [comment]
No, I already added the Resources folder manually. There's no error message logged at all, the export runs through without errors - just a tiny glb is exported.

**Comment by soraryu** [comment]
Upon some further investigation I'd say this is a bug:
calling
```
// save gltf + bin
exporter.SaveGLTFandBin(Path.Combine(wwwPath, sceneName), sceneName);
// save glb file directly
exporter.SaveGLB(Path.Combine(wwwPath, sceneName), sceneName);
```
results in a tiny GLB (and no error message),
while ONLY calling
`exporter.SaveGLB(Path.Combine(wwwPath, sceneName), sceneName);
`(and not exporting the GLTF before) results in a proper GLB file.

**Comment by andreasplesch** [comment]
Ok. It sounds like something which could be narrowed down by stepping through with the debugger.

**Comment by AdamMitchell-ms** [comment]
@soraryu or @andreasplesch , do either of you have time to investigate and possibly send a pull request with a fix?

**Comment by andreasplesch** [comment]
Sorry, not currently.
