### ISSUE TITLE
Loading multiple gtb file in a scene on iOS feels up the memory.

### ISSUE THREAD

**Issue by AzadNezamdoust** [KhronosGroup/UnityGLTF#425]
Loading multiple gtb file in a scene on iOS feels up the memory and app crashed.
I used same contents with unity bundles but never had memory issue.
Please help ASAP my new app release is dependant on it. 
Thanks.

**Comment by azakariaMSFT** [comment]
Hi,
You should check out the unity memory profiler to understand what is the memory usage of your app and assets before and after your changes. Could you describe what the app does with the content and why you needed to switch from bundles?
https://docs.unity3d.com/Manual/ProfilerMemory.html
Feel free to share the glbs that you are having trouble with so we can see how we can help

Thanks
Ahmed

**Comment by AdamMitchell-ms** [comment]
Unity asset bundles are saved in a way that allows Unity to stream in mips and stay within the app's memory budget.  By default, glb/gltf does not contain these lower resolution images.

However, UnityGLTF does support the [MSFT_lod](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/MSFT_lod) extension to support different levels of detail.  If you author files with this extension, then I think they will load more like you are expecting.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
