### ISSUE TITLE
GLTFComponent path.combine fails runtime import from network share

### ISSUE THREAD

**Issue by fagerbur** [KhronosGroup/UnityGLTF#430]
When you import at run-time from a network share the below code meant to fix path.combine trims the starting \\\\ and causes invalid paths.

example:
"\\\\server\share\file" becomes "server\share\file"

GLTFComponent.cs Line 79
```
// Path.Combine treats paths that start with the separator character
// as absolute paths, ignoring the first path passed in. This removes
// that character to properly handle a filename written with it.
GLTFUri = GLTFUri.TrimStart(new[] { Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar });
```

I can't seem to think of how to accommodate both cases off the top of my head but I'll come back to this and make a pull request if I come up with something good enough

**Comment by AdamMitchell-ms** [comment]
@fagerbur , if you come up with a fix that handles network file shares and doesn't break any existing loading paths, then please do send a pull request and we'll get it in.

**Comment by fagerbur** [comment]
@AdamMitchell-ms  what about moving the trim into the Path.Combine? The combine is only needed when AppendStreamingAssets is true so i think moving it inside the if statement would fix the issue without breaking anything else. I made a pull request but if you can think of a case where it doesn't work feel free to reject it. #431 
```
string fullPath;
if (AppendStreamingAssets)
{
   fullPath = Path.Combine(Application.streamingAssetsPath, GLTFUri.TrimStart(new[] { Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar }));

```
