### ISSUE TITLE
Out Of Memory Handling

### ISSUE THREAD

**Issue by rferrese** [KhronosGroup/UnityGLTF#432]
On iOS (though possibly on other platforms) out of memory exceptions caused by Texture2D.LoadImage cause the app to crash.  This is because the exception happens on gfx thread, and isn't caught by a try/catch around LoadImage(...)  Ideally, running out of memory would cause the load to fail, discard all loaded data, and continue app execution normally.

**Comment by AdamMitchell-ms** [comment]
Fixed
