### ISSUE TITLE
Unity WebGL build not building at all 153 erros

### ISSUE THREAD

**Issue by yaakovyitzchak** [KhronosGroup/UnityGLTF#436]
Hi,
I tried building the latest release of GLTF importer (just dragged in the ZIP to the assets folder / imported package also), and it works fine in the editor (2019.2.a), but when I do webGL build I get about 153 errors all saying basically that "GLTFComponent"... or whatever is not recognized.

It works fine in windows standalone.

I heard somewhere that there are two binaries - one for UWP and one for all others, but I couldn't find the UWP one ? Is this some kind of bug?

**Comment by AdamMitchell-ms** [comment]
Did you clone the repository?  If so, then check out README.md.  You'll need to build /GLTFSerialization/GLTFSerialization.sln.  Then open the Unity project at /UnityGLTF and it should succeed.

**Comment by mkorpinen** [comment]
The problem is that some of the files don't have WebGL toggled on. After you toggle them the build succeeds, but it raises a new issue with some dll not being supported.

![image](https://user-images.githubusercontent.com/51988559/60095037-532dc180-9756-11e9-8e1c-5b6250b83cea.png)

**Comment by Lakuman** [comment]
I have this error too when i use Unity Package do you found the solution ?

**Comment by jmo7** [comment]
I am also seeing this every time (WebGL is dead in the water because of it).  
What's the current status on this? (Is there a known workaround)?

**Comment by jmo7** [comment]
Does anybody have any further insights on this? Although my c# and unity skills are only a  bit above basic I'm willing to work on this if anybody has any further info that could help me get started.

**Comment by antont** [comment]
@jmo7 - did you get this working?

I've worked with Unity C# and WebGL pretty much full time for several years now, can maybe help.

**Comment by Schaubli** [comment]
To solve the dlopen / emscripten / linking error in the WebGL Build, try @kolodi's pull request #367. That solved it for me.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
