### ISSUE TITLE
only Unity plugIn import in new empty project brings at all 153 errors

### ISSUE THREAD

**Issue by julia1981** [KhronosGroup/UnityGLTF#439]
Hello and thanks for your plugIn!

hope i can use it soon as possible. 

I use Unity 2019.1.3f1 and get these errors:

![image](https://user-images.githubusercontent.com/6509238/58767924-a9ae4280-8592-11e9-88a5-4af00b7a5307.png)

Can you please help me out?

Thanks in Advance

**Comment by julia1981** [comment]
using unity 2019.1.3f1

**Comment by starterboost** [comment]
I'm having the same problem. This issue states that the dlls need to be built:

https://github.com/KhronosGroup/UnityGLTF/issues/236

> The project GLTFSerialization/GLTFSerialization.sln needs built to generate the dll's. Please refer to the instructions in the Readme.md.

I don't see any mention of generating the dlls in the Readme but I'm now trying to install Visual Studio so that I can give this a go.

**Comment by starterboost** [comment]
Building GLTFSerialization/GLTFSerialization.sln fixed all the errors.

**Comment by dblatner** [comment]
How can the DLL be build on macOS? I think I can not open the SLN without Visual Studio

**Comment by AdamMitchell-ms** [comment]
Hi @dblatner ,
I don't have a mac device, but does this work for you?
https://visualstudio.microsoft.com/vs/mac/

**Comment by AdamMitchell-ms** [comment]
@julia1981,
See comments from @starterboost.  Closing this issue now.
