### ISSUE TITLE
How to import gltf file from local folder in Runtime?

### ISSUE THREAD

**Issue by SkyWalker2506** [KhronosGroup/UnityGLTF#447]
Hi. I have tried to find a way to import gltf in runtime from local folder but I can't find how to do it. I tried it on mac and I used the AnimatedCube scene.  It is giving Error as: 
InvalidOperationException: The request URI must either be an absolute URI or BaseAddress must be set.

![Screen Shot 2019-06-11 at 17 54 28](https://user-images.githubusercontent.com/42008533/59282734-0e902980-8c72-11e9-9730-b785c8ad0947.png)

Is there any tutorial or documentation that show how to import gltf in runtime from local folder ?

**Comment by fagerbur** [comment]
Have you tried checking the box for 'Use Stream' ?

I have a script that does a lot of run-time loading, here is a sample of it below

```
GameObject ActiveObject = new GameObject();

GLTFComponent gltfcomponent = ActiveObject.AddComponent<GLTFComponent>();
gltfcomponent.Multithreaded = true;
gltfcomponent.UseStream = true;
gltfcomponent.AppendStreamingAssets = false;
gltfcomponent.GLTFUri = {your path here};
gltfcomponent.name = {your object name here};
```

Also, I would pull from the master branch as the latest release is out of date.

**Comment by SkyWalker2506** [comment]
> Have you tried checking the box for 'Use Stream' ?
> 
> I have a script that does a lot of run-time loading, here is a sample of it below
> 
> ```
> GameObject ActiveObject = new GameObject();
> 
> GLTFComponent gltfcomponent = ActiveObject.AddComponent<GLTFComponent>();
> gltfcomponent.Multithreaded = true;
> gltfcomponent.UseStream = true;
> gltfcomponent.AppendStreamingAssets = false;
> gltfcomponent.GLTFUri = {your path here};
> gltfcomponent.name = {your object name here};
> ```
> 
> Also, I would pull from the master branch as the latest release is out of date.

Thanks. It worked. I was using UniGltf but It was using too much memory so I decided to try this one. However results are much worse. After loading about 100 to 200 mb model for the UniGltf, It crashes. I haven't tried the limit of this one since it already spent few times more memory.

**Comment by AdamMitchell-ms** [comment]
It sounds like the original issue is resolved.
