### ISSUE TITLE
bad cleanup after importing glb

### ISSUE THREAD

**Issue by phanemy** [KhronosGroup/UnityGLTF#449]
I have update my version of UnityGltf (my previous version date from some month) and now when importing glb in editor and now some asset are still in memory at the end of the import, to have the same memory footprint as before i need to use Resources.UnloadUnusedAssets(); at the end of gltfImport.OnImportAsset

**Comment by Dryra** [comment]
We also ran into this issue in runtime. Is this fixed ?

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
