### ISSUE TITLE
WebGL not working

### ISSUE THREAD

**Issue by mkorpinen** [KhronosGroup/UnityGLTF#457]
Problem is with some files are not included in the WebGL build and once you enable them build succeeds, but the browser throws the following window.
![image](https://user-images.githubusercontent.com/51988559/60095091-76587100-9756-11e9-810d-6ace67ed76b5.png)

**Comment by mkorpinen** [comment]
Its related to fixing namespace issues with enabling the dll files to the build.
https://github.com/KhronosGroup/UnityGLTF/issues/436

**Comment by jmo7** [comment]
mkorpinen, do you know any more information about how the namespaces need to be fixed? (I read issue #436 but didn't find any specifics about namespacing issues).

**Comment by jmo7** [comment]
Does anybody have any ideas about what might be going on. My c# and unity levels are just a little bit above basic but I'm willing to tackle this if anyone has any pointers.

**Comment by Schaubli** [comment]
To solve the dlopen / emscripten / linking error in the WebGL Build, try  @kolodi's pull request #367. That solved it for me.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
