### ISSUE TITLE
Shader variants

### ISSUE THREAD

**Issue by antoninklopp** [KhronosGroup/UnityGLTF#459]
Hi, 

I am currently using UnityGLTF for Android and Oculus. 
To be able to build, I need to include the shader : GLTF/PbrMetallicRoughness into the graphics settings, but the apk is 40 Mo heavier when including the shader in the build. 

Therefore I have two questions : 
- Do I need to include the PbrSpecularGlosiness into the build? 
- Unity seems to compile a lot of shader variants. Did anyone do this kind of build before and knows which platforms to target? 

Thank you very much for your help

**Comment by murphysurveys** [comment]
(A) It is my understanding that metallic-roughness and specular-glossiness are alternative "material models" or workflows for creating physically-based renders. Therefore only one should be needed and I think it was mentioned that PbrMetallicRoughness is preferred.

(B) I have targeted Android and whilst doing so, added the PbrMetallicRoughness to the included shader list, then saved the list to an asset, added this shader asset in the graphics settings, and finally removed the PbrMettalicRoughness from the list. It seems that the asset is of generated shader variants which improved build times.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
