### ISSUE TITLE
Updated shader for Vertex Color support

### ISSUE THREAD

**Issue by handyjellyfish** [KhronosGroup/UnityGLTF#468]
[UnityGLTF.zip](https://github.com/KhronosGroup/UnityGLTF/files/3400814/UnityGLTF.zip)

Hi there,

When using the importer I discovered that Vertex Colors weren't being displayed. I have updated the existing shaders to run a pass that renders out the Vertex Colors (with an option to toggle it off).

I am happy to send through a PR if you deem it worthwhile - but understand that there may be work around replacing the shaders anyway. In either case this may help someone else so I thought I would post it here.

Cheers
Rich Young.

**Comment by handyjellyfish** [comment]
#210

**Comment by antoninklopp** [comment]
Hi, 

I just discovered this issue on one of my objects and I think that it would be very cool to send the code through a PR since a lot of people might need this.

**Comment by AdamMitchell-ms** [comment]
Fixed with #512
