### ISSUE TITLE
Hide node before model is completely loaded

### ISSUE THREAD

**Issue by RomanFrom710** [KhronosGroup/UnityGLTF#469]
I'd like to hide some nodes of loaded GLTF model. If I hide them right after a model is loaded (after `await gltfComponent.Load()`) they still flick for a moment on the scene. I can't do anything with that since UnityGLTF loads nodes consequentially and places them at the scene root until the whole model is loaded, that's why they're flickering.

So are there any ways to hide a node immediately when it appears on the scene?

**Comment by antoninklopp** [comment]
Hi, 

If you are using the Load method from GLTFImporter, you can set **bool showSceneObj** to false, which will hide your object during loading.

**Comment by RomanFrom710** [comment]
Hi @antoninklopp ,

So should I use `GLTFSceneImporter` instead of `GLTFComponent`?

**Comment by antoninklopp** [comment]
Hi, 

I actually don't know because I always used `GLTFSceneImporter`. It seems to be the way its done in the tests. Maybe you would get a better answer when a contributor responds here.

**Comment by pfcDorn** [comment]
I added the option to the GLTFComponent eb2987a67a84a87fda6e8924e0ae0011feab97f1
