### ISSUE TITLE
Cannot access a closed Stream

### ISSUE THREAD

**Issue by gp70** [KhronosGroup/UnityGLTF#473]
**Issue**: When loading files at runtime with UnityGLTF, an error will sometimes be raised that reads "ObjectDisposedException: Cannot access a closed Stream."

**Effect**: There do not seem to be any adverse effects - files load as they should, and there is no noticeable impact on performance.

**Environment**: Unity 2019.1.10f1, edit made to UnityGLTF code in order to read directly from stream:
`importOptions.ExternalDataLoader = new FileLoader(directoryPath);` replaced with `importOptions.ExternalDataLoader = new StreamLoader(ReadStream);`, with a corresponding ReadStream variable.

**Debugging**: I've managed to track it to the Stream associated with the bufferCacheData objects in AssetCache - if that Stream isn't closed in AssetCache's Dispose() method, then the error doesn't show up. The error seems to come from line 579 of GLTFSceneImporter: `GLTFParser.ParseJson(_gltfStream.Stream, out _gltfRoot, _gltfStream.StartPosition);`, but I'm not sure why this would be trying to read the buffer cache after it's already been closed.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
