### ISSUE TITLE
Extremely Large GC Allocations

### ISSUE THREAD

**Issue by BananaHemic** [KhronosGroup/UnityGLTF#474]
I compiled this plugin from commit 16f3112cf3352815bbb89da4f48d742cad4c83b9 in Release mode. When loading the VC.glb model via LoadSceneAsync() in a coroutine, the process freezes the editor for about 16 seconds, and generates 2.8 GB of GC allocations. This is substantially more GC allocations that I would anticipate given the size of the model.

3D Viewer loads the model in a few seconds, and Task Manager shows a memory usage of around 120MB.

Is this expected behavior, and can anything be done to improve the performance?

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
