### ISSUE TITLE
Unrecognized mesh attributes

### ISSUE THREAD

**Issue by gp70** [KhronosGroup/UnityGLTF#475]
Due to the new changes to the way that GLTFHelper's BuildMeshAttributes function works, only a given set of mesh attributes are usable, and attribute keys which do not match any in the switch statement throw an exception, which prevents the model from being loaded. In the case that I ran into, the mesh being loaded has a "_BATCHID" attribute which results in an exception.

**Comment by jhaverkost** [comment]
I just ran into the same error.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
