### ISSUE TITLE
Split GLTF folder into submodule

### ISSUE THREAD

**Issue by mtschoen** [KhronosGroup/UnityGLTF#48]
It would be much easier to include this in your project and keep it up to date if there were a separate repository for the package itself as well as this repo for the project, tests, etc.

**Comment by robertlong** [comment]
The current plan is to bundle the GLTF folder into a `.unitypackage` and publish versioned releases on Github #7 

This is similar to how [VRTK](https://github.com/thestonefox/VRTK), [UniRX](https://github.com/neuecc/UniRx), [Github for Unity](https://github.com/github-for-unity/Unity), and many others manage their releases.

We could do this now, but the project is undergoing a lot of changes to its architecture (see #40). I'd like to at least land that before we start versioning. @MSblgross would you agree?

**Comment by MSblgross** [comment]
Yeah I think after the architecture changes land would be a good time to start release a unitypackage. We should also distribute it on the asset store as well for discoverability.

**Comment by mtschoen** [comment]
A unitypackage is a good idea, of course, but I still think a submodule would be helpful, as well. The point is that you get the code along with a repository that you can use to sync latest changes, or contribute fixes if you have made them locally. This is a much better workflow than having to maintain a separate repository and copy files back and forth.

**Comment by robertlong** [comment]
I'm not certain we want to add the complexity of submodules and multiple repositories to support this use case. Although, I agree that the unitypackage method is not the best way to stay up to date with the latest changes or contribute back to the project. I also will admit, I haven't seen any Unity library distributed in this way and would be curious to see how consumers of that library like it.
 
If you're not working on a team, symlinking the GLTF directory from the cloned repository into your assets directory is a good option. Any changes you make to the code in your project will be made to the UnityGLTF project and you can commit and push from there. However, these symlinks are harder to maintain on a team. [Projeny](https://github.com/modesttree/Projeny) solves similar problems and is better for teams, but I don't know if it will support git dependencies well.

The perfect solution for all of this would be a real package manager for Unity. Which is coming although who knows when it will land. https://forum.unity3d.com/threads/what-is-packman.482001/

I'm curious to hear others thoughts on submodules and how they've solved this problem in the past.

**Comment by mtschoen-unity** [comment]
Yeah, I've seen this done with symlinks in the past. Another argument for doing this is that you can version the project and the module separately. If the project/support files change because of a Unity upgrade, or if you decide to not include say unit tests, the version # doesn't have to bump on one for changes in the other.
