### ISSUE TITLE
.gltf import materials problem for Lantern example

### ISSUE THREAD

**Issue by Stephengower** [KhronosGroup/UnityGLTF#484]
In the LanternTestScene, the Loading doesn't work all Via url. For some reason the URI request doesn't return things correctly.

But when loading from StreamingAssets, there is another problem. 

If you check "Use Stream", and try the following:
/Lantern/glTF-Binary/Lantern.glb 
the import works fine.

If you try the following:
/Lantern/glTF/Lantern.gltf
the resulting model has screwed up materials.

![image](https://user-images.githubusercontent.com/19933590/63622056-759f5800-c5aa-11e9-951b-cd9913ecdba8.png)

![image](https://user-images.githubusercontent.com/19933590/63622085-8780fb00-c5aa-11e9-8195-20259b2fe615.png)

**Comment by Stephengower** [comment]
It looks like issue #462 is the same as this.

**Comment by Stephengower** [comment]
If seen the same problem with most of the models I've tried loading.  The version of UnityGLTF included in the sketchfab for Unity doesn't have this same issue.    I don't see a lot of activity here (summer break?), so my guess is that someone checked in some changes without fully testing, and left things in a bad state.  Hopefully someone can find some time to check into this.

**Comment by Stephengower** [comment]
To workaround this issue, in GLTFSceneImporter.cs, in the ConstructImageBuffer method, change the LoadStream call to use LoadStreamSync instead.

//  await _options.ExternalDataLoader.LoadStream(image.Uri);
 _options.ExternalDataLoader.LoadStreamSync(image.Uri);


For some reason, the async LoadStream method only works once, so only the first texture is loaded, and all others are empty.

**Comment by nodermatt** [comment]
For reference, the file is located in UnityGLTF\UnityGLTF\Assets\UnityGLTF\Runtime\Scripts

Unfortunately, I could neither load the LanternTestScene nor the Streaming example. I always get the 404 error, shown below:

![image](https://user-images.githubusercontent.com/1467464/68470604-ae031980-021c-11ea-8d74-91b76193a23e.png)

@Stephengower Have you had the same issue with the Streaming Asset?

**Comment by fagerbur** [comment]
this has been resolved by @mhochk in #532 and can be closed
