### ISSUE TITLE
Is Draco support coming?

### ISSUE THREAD

**Issue by Stephengower** [KhronosGroup/UnityGLTF#488]
Draco mesh compression looks to be a good way to greatly reduce the mesh file sizes for Gltf files.  There is a gltf-pipeline project in GitHub that can be used to convert a GlTF file to use draco compression.  But as far as I can tell, UnityGLTF (and nothing else I've seen) can read draco-compressed GlTF files.   Does anyone know how to do this?  Is this something that is going to be added to UnityGLTF?  I would think that a lot of people using UnityGlTF would appreciate this addition.

**Comment by pfcDorn** [comment]
Fixed in latest release
