### ISSUE TITLE
using latest version fail to parse gltf object on android device.

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/UnityGLTF#489]
![mmexport1568029099228](https://user-images.githubusercontent.com/43545191/64527779-673a9580-d339-11e9-9dce-235ed6b00e21.jpg)
targeting on android Oreo.minimal sdk is android 7.1.using runtime debug to show the console log.and I got this,in the editor works fine.does anyone met this problem?

**Comment by jeremiasbaur** [comment]
Can you provide more info etc., please?

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
