### ISSUE TITLE
Tangents not calculated if missing

### ISSUE THREAD

**Issue by ANTONBORODA** [KhronosGroup/UnityGLTF#491]
Hello,
Looking through the Scene Importer code I see that the importer ignores Tangents if they are missing. 
This seems to be against the spec, as the spec states that it is required for the client implementation to calculate tangents
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes
I have issue with specific models that have no tangents and normal maps are not displayed correctly due to this.
Can this be corrected to match the spec and calculate the tangents client side?

**Comment by pfcDorn** [comment]
Fixed in latest release
