### ISSUE TITLE
NewtonSoft.JSON

### ISSUE THREAD

**Issue by SorenMuller** [KhronosGroup/UnityGLTF#493]
HI,

Have you tested it on IOS IPAD/Iphone and Android..
We have had problems usign standard version of Newtonsoft.json on ipad, worked fine on PC/MAC..
We had to use the version of Newtonsoft.JSON located in unity store v. 8.0.0.0.

Thanks

**Comment by antoninklopp** [comment]
Hi, 

You can't use two versions of Newtonsoft and it seems to me that UnityGLTF is using the 8.0 Newtonsoft. 

This explains why. 

Regards
