### ISSUE TITLE
Add Support for Specular Glossiness Physically Based Rendering

### ISSUE THREAD

**Issue by robertlong** [KhronosGroup/UnityGLTF#5]
This is the only documentation I can find on this so far: https://github.com/sbtron/glTF/tree/KHRpbrSpecGloss/extensions/Khronos/KHR_materials_pbrSpecularGlossiness#additional-maps

I'd be nice to support this workflow, but I'd like to hold off until it's finalized.

**Comment by jm991** [comment]
Hi,

Could I have access to make pull requests? I have forked the repository and added a prototype of loading spec/gloss for KHR_materials_pbrSpecularGlossiness: https://github.com/jm991/UnityGLTF/commits/master

I'd like to get feedback on my implementation and work with the group to get spec/gloss supported in master.

Thank you!
John

![image](https://user-images.githubusercontent.com/3520284/31257809-a8d75c96-a9ef-11e7-87d8-809f7bc8bbae.png)

**Comment by sbtron** [comment]
Added in #74
