### ISSUE TITLE
Add in Support for SRP

### ISSUE THREAD

**Issue by blgrossMS** [KhronosGroup/UnityGLTF#504]
Currently UnityGLTF uses legacy rendering instead of the ScriptableRenderingPipeline. Support should be added for Universal Render Pipeline and HD Render Pipeline

**Comment by nvandessel** [comment]
As a temporary fix I updated SpecGlossMap.cs SpecGloss2StandardMap.cs, MetalRoughMap.cs and MetalRough2StandardMap.cs to target Universal Render Pipeline/Lit and update the _Color and _MainTex to _BaseColor and _BaseMap

**Comment by ROBYER1** [comment]
Any update on this?

**Comment by andrefrancavilla** [comment]
2022 and still no update. A modern version of this plugin is needed, right now I'm modifying it according to @nvandessel's suggestion.

**Comment by pfcDorn** [comment]
Fixed in latest release
