### ISSUE TITLE
Image loading 'race condition' issue and solution

### ISSUE THREAD

**Issue by mathiassiig** [KhronosGroup/UnityGLTF#508]
I wasn't sure how to name this issue. Anyway, onto the main point.
You got an interface called `ILoader` which has a function called `LoadStream`.
I was a little suspicious already at this point because it doesn't return anything, it's just a task.

```csharp
public Task LoadStream(string gltfFilePath)
{
	if (gltfFilePath == null)
	{
		throw new ArgumentNullException("gltfFilePath");
	}

	return LoadFileStream(_rootDirectoryPath, gltfFilePath);
}

private Task LoadFileStream(string rootPath, string fileToLoad)
{
	string pathToLoad = Path.Combine(rootPath, fileToLoad);
	if (!File.Exists(pathToLoad))
	{
		throw new FileNotFoundException("Buffer file not found", fileToLoad);
	}

	return Task.Run(() => { LoadedStream = File.OpenRead(pathToLoad); });
}
```
The result is that `LoadedStream` can and very likely will be overwritten eventually, for example in this line later in `GLTFSceneImporter.cs`:

```csharp
await _options.ExternalDataLoader.LoadStream(image.Uri);
_assetCache.ImageStreamCache[sourceId] = _options.ExternalDataLoader.LoadedStream;
```

This is run N amount of times, where N is the amount of textures the material has.

I propose you rewrite `ILoader` to not have `LoadedStream`, but instead `LoadStream` should be of return type `Task<Stream>`, like this:

```csharp
public async Task<Stream> LoadStream(string gltfFilePath)
{
	if (gltfFilePath == null)
	{
		throw new ArgumentNullException("gltfFilePath");
	}
	string pathToLoad = Path.Combine(_rootDirectoryPath, gltfFilePath);
	if (!File.Exists(pathToLoad))
	{
		throw new FileNotFoundException("Buffer file not found", gltfFilePath);
	}

	return await Task.Run(() => File.OpenRead(pathToLoad));
}
```

And then the previously mentioned lines could look something like this:
```csharp
var stream = await _options.ExternalDataLoader.LoadStream(image.Uri);
_assetCache.ImageStreamCache[sourceId] = stream;
```

... at least this works for me. Thanks in advance.

**Comment by mhochk** [comment]
Resolved with #532
