### ISSUE TITLE
Model with animation throws IndexOutOfRangeException(s)

### ISSUE THREAD

**Issue by kvanlin-spoton** [KhronosGroup/UnityGLTF#510]
Some models with animations that I try to load fail on the following assert and exception(s):

`Unity does not allow you to put two keyframes in with the same time, so this should never occur.
UnityEngine.Debug:Assert(Boolean, String)
UnityGLTF.GLTFSceneImporter:GetCurveKeyframeLeftLinearSlope(Keyframe[], Int32) (at Assets/UnityGLTF/Runtime/Scripts/GLTFSceneImporter.cs:1092)`

`IndexOutOfRangeException: MoveKey
UnityEngine.AnimationCurve.MoveKey (System.Int32 index, UnityEngine.Keyframe key) <0x185049e8fe0 + 0x00062> in <578b5b677e3045f586753155bc1864cb>:0
UnityGLTF.GLTFSceneImporter.SetTangentMode (UnityEngine.AnimationCurve curve, UnityEngine.Keyframe[] keyframes, System.Int32 keyframeIndex, GLTF.Schema.InterpolationType interpolation) (at Assets/UnityGLTF/Runtime/Scripts/GLTFSceneImporter.cs:1079)
UnityGLTF.GLTFSceneImporter.SetAnimationCurve (UnityEngine.AnimationClip clip, System.String relativePath, System.String[] propertyNames, GLTF.Schema.NumericArray input, GLTF.Schema.NumericArray output, GLTF.Schema.InterpolationType mode, System.Type curveType, UnityGLTF.ValuesConvertion getConvertedValues) (at Assets/UnityGLTF/Runtime/Scripts/GLTFSceneImporter.cs:1044)
UnityGLTF.GLTFSceneImporter+<ConstructClip>d__76.MoveNext () (at Assets/UnityGLTF/Runtime/Scripts/GLTFSceneImporter.cs:1161)`

Note that I have already added the following check to the `SetTangentMode` method:
`if (keyframeIndex < 0 || keyframeIndex >= keyframes.Length) {	return;	}`
This also already caused an `IndexOutOfRangeException`.

Example of a model with the issue: (source https://sketchfab.com/3d-models/medieval-fantasy-book-06d5a80a04fc4c5ab552759e9a97d91a)
[medieval_fantasy_book.zip](https://github.com/KhronosGroup/UnityGLTF/files/3743032/medieval_fantasy_book.zip)

It looks like the `curve.frames.Length` is different from the `keyframes.Length` (method argument), I'm not sure if this is related. When I add a catch for the `IndexOutOfRangeException` the model loads fine and the animations seems to work correctly (at first glance).

**Comment by emackey** [comment]
Likely duplicate with #476.

**Comment by pfcDorn** [comment]
Fixed in latest release
