### ISSUE TITLE
Shader transparency bug

### ISSUE THREAD

**Issue by jeremiasbaur** [KhronosGroup/UnityGLTF#514]
Hello everyone,

I am currently facing a weird shader bug. I don't know much about shaders so I am reporting my problems here.

If you take a look at this image, you can see that some of the faces are inverted.
![image](https://user-images.githubusercontent.com/41521832/67667766-db271080-f96e-11e9-8091-6b4ec73c410d.png)

As soon as I expand the material of this object, the faces update and the object is shown correctly. Other objects also have this behavior. 
![image](https://user-images.githubusercontent.com/41521832/67667782-e5e1a580-f96e-11e9-837f-8bce51a54b1c.png)

What is causing this problem? Is it a bug in the provided shaders or a Unity bug?
Let me know if you need more information.

**Comment by BlackMatlock** [comment]
Having this same problem. Anyone?

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
