### ISSUE TITLE
HTTPRequestException running LanternTestScene from Samples

### ISSUE THREAD

**Issue by nodermatt** [KhronosGroup/UnityGLTF#518]
After cloning the repo, building SceneExporter for Release and opening the project in Unity, I get the following error when trying to run the "LanternTest" scene.

![image](https://user-images.githubusercontent.com/1467464/68468446-58c50900-0218-11ea-941b-76012de24d8f.png)

Am I using the wrong file? The documentation states any file from the assets/gltf/examples may be used, however, there is no "examples" but "samples" folder thus I assumed "samples" is the folder.

(potentially related issues https://github.com/KhronosGroup/UnityGLTF/issues/484 and https://github.com/KhronosGroup/UnityGLTF/issues/462

**Comment by nodermatt** [comment]
The reason for the 404 was that I didn't have the https://github.com/KhronosGroup/glTF-Sample-Models project checked out into the www folder in my project root. After creating the www folder and copying the glTF-Sample-Models into it, it worked fine.

It's possible to change the location of the gltf files, but not to define the root directory of the Web server component
![image](https://user-images.githubusercontent.com/1467464/68655325-24ab5a00-0530-11ea-8a04-18a31e425466.png)


I switched from cloning the master to branch to using the [1.0.1 release](https://github.com/KhronosGroup/UnityGLTF/releases/download/v1.0.1/UnityGLTF.unitypackage)

**Comment by fagerbur** [comment]
Sounds like this sample is working as expected. Beyond an update to the readme to add some clarification on sample usage, can this issue be closed?

**Comment by nodermatt** [comment]
@fagerbur Yes, that's correct. Adding the sample models as a submodule would do the trick I suppose. That way the required resources are automatically downloaded.

**Comment by fagerbur** [comment]
I'm not sure we would want it tied in that closely to this project but I'll add a pull request to update the readme with information about the sample models.

@AdamMitchell-ms If you're alright with it, i think this issue can be closed

**Comment by fagerbur** [comment]
Nevermind I'm dumb, the sample models are already a submodule. Not sure how I missed that the first time I looked. @mhochk you can probably close this one out as well.
