### ISSUE TITLE
Unity 2019.1.4f1 nothing works.

### ISSUE THREAD

**Issue by anupamdas2012** [KhronosGroup/UnityGLTF#522]
Hi, Unity 2019.1.4f1 issue. I followed the dll build instructions, dlls are built. I opened the unity project and none of the examples work. When I try to use editor importer and select a .gltf or .glb file I get nothing. So essentially something is broken or proper configuration needs to be documented for the latest release of unity. Any pointers would help.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
