### ISSUE TITLE
Windows Standalone Build + Multithreading

### ISSUE THREAD

**Issue by Yohdu** [KhronosGroup/UnityGLTF#529]
I have a gltf model that I can load synchronously (Multihreading = false) in about 10 seconds (both in editor and in a windows standalone build). But when I set Mutlithreading to true, the windows standalone build takes about 3 minutes to complete the loading of the same gltf model.

It's really annoying. Do you have any idea on why this problem is occuring?

Unity version : 2019.2.9f1

**Comment by rekerukuru** [comment]
Same problem, I disabled the multithread on Standalone to fix it

**Comment by rekerukuru** [comment]
If anyone has a solution to use the multithread with better performance, share it !
Thanks

**Comment by pfcDorn** [comment]
Will be soon available :)  > https://github.com/KhronosGroup/UnityGLTF/pull/687
