### ISSUE TITLE
Enable Animation Export with Sketchfab's Fork

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/UnityGLTF#531]
Sketchfab's fork of UnityGLTF supports pretty good animation export for nearly two years now, and as far as I know (and from my testing) this repo here still doesn't, which is really unfortunate as it contains many other fixes.

It would be great if the relevant parts that enable animation export are brought over. I messed with it a bit, but are not familiar enough with the details of the file format to get that to work. I might find more time to test but I think it would be much faster to do for someone with more GLTF insight.

Fact is, if you download the unitypackage from https://github.com/sketchfab/UnityGLTF/releases/tag/1.1.0 (you can disable the actual sketchfab upload and log where the GLB is produced), you get properly exported animations in the resulting GLB file.

(for testing, here's sketchfab fork latest with just a simple export button in "Sketchfab/Publish to Sketchfab": https://github.com/prefrontalcortex/UnityGLTF/tree/sketchfab-master)

**Comment by soraryu** [comment]
I opened #533 with what I got over from Sketchfab which seems to work the same as their old fork.

**Comment by odweibo** [comment]
Hi, I have created a pull request for support animations and skeleton [export.](https://github.com/KhronosGroup/UnityGLTF/pull/561)

**Comment by owilliamailliwo** [comment]
Hi, I have created a pull request for support animations and skeleton export.[#561](https://github.com/KhronosGroup/UnityGLTF/pull/561) @soraryu

**Comment by soraryu** [comment]
Hey @owilliamailliwo - have you compared in functionality with my PR above? I've also added more features and a ton of stability fixes on my fork - would be great if we can work on getting the best of both!
