### ISSUE TITLE
How to use UnityGLTF

### ISSUE THREAD

**Issue by lizylgit** [KhronosGroup/UnityGLTF#534]
Hi, 
I am new to Unity, but, not new in 3D.  I have used GLTF in other tools which works well. 
I have been trying to follow steps to use 'UnityGLTF in Unity', But, couldn't find the steps to use this library. 
My use case is to load  GLTF model at runtime from an api.  The current GLTF model is a single asset bundle contains the binary and texture ( I can split the single GLTF file  into .bin & textures if that is a requirement).

Please could someone help me with the steps to install UnityGLTF in Unity and also how to go about loading it in runtime. Thanks a Lot

**Comment by fagerbur** [comment]
The current release is terribly out of date but you can:
1) download the .unitypackage file of the latest release
2) To import in Unity, Assets > Import Package > Custom Package

If you have visual studio then you can follow the build instructions on the readme and create the unity package yourself with the latest code.

To use in your project, there are several ways, this is the one I'm currently using to load from a file
```
ActiveObject = new GameObject();
GLTFComponent gltfcomponent = ActiveObject.AddComponent<GLTFComponent>();
gltfcomponent.GLTFUri = model.Path;
```
Alternatively, the [GLTFComponentTest ](https://github.com/KhronosGroup/UnityGLTF/blob/03dd3739d9c08cb899f319032da53188a3c64da7/UnityGLTF/Assets/UnityGLTF/Scripts/Tests/Integration/GLTFTestComponent.cs) includes an api example

Hope this helps!

**Comment by lizylgit** [comment]
> The current release is terribly out of date but you can:
> 
> 1. download the .unitypackage file of the latest release
> 2. To import in Unity, Assets > Import Package > Custom Package
> 
> If you have visual studio then you can follow the build instructions on the readme and create the unity package yourself with the latest code.
> 
> To use in your project, there are several ways, this is the one I'm currently using to load from a file
> 
> ```
> ActiveObject = new GameObject();
> GLTFComponent gltfcomponent = ActiveObject.AddComponent<GLTFComponent>();
> gltfcomponent.GLTFUri = model.Path;
> ```
> 
> Alternatively, the [GLTFComponentTest ](https://github.com/KhronosGroup/UnityGLTF/blob/03dd3739d9c08cb899f319032da53188a3c64da7/UnityGLTF/Assets/UnityGLTF/Scripts/Tests/Integration/GLTFTestComponent.cs) includes an api example
> 
> Hope this helps!

Thanks  a lot @fagerbur for your response. Really appreciate your time.
I tried the first two steps as mentioned in your reply, by downloading the 'latest release' as custom package. 
When I 'Play' from unity the models are loaded and works fine. However, when I build for PC/ Mac, the build is successful,  but no models are loaded, not sure why that would be!  Testing on Mac.
I have  copied the 'gltf' model file to 'StreamingAssets' folder and changed the URI to point to this file name.
 'Play' is working but no models are shown when I 'Build' it - what am I doing wrong?

Next, I was trying the latest git to build a package but,  am not sure how to go about with that,  do I use 'GLTFSerialization' in VS and then build it as 'plugin'?  not clear on what I am meant to do - Sorry! if I'm missing something that is obvious, as I am new to Unity. 
Thanks

**Comment by lizylgit** [comment]
Thank You so much @fagerbur. This is working now, after debugging the build noticed the runtime issue was due to shader not getting added to the project setting.

**Comment by fagerbur** [comment]
@lizylgit Sorry for not getting back to you quicker on your last message but glad you got it figured out! If everything is good, feel free to close the issue.
