### ISSUE TITLE
KHR_materials_pbrSpecularGlossiness export support

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/UnityGLTF#539]
#74 added support for importing specular/glossiness materials, but they still don't export properly - the extension is not added when exporting Standard (Specular) materials; instead, they produce errors in most GLTF viewers and render incorrect.

Reproduction is just: try to export an object with a "Standard (Specular)" material and a map assigned to the Specular slot.

Would be great to have export support for Standard (Specular) as well.

**Comment by owilliamailliwo** [comment]
I commited a new [pull request](https://github.com/KhronosGroup/UnityGLTF/pull/563) to close this issue.
