### ISSUE TITLE
Conversion error with Pbr shaders (Unity 2019, Android)

### ISSUE THREAD

**Issue by marcspraragen** [KhronosGroup/UnityGLTF#540]
[   I'm using Unity 2019.3.0f3, 
UnityGLTF package manifest has 
	"name": "org.khronos.unitygltf",
	"displayName": "Khronos GLTF Loader",
	"version": "1.0.0",
	"unity": "2018.3",

I'm building for Android 7 (v24), using .NET 4.x API, mono scripting background. Testing on a Samsung 8+, though I haven't got it to build yet.  I have also saved the generated shader variant instructions to an asset as per previous issues here. ]

Before I do any script surgery (with very limited knowledge of these files) or revert to Unity 2018.3, I thought I'd check if anyone here has encountered this issue. I've attached the error log and the possible culprit VertexColor.cginc Thanks for your time.

--Marc

Error log: 
[GLTFconversionErrors.txt](https://github.com/KhronosGroup/UnityGLTF/files/4002784/GLTFconversionErrors.txt)

Here is the .cginc file that the errors are all blaming: 
[VertexColor.cginc.txt](https://github.com/KhronosGroup/UnityGLTF/files/4002786/VertexColor.cginc.txt)

**Comment by marcspraragen** [comment]
Anybody at Khronos? This is a showstopper...

**Comment by marcspraragen** [comment]
I fixed it. (desperation)

In shaders/VertexColor.cginc, change the class of "WrappedVertexOutputForwardBase.innerValue": 

struct WrappedVertexOutputForwardBase {
    //VertexOutputForwardBase innerValue;
	VertexOutputBaseSimple innerValue;
    fixed4 color : COLOR;
};

This ALSO seemed to fix #125 (UNITY_STANDARD_SIMPLE already defined).

PLEASE put this in readme, or just fix the master branch!

**Comment by AdamMitchell-ms** [comment]
Hey @marcspraragen, can you create a pull request with your change?  @mhochk or I can review it and get it into master.

**Comment by marcspraragen** [comment]
will do, and thanks :)

**Comment by marcspraragen** [comment]
Request set. Also, a note: during initial build for android, variant compilation will throw "not found" errors for VertexOutputBaseSimple vs. the two shaders, but following builds work fine.

**Comment by mhochk** [comment]
Fixed with #547
