### ISSUE TITLE
Dropped support for unity 5.6.7 ?

### ISSUE THREAD

**Issue by forsmoo** [KhronosGroup/UnityGLTF#543]
Hi, was trying to use this package in unity 5.7, but there are alot of errors with newer features of C#. I get errors like these with the GLTFSceneImporter among other scirpts:
Assets/UnityGLTF/Runtime/Scripts/GLTFSceneImporter.cs(368,14): error CS1644: Feature `asynchronous functions' cannot be used because it is not part of the C# 4.0 language specification

I'm building for Windows Standalone and the highest value for scripting backend I get is Mono2x and Api Compability level .NET 2.0 subset

**Comment by pfcDorn** [comment]
deprecated
