### ISSUE TITLE
Incorrect normal mapping with custom tangents

### ISSUE THREAD

**Issue by atteneder** [KhronosGroup/UnityGLTF#556]
The following scenes, that demonstrate proper normal mapping with custom tangents, do not create correct results:

<https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest>

<img width="373" alt="UnityGLTF-NormalTangentTest-Front" src="https://user-images.githubusercontent.com/2593014/73600667-eed8a900-4553-11ea-8c93-5e6468832bc1.png">
<img width="373" alt="UnityGLTF-NormalTangentTest-Front" src="https://user-images.githubusercontent.com/2593014/73600669-f0a26c80-4553-11ea-970f-52a58728c021.png">

This one as well:
<https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentMirrorTest>

See the given links on how it should look like and what possible errors could be.
Tested with Unity 2019.3.0f6

Somehow related: #491

**Comment by pfcDorn** [comment]
Fixed in latest release
