### ISSUE TITLE
Textures not exported in .glb

### ISSUE THREAD

**Issue by KasperKronborgUnity** [KhronosGroup/UnityGLTF#557]
When exporting .glb models using SaveGLBToStream(Stream stream, string sceneName) and SaveGLBToByteArray(string sceneName) textures are not included in the .glb file. 

Including this line as the first in SaveGLBToStream() seems to fix it, but I have not tested it much. 

_shouldUseInternalBufferForImages = true;

**Comment by jaspreetdhanjan** [comment]
Has this been resolved? Found the same issue.

**Comment by jaspreetdhanjan** [comment]
I used the PBR Metallic Roughness shader for the material and it fixed it.

**Comment by marioslokas-v** [comment]
> 
> 
> I used the PBR Metallic Roughness shader for the material and it fixed it.

Can you elaborate? I can't find either a "_shouldUseInternalBufferForImages" anywhere, nor anything changed when I added the PBR shader in the material.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
