### ISSUE TITLE
Can't compile VS project

### ISSUE THREAD

**Issue by antoine-ladrech** [KhronosGroup/UnityGLTF#558]
Hello, 

I can't compile the VS project for release. When I try to I get a error stating: 
"Your project file doesn't list 'win10' as a "RuntimeIdentifier". You should add 'win10' to the "RuntimeIdentifiers" property in your project file and then re-run NuGet restore."
 The error concerns the GLTFSerializationUWPTests project and only occurs when building for Release.

Has anyone have the same issue?
I'm on VS Community 2017 Version 15.9.19.

**Comment by segurvita** [comment]
In my case, when I set `Any CPU` to `x64`, I no longer get that error.

![image](https://user-images.githubusercontent.com/4960850/109103047-74398780-776d-11eb-80cd-139bd26f89d7.png)

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
