### ISSUE TITLE
Install Instruction unclear

### ISSUE THREAD

**Issue by Mrgove10** [KhronosGroup/UnityGLTF#565]
Hello I fin the install instruction kind of unclear.

When i import the .unityPackage i get some errors regarding ImportOptions
```
Assets\Imports\UnityGLTF\Assets\UnityGLTF\Runtime\Scripts\Factories\ImporterFactory.cs(13,78): error CS0246: The type or namespace name 'ImportOptions' could not be found (are you missing a using directive or an assembly reference?)
```

The unity package is also super old, any plans to update it ?

**Comment by Thomas-6freedom** [comment]
This is how it should looks like when importing :
![image](https://user-images.githubusercontent.com/49686866/78763166-19484780-7985-11ea-9176-be46615ff3b0.png)

Did you import [this unity package](https://github.com/KhronosGroup/UnityGLTF/releases/tag/v1.0.1) ?

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
