### ISSUE TITLE
Errors in unity, 2019.3.0f5

### ISSUE THREAD

**Issue by DevJeeth** [KhronosGroup/UnityGLTF#566]
I have built the dlls and added them after which these errors still remain, it seems like it can't find UnityEngine.TestTools.Utils 
Assets\UnityGLTF\Tests\Runtime\GLTFAssetGeneratorTests.cs(11,29): error CS0234: The type or namespace name 'Utils' does not exist in the namespace 'UnityEngine.TestTools' (are you missing an assembly reference?)
Assets\UnityGLTF\Tests\Runtime\GLTFAssetGeneratorTests.cs(17,26): error CS0246: The type or namespace name 'ColorEqualityComparer' could not be found (are you missing a using directive or an assembly reference?)
Assets\UnityGLTF\Tests\Runtime\GLTFAssetGeneratorTests.cs(85,3): error CS0246: The type or namespace name 'UnityTestAttribute' could not be found (are you missing a using directive or an assembly reference?)
Assets\UnityGLTF\Tests\Runtime\GLTFAssetGeneratorTests.cs(85,3): error CS0246: The type or namespace name 'UnityTest' could not be found (are you missing a using directive or an assembly reference?)

**Comment by DrScatman** [comment]
Same issue here. A reply to this would be much appreciated :)

**Comment by wangyanmeego** [comment]
Same isuue.

**Comment by sanjaysingh101** [comment]
How do you Build the dlls?

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
