### ISSUE TITLE
Custom shader / transparency + refraction in export?

### ISSUE THREAD

**Issue by efsjouw** [KhronosGroup/UnityGLTF#573]
Hi, it doesn't seem like my custom material/shader effect is being exported.
Is there any way to make this work by copying the properties or something?

What it looks like in Unity:
https://postimg.cc/LY41sG6y
![image](https://user-images.githubusercontent.com/7520611/78671348-78538100-78df-11ea-8bf9-e4ad0336e3cd.png)

What is looks like in the previewer:
https://postimg.cc/sB4Ws3yQ
![image](https://user-images.githubusercontent.com/7520611/78671303-67a30b00-78df-11ea-9004-f26c93d1b7e5.png)

EDIT: edited image links

**Comment by donmccurdy** [comment]
glTF does not support arbitrary custom shaders, as these aren't portable across tools and engines. The core glTF PBR model has fixed inputs, described in the specification. These include alpha, with modes for "alpha blend" and "alpha clip". Only alpha-based transparency is currently supported.

There are proposals in progress for inputs with physically-based transparency, see https://github.com/KhronosGroup/glTF/milestone/2 for a full list of relevant discussions, and probably the item on KHR_materials_transmission is most relevant. However, these are still drafts and not yet supported in tools.
