### ISSUE TITLE
Magic Leap - Single Pass Instanced rendering

### ISSUE THREAD

**Issue by EricBeetsOfficial-Opuscope** [KhronosGroup/UnityGLTF#578]
Since shaders are based on VertexColor.cginc, we have a rendering issue on Magic Leap: the stereo mode is broken, i.e. the rendering is only on the left eye (nothing appear on right eye..).

Do you have an idea ?

Thx in advance,
Eric

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
