### ISSUE TITLE
Workflow to export full scene from Unity editor to .glb?

### ISSUE THREAD

**Issue by juj** [KhronosGroup/UnityGLTF#580]
Heya,

I was wondering what the current state of the project is? Looks like there haven't been recent updates in a few months - perhaps this is on a lower burn atm, or?

What I was looking for is an editor tool that would enable the following workflow in latest Unity:

1. Import UnityGLTFExporter.unitypackage to an existing Unity project
2. A new Edit->Export to GLTF... option would appear
3. Choosing that option would serialize the selected object(s)/whole scene to a given .glb file?

Is this kind of workflow available and I missed it? It looks like there should exist a C# API to do that, though I was not quite able to find the documentation to how to add such an Editor tool to it?

How complete is the export-scene-to-gltf support state at btw? I was eyeballing the ["road to 1.0" document](https://github.com/KhronosGroup/UnityGLTF/projects/1) that seemed to be outlining pending work , but then noticed in [Releases](https://github.com/KhronosGroup/UnityGLTF/releases) page that the version numbeirng is already going beyond 1.0 at version 1.0.1, so not sure how much of the roadmap is still accurate?

**Comment by Skylion007** [comment]
Just use the editor widget: https://github.com/KhronosGroup/UnityGLTF/blob/bb85e9a38937b87d0ce8efaac00ba479ae706319/UnityGLTF/Assets/UnityGLTF/Editor/Scripts/GLTFExportMenu.cs

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
