### ISSUE TITLE
Is the rotation property of KHR_texture_transform supported?

### ISSUE THREAD

**Issue by a3doucet** [KhronosGroup/UnityGLTF#584]
Hello,

I've run into a situation where I need an embedded texture to be rotated 90 degrees on the model itself. Does this convertor support UV rotation as specified in the KHR_texture_transform extension, or will I need to find a workaround?

**Comment by adoucet85** [comment]
After testing, I have confirmed that this attribute is not supported. Can I expect a fix for this?

**Comment by stevenvergenz** [comment]
As far as I can tell, Unity all-up does not support texture rotation in a standard way. You'd have to write a custom shader for it, then write a custom importer to set the properties.

**Comment by adoucet52** [comment]
Thanks for letting me know. I've found a way around it.

**Comment by pfcDorn** [comment]
Fixed in latest release
