### ISSUE TITLE
Failing to deserialize sparse accessors

### ISSUE THREAD

**Issue by dri-richard** [KhronosGroup/UnityGLTF#587]
Our application reads glTF files from a 3rd party which would like to start using sparse accessors, but GLTFSerialization fails to deserialize them. These are files that pass validation.

Stepping through the code, AccessorSparse.Deserialize() immediately expects to find a PropertyName token, but given that a sparse data block is an object, e.g.:
`"sparse": {
 "count": 4,
 "values": {
 "bufferView": 2,
 },
 "indices": {
 "bufferView": 1,
 "componentType": 5123
 }
 }`
I'd expect it to read a StartObject token first.

I've experimented with this change, and deserialization now completes, but the scene importer fails with a NullReferenceException in ConstructMeshTargets() as it appears the targetAttributes are invalid.

I'm quite new to working with glTF files so I'm unable to proceed further, can anybody shed light on how I might debug this, or perhaps the sparse accessor support is incomplete and needs more work?

**Comment by pfcDorn** [comment]
Fixed in latest release
