### ISSUE TITLE
Building a project where all glbs are externally loaded will failed because of shader stripping

### ISSUE THREAD

**Issue by jeanfabre** [KhronosGroup/UnityGLTF#589]
Hi,

 We have a project where all content is exclusively downloaded externally, stored in the persistent folder and then loaded in game. We get an error in this published application where it can't find the shaders it needs to create the glb it just loaded. because it's been stripped during compilation since Unity did not find any usage for it  ( that's my understanding of the situation, I may be wrong here)

Is there a guide as to how to deal with this properly? right now, I am tempering with putting a glb in the resources, it seems to work, but is it the best way or not, I am not sure, there could be more implications that I am not foreseeing.

Bye,

 Jean

**Comment by marcinwalus** [comment]
Hello,
maybe you try to add "Assets/UnityGLTF/Runtime/Shaders/ShaderRetention/ShaderRetention.unity" scene to your application build (just have it on the "Scenes In Build" list).
I'm also loading glb files from "internet" and it works correctly for me.

BR,
Marcin

**Comment by jeanfabre** [comment]
Hi,

uhm, so that's the purpose of this scene! why not simply put the shaders in a Resources folder? that would be automated then...

Let me close this issue, but I would definitely consider improving this to avoid frustrations when devs encounter this.

Bye,

 Jean
