### ISSUE TITLE
Shaders fail for double-sided materials on Mobile devices.

### ISSUE THREAD

**Issue by adoucet52** [KhronosGroup/UnityGLTF#591]
Using Unity 2019.3.1 and tested on Samsung Android device, iOS 13 and iOS 12.

There appears to be a problem with the pbr metallic roughness shaders when they are used with double-sided materials. Some double-sided materials will display a flat colour instead of the assigned texture, or will be improperly lighted. These problem only appear when building for mobile devices. If the platform is set to Windows or Mac, the models render correctly. Switching the build target to Android or iOS will cause these issues to appear, even if are still running the scene on the Windows/Mac editor rather than the device.

Removing the double-sided material property causes the models to render properly, but I need to support double-sided materials for my project.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
