### ISSUE TITLE
Shaking animation

### ISSUE THREAD

**Issue by marcinwalus** [KhronosGroup/UnityGLTF#592]
When playing animation imported in glb file using latest version of the plugin some parts are "shaking/jiggling (i.e. commit #1e00333). This issue was not present in earlier versions of the plugin (i.e. commit 922e98d).

Videos presenting problem
- Broken animation: [Demo for UnityGLTF-master-1e00333](https://www.icloud.com/iclouddrive/0BLWQFlR-mTVKSSHHEuG6SkTQ#UnityGLTF-master-1e00333)
- Animation OK: [Demo for UnityGLTF-master-922e98d](https://www.icloud.com/iclouddrive/0VD1mQTRDPOOEGo-KFDg-Yamw#UnityGLTF-master-922e98d)

Example model: [ArcWeldingExample.glb](https://www.icloud.com/iclouddrive/0I_8Gy5X13H0TKu3HTtUSsKwA#ArcWeldingExample)

Unity version: 2019.4.2 on macOS 10.15.5

Issue can be reproduced in Editor but is also present when running application on device.
Also tested in babylonjs and animation in example model work smooth.

**Comment by pfcDorn** [comment]
Should be fixed. Please update to the latest version and open a new issue if the problem persists. Thanks!
