### ISSUE TITLE
No Import option

### ISSUE THREAD

**Issue by berk-can** [KhronosGroup/UnityGLTF#598]
Hello there
I've installed latest release of UnityGLTF via unitypackage file, but there are only export options under the tab there is no import option. Is there anything I need to do to enable import feature

**Comment by jeanfabre** [comment]
Hi,

 Import is done like any other assets, you just drag and drop them into the asset folder.

At runtime, please check the examples, they show how to load and import via code.

Are you experiencing issues with this?

Bye,

 Jean

**Comment by florolf1** [comment]
Import at runtime is working fine, but just drag and drop the folder containing the .gltf and .bin files is not working for me. Using Unity 2019.3

**Comment by jeanfabre** [comment]
uhm, I only drag and drop .glb files, I am not sure if .gltf and .bin are supported as an editor drag and drop feature.

**Comment by florolf1** [comment]
.glb is not working for me as well..
I can drag and drop it into the asset folder, i can see the file, but it is not converted. I cant do anything with the file.

**Comment by jeanfabre** [comment]
Hi,

 Have you tried with the project distributedby Khronos or is it on a project you created yourself and then imported the necessary files? you are likely missing some scripts.

Bye,

 Jean

**Comment by florolf1** [comment]
I tried both. 
Its is working in the Khronos project, but only for .glb files.
.gltf is not working for me.

**Comment by florolf1** [comment]
No support, switching to other plugin.

**Comment by congxinUSC** [comment]
Sorry for calling up an old thread but I just encountered the same problem and it seems the issue is still open.

**Comment by hybridherbst** [comment]
Please try the dev branch!

**Comment by congxinUSC** [comment]
Works, howerver I think it doesn't mean the issue is solved based on this repo's master branch. I'll leave the decision to you. I guess the official team has some opinion on the IPO of Unity (the company). However driving people to use other engines by not supporting GLTF in one of the most popular game engine so far really doesn't sound like a good idea (assuming that's the case). 😭

**Comment by hybridherbst** [comment]
I'll merge the dev branch back to main any day now, we just identified a couple runtime issues we wanted to address first. Thanks for confirming that the dev branch works for you, that's helpful!

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
