### ISSUE TITLE
New release of Unity GLTF

### ISSUE THREAD

**Issue by ThimoVBE** [KhronosGroup/UnityGLTF#599]
I was wondering if there is a date set for a new release of Unity GLTF. The last release is from April 2019 and I was curious if there will come a new version with additional features and bug fixes.

**Comment by DrScatman** [comment]
I am also wondering this, as the most recent version does not seem to work for .glb files using Unity 2019.2.17f1

**Comment by ThimoVBE** [comment]
@robertlong @blgrossMS @AdamMitchell-ms @stevenvergenz @mhochk Do you know something more about a potential new release of UnityGLTF (bug fixes and improvements) or is the development of UnityGLTF dead?

**Comment by ThimoVBE** [comment]
Does anyone else know if there are developers working on fixing issues/releasing new UnityGLTF versions?

**Comment by Skylion007** [comment]
The prefrontal-cortex fork seems like its the best maintained: https://github.com/prefrontalcortex/UnityGLTF

**Comment by ThimoVBE** [comment]
Does someone know if there is another repo of this Unity GLTF feature where there is official support and development?

**Comment by ThimoVBE** [comment]
Does Khronosgroup have another repo or something where they do active support on a GLTF importer for Unity?

**Comment by emackey** [comment]
I've heard there's recent development ramping up in glTFast: https://github.com/atteneder/glTFast

**Comment by pfcDorn** [comment]
Many new updates are available :)
