### ISSUE TITLE
Question: Why isn't JsonUtility being used?

### ISSUE THREAD

**Issue by StephenHodgson** [KhronosGroup/UnityGLTF#60]
Just curious why there's an [external dependency](https://github.com/KhronosGroup/UnityGLTF/tree/master/UnityGLTF/Assets/UnityGLTF/Plugins) to `Newtonsoft.Json.dll` when there's a [built in Json Utility in Unity](https://docs.unity3d.com/ScriptReference/JsonUtility.html)?

**Comment by robertlong** [comment]
Early on in the development I noticed that JsonUtility was considerably slower than parsing with JSON.NET. Also, UnityGLTF was recently split into two parts, a generic C# glTF loader that deals with JSON serialization/deserialization and the Unity importer/exporter. We use JSON.NET to make the JSON serialization/deserialization project usable by other .NET projects.

**Comment by StephenHodgson** [comment]
> Early on in the development I noticed that JsonUtility was considerably slower than parsing with JSON.NET.

I'm surprised to hear this.  Here's some benchmark tests (two years old, but should be easily replicated)
http://jacksondunstan.com/articles/3303

> Also, UnityGLTF was recently split into two parts

I can understand the need to have the generic C# have a JSON parser of it's own.

**Comment by robertlong** [comment]
It looks like that benchmark was done with JSON.NET's reflection based APIs. We moved away from the reflection based API to manually serializing/deserializing (see #10).

Basically we use JSON.NET for tokenizing the string and then we manually parse those into a known schema. This way we avoid reflection on the class passed into `JsonConvert.DeserializeObject<T>()` which is slow and not what you want for a runtime importer.

Ideally we could generate this type of parser from a JSONSchema in the future, but for now we are writing that by hand in the GLTFSerialization project:

https://github.com/KhronosGroup/UnityGLTF/blob/master/GLTFSerialization/GLTFSerialization/Schema/GLTFRoot.cs#L119

**Comment by StephenHodgson** [comment]
I've noticed a lot of people complaining on the Mixed Reality Toolkit that they have conflicts with the Newtonsoft.Json.dll.  Is there any plans to mitigate this issue?
