### ISSUE TITLE
Unity Cloud Builds fails to handle GLB assets.

### ISSUE THREAD

**Issue by jeanfabre** [KhronosGroup/UnityGLTF#600]
Hi,

We have an issue with Unity Cloud builds, where the glb assets are missing during compilation. no error produced, the gameobject is just not showing anything ( probably mesh missing or material, it's very odd). The only way I could fix this is to call a pre export method that deletes the meta file associated, then the GLB is good, however, this means the guid changes so it can't be referenced within prefabs or scenes.

Is there any other way? or possibly a fix coming for this?

While testing we found that within unity editor, calling for re importation on a broken glb never works, that's something that should be looked at to actually force the importation when requested.

Thanks,

 Jean

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
