### ISSUE TITLE
Make usage instructions more clear in the readme

### ISSUE THREAD

**Issue by marcofugaro** [KhronosGroup/UnityGLTF#601]
I think the usage instructions of this library should be at the top, after explaining the features of the library.

What is needed:
- Instructions on how to download the library
- Where do I put the library in my unity project?
- Any other step to enable the library

**Comment by johngoren** [comment]
Same thought. I'm trying to follow the directions and it seems like the path to the examples has changed, too.

**Comment by Antonio-Iliev** [comment]
> Same thought. I'm trying to follow the directions and it seems like the path to the examples has changed, too.

You can create a 'Plugins' folder in the main Assets folder. Copy GLTFSerialization.deps.json, GLTFSerialization.dll, GLTFSerialization.pdb, Newtonsoft.Json.dll from bin/Release/netstandard1.3 folder. And ready to go.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
