### ISSUE TITLE
Cannot export animations

### ISSUE THREAD

**Issue by IMorphizI** [KhronosGroup/UnityGLTF#602]
Hello, I'm not sure if this plugin supports this feature, but I'm trying to export an animated cube to .GLB file extension. The model exports nicely, but there is no animation. I used the export function from the Unity menu (GLTF -> Export SelectedGLB).

**Comment by jiangcaiyang** [comment]
> Hello, I'm not sure if this plugin supports this feature, but I'm trying to export an animated cube to .GLB file extension. The model exports nicely, but there is no animation. I used the export function from the Unity menu (GLTF -> Export SelectedGLB).

I have the same problem. Maybe the khronos guys are very busy and they forget adding these feature. Another repo you could refer to and it can export animation nicely (though not fully tested): git@github.com:sketchfab/UnityGLTF.git

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
