### ISSUE TITLE
glTF-Sample-Models and glTF-Asset-Generator folders empty

### ISSUE THREAD

**Issue by bkfichter** [KhronosGroup/UnityGLTF#603]
I downloaded the zip. Got everything compiled. Main runs but nothing shows up, same for other examples. Www is incomplete. both glTF-Sample-Models and glTF-Asset-Generator folders empty.

**Comment by YeonduBori** [comment]
@bkfichter You should also clone submodules in this repository
![image](https://user-images.githubusercontent.com/44824411/114657451-10721a80-9d2b-11eb-8931-f638355c3c0a.png)
Can you see  the blue highlighted in screenshot?
go there and get contents then you can fix it

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
