### ISSUE TITLE
Exporter doesn't support base color textures

### ISSUE THREAD

**Issue by peoplepilot** [KhronosGroup/UnityGLTF#609]
Am I missing something? Seems like a lot of more advanced functionality is supported...

**Comment by ponahoum** [comment]
It seems that for the exporter to work with colors and textures you need to have a shader that supports metallic roughness on the object you want to export. Such a shader is included in the project and is called "PBRMetallicRoughness". 

That's a pretty stupid behavior, the exporter should allow working with any shader, even though it might skip some properties upon export...

**Comment by peoplepilot** [comment]
Yes, thanks.

In the end I hacked the GLTFSceneExporter.cs ExportMaterial function and added the below code after the IsPBRMetallicRoughness test:

else if (materialObj.HasProperty("_MainTex"))
{
  material.PbrMetallicRoughness = ExportPBRMetallicRoughness(materialObj);
}

which is working well enough for my purposes...

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
