### ISSUE TITLE
Export Texture to DDS for Mixed Relity Portal support and performance enhancments

### ISSUE THREAD

**Issue by hridpath** [KhronosGroup/UnityGLTF#61]
The Windows 10 Creators Update Mixed Reality Portal has requirements that glTF be used and that textures need to be in DDS format. 
Adding this to the project will allow the developer to be able to export and compile Unity objects that are suitable for use in the MR portal.

**Comment by StephenHodgson** [comment]
Why use a depreciated file format, when DX3/DX5 is more widely supported? 
(Trick question I know it's part of the glTF MSFT standard, but really they should update that)
