### ISSUE TITLE
where is the .unitypackage file??

### ISSUE THREAD

**Issue by jinsw1081** [KhronosGroup/UnityGLTF#610]
where is the .unitypackage file??

i don't find package file

**Comment by Schaubli** [comment]
You can find all the releases under [releases](https://github.com/KhronosGroup/UnityGLTF/releases/) and will also find the latest .unitypackage file (Apr 3, 2019) there.

**Comment by andybak** [comment]
> blgrossMS released this on 3 Apr 2019

I sense this project is in the doldrums. There's a fair bit of activity on forks but no pull requests.

Is anyone at Khronous able to accept PRs if there were any? Are there any plans to hand over stewardship at any point?

Even updating the readme with current project status would be useful.

**Comment by GauchetIssaya** [comment]
@andybak agreed 👍

**Comment by zkyf** [comment]
I imported the unitypackage but shows the namespace UnityGLTF cannot be found in script while I can access it by directly adding a component to a game object. 😢

**Comment by sivatejachigicherla** [comment]
@zkyf  clone the project and add package from local disk, this works!!
