### ISSUE TITLE
To record Loading time of glb file

### ISSUE THREAD

**Issue by waseemkhan1989** [KhronosGroup/UnityGLTF#615]
Hi,

I am importing a glb file into my scene as follows:

`            GLTFComponent gltfcomponent = model.AddComponent<GLTFComponent>();
            gltfcomponent.GLTFUri = "https://dummy.com/model.glb";
            gltfcomponent.Multithreaded = true;
            gltfcomponent.UseStream = false;
            gltfcomponent.AppendStreamingAssets = false;
            gltfcomponent.PlayAnimationOnLoad = false;
            var b = gltfcomponent.Collider == GLTFSceneImporter.ColliderType.None;`

To determine the loading efficiency of UnityGLTF, I would like to record how much time it takes:

1.  To downloading a glb file from remote server to a local location(on hard drive on a local computer)

2.  And the time it takes to import glb file from this local location into the scene

I would like to record these timings on Quest(Android).  I would like to know the exact location where I should start and stop the timer. I need it urgent, any help @ousttrue @outofcontrol @aidinabedi .

**Comment by sivatejachigicherla** [comment]
var watch = System.Diagnostics.Stopwatch.StartNew();

// the code that you want to measure comes here
GLTFComponent gltfcomponent = model.AddComponent<GLTFComponent>(); gltfcomponent.GLTFUri = "https://dummy.com/model.glb"; gltfcomponent.Multithreaded = true; gltfcomponent.UseStream = false; gltfcomponent.AppendStreamingAssets = false; gltfcomponent.PlayAnimationOnLoad = false; var b = gltfcomponent.Collider == GLTFSceneImporter.ColliderType.None;

watch.Stop();
var elapsedMs = watch.ElapsedMilliseconds;
