### ISSUE TITLE
png texture much brighter than in microsoft 3d viewer

### ISSUE THREAD

**Issue by tufeixp** [KhronosGroup/UnityGLTF#616]
Looks like unity's texture loader has some issue with such kind of png texture exported by microsoft's DirectXtex tool, the original file is a dds tga file, and exported to this png:
![1010](https://user-images.githubusercontent.com/11953709/99233051-af065800-282d-11eb-861d-09d3a6e7204c.png)

after open and re-save it by another png in photoshop, the texture can be present as original designed:
![1010_reExport](https://user-images.githubusercontent.com/11953709/99233071-b4fc3900-282d-11eb-98d7-34621c39e5bf.png)

Microsoft's own application "Photo" has the same problem as unity does, maybe it's due to the missing value of the sRGB chunk? But we definitely need a fix for such content, 'cause it's everywhere.

Before:
  Offset: 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 	
00000000: 89 50 4E 47 0D 0A 1A 0A 00 00 00 0D 49 48 44 52    .PNG........IHDR
00000010: 00 00 00 0A 00 00 00 0A 08 06 00 00 00 8D 32 CF    ..............2O
00000020: BD 00 00 00 04 67 41 4D 41 00 01 86 A0 31 E8 96    =....gAMA....1h.
00000030: 5F 00 00 00 09 70 48 59 73 00 00 0E C4 00 00 0E    _....pHYs...D...
00000040: C4 01 95 2B 0E 1B 00 00 00 13 74 45 58 74 53 6F    D..+......tEXtSo
00000050: 66 74 77 61 72 65 00 44 69 72 65 63 74 58 54 65    ftware.DirectXTe
00000060: 78 CA 46 F6 97 00 00 00 DF 49 44 41 54 28 53 4D    xJFv...._IDAT(SM
00000070: 50 CB 6E 02 31 0C 9C 38 61 51 A5 4A D5 22 C1 95    PKn.1..8aQ%JU"A.
00000080: 1B 7F 80 C4 A1 87 AA 3F D8 AF E1 CE 47 70 43 5C    ...D!.*?X/aNGpC\
00000090: E1 07 78 2B 9B 74 26 D9 5D 11 2B 8A C7 76 66 6C    a.x+.t&Y].+.Gvfl
000000a0: BB DD CF 32 87 E0 A1 13 63 57 DE 77 EC 1C E0 BD    ;]O2.`!.cW^wl.`=
000000b0: 87 19 BD 94 12 6F 86 7C 06 46 EC 88 75 85 2D E5    ..=..o.|.Fl.u.-e
000000c0: 0C 6F 56 0B E8 AB C0 5B 61 80 11 63 C8 4B 82 70    .oV.h+@[a..cHK.p
000000d0: 3C 92 CA 34 89 1F EF 1D 6E B5 9B 41 9A A9 5E 5A    <.J4..o.n5.A.)^Z
000000e0: 46 6A 5C 62 C2 67 20 93 E0 28 ED 0D AE 48 33 40    Fj\bBg..`(m..H3@
000000f0: B6 C5 47 C0 8B 32 87 6B C4 FE 12 EB 30 45 8A 0C    6EG@.2.kD~.k0E..
00000100: D2 0F 04 27 56 AC B6 67 34 FC F8 3B 6B B0 F9 9A    R..'V,6g4|x;k0y.
00000110: 54 46 76 55 7A 92 25 FA F3 C6 F0 B7 6E 31 25 C1    TFvUz.%zsFp7n1%A
00000120: 93 9F 23 FB 13 0F 07 63 35 A7 2A 6B 90 CF 56 BE    ..#{...c5'*k.OV>
00000130: DB 86 93 D6 B5 48 4D AD 51 BA 0F B0 40 BE C6 7E    [..V5HM-Q:.0@>F~
00000140: 74 DC 63 8F 6B 3E E1 1F 9D 41 7D 38 7C 80 10 AA    t\c.k>a..A}8|..*
00000150: 00 00 00 00 49 45 4E 44 AE 42 60 82                ....IEND.B`.

After:
  Offset: 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 	
00000000: 89 50 4E 47 0D 0A 1A 0A 00 00 00 0D 49 48 44 52    .PNG........IHDR
00000010: 00 00 00 0A 00 00 00 0A 08 02 00 00 00 02 50 58    ..............PX
00000020: EA 00 00 00 09 70 48 59 73 00 00 0E C4 00 00 0E    j....pHYs...D...
00000030: C4 01 95 2B 0E 1B 00 00 05 F1 69 54 58 74 58 4D    D..+.....qiTXtXM
00000040: 4C 3A 63 6F 6D 2E 61 64 6F 62 65 2E 78 6D 70 00    L:com.adobe.xmp.
00000050: 00 00 00 00 3C 3F 78 70 61 63 6B 65 74 20 62 65    ....<?xpacket.be
00000060: 67 69 6E 3D 22 EF BB BF 22 20 69 64 3D 22 57 35    gin="o;?".id="W5
00000070: 4D 30 4D 70 43 65 68 69 48 7A 72 65 53 7A 4E 54    M0MpCehiHzreSzNT
00000080: 63 7A 6B 63 39 64 22 3F 3E 20 3C 78 3A 78 6D 70    czkc9d"?>.<x:xmp
00000090: 6D 65 74 61 20 78 6D 6C 6E 73 3A 78 3D 22 61 64    meta.xmlns:x="ad
000000a0: 6F 62 65 3A 6E 73 3A 6D 65 74 61 2F 22 20 78 3A    obe:ns:meta/".x:
000000b0: 78 6D 70 74 6B 3D 22 41 64 6F 62 65 20 58 4D 50    xmptk="Adobe.XMP
000000c0: 20 43 6F 72 65 20 35 2E 36 2D 63 31 34 38 20 37    .Core.5.6-c148.7
000000d0: 39 2E 31 36 34 30 33 36 2C 20 32 30 31 39 2F 30    9.164036,.2019/0
000000e0: 38 2F 31 33 2D 30 31 3A 30 36 3A 35 37 20 20 20    8/13-01:06:57...
000000f0: 20 20 20 20 20 22 3E 20 3C 72 64 66 3A 52 44 46    .....">.<rdf:RDF
00000100: 20 78 6D 6C 6E 73 3A 72 64 66 3D 22 68 74 74 70    .xmlns:rdf="http
00000110: 3A 2F 2F 77 77 77 2E 77 33 2E 6F 72 67 2F 31 39    ://www.w3.org/19
00000120: 39 39 2F 30 32 2F 32 32 2D 72 64 66 2D 73 79 6E    99/02/22-rdf-syn
00000130: 74 61 78 2D 6E 73 23 22 3E 20 3C 72 64 66 3A 44    tax-ns#">.<rdf:D
00000140: 65 73 63 72 69 70 74 69 6F 6E 20 72 64 66 3A 61    escription.rdf:a
00000150: 62 6F 75 74 3D 22 22 20 78 6D 6C 6E 73 3A 78 6D    bout="".xmlns:xm
00000160: 70 3D 22 68 74 74 70 3A 2F 2F 6E 73 2E 61 64 6F    p="http://ns.ado
00000170: 62 65 2E 63 6F 6D 2F 78 61 70 2F 31 2E 30 2F 22    be.com/xap/1.0/"
00000180: 20 78 6D 6C 6E 73 3A 64 63 3D 22 68 74 74 70 3A    .xmlns:dc="http:
00000190: 2F 2F 70 75 72 6C 2E 6F 72 67 2F 64 63 2F 65 6C    //purl.org/dc/el
000001a0: 65 6D 65 6E 74 73 2F 31 2E 31 2F 22 20 78 6D 6C    ements/1.1/".xml
000001b0: 6E 73 3A 70 68 6F 74 6F 73 68 6F 70 3D 22 68 74    ns:photoshop="ht
000001c0: 74 70 3A 2F 2F 6E 73 2E 61 64 6F 62 65 2E 63 6F    tp://ns.adobe.co
000001d0: 6D 2F 70 68 6F 74 6F 73 68 6F 70 2F 31 2E 30 2F    m/photoshop/1.0/
000001e0: 22 20 78 6D 6C 6E 73 3A 78 6D 70 4D 4D 3D 22 68    ".xmlns:xmpMM="h
000001f0: 74 74 70 3A 2F 2F 6E 73 2E 61 64 6F 62 65 2E 63    ttp://ns.adobe.c
00000200: 6F 6D 2F 78 61 70 2F 31 2E 30 2F 6D 6D 2F 22 20    om/xap/1.0/mm/".
00000210: 78 6D 6C 6E 73 3A 73 74 45 76 74 3D 22 68 74 74    xmlns:stEvt="htt
00000220: 70 3A 2F 2F 6E 73 2E 61 64 6F 62 65 2E 63 6F 6D    p://ns.adobe.com
00000230: 2F 78 61 70 2F 31 2E 30 2F 73 54 79 70 65 2F 52    /xap/1.0/sType/R
00000240: 65 73 6F 75 72 63 65 45 76 65 6E 74 23 22 20 78    esourceEvent#".x
00000250: 6D 70 3A 43 72 65 61 74 6F 72 54 6F 6F 6C 3D 22    mp:CreatorTool="
00000260: 41 64 6F 62 65 20 50 68 6F 74 6F 73 68 6F 70 20    Adobe.Photoshop.
00000270: 32 31 2E 31 20 28 57 69 6E 64 6F 77 73 29 22 20    21.1.(Windows)".
00000280: 78 6D 70 3A 43 72 65 61 74 65 44 61 74 65 3D 22    xmp:CreateDate="
00000290: 32 30 32 30 2D 31 31 2D 31 36 54 31 36 3A 34 38    2020-11-16T16:48
000002a0: 3A 32 36 2B 30 38 3A 30 30 22 20 78 6D 70 3A 4D    :26+08:00".xmp:M
000002b0: 6F 64 69 66 79 44 61 74 65 3D 22 32 30 32 30 2D    odifyDate="2020-
000002c0: 31 31 2D 31 36 54 31 36 3A 34 39 3A 30 38 2B 30    11-16T16:49:08+0
000002d0: 38 3A 30 30 22 20 78 6D 70 3A 4D 65 74 61 64 61    8:00".xmp:Metada
000002e0: 74 61 44 61 74 65 3D 22 32 30 32 30 2D 31 31 2D    taDate="2020-11-
000002f0: 31 36 54 31 36 3A 34 39 3A 30 38 2B 30 38 3A 30    16T16:49:08+08:0
00000300: 30 22 20 64 63 3A 66 6F 72 6D 61 74 3D 22 69 6D    0".dc:format="im
00000310: 61 67 65 2F 70 6E 67 22 20 70 68 6F 74 6F 73 68    age/png".photosh
00000320: 6F 70 3A 43 6F 6C 6F 72 4D 6F 64 65 3D 22 33 22    op:ColorMode="3"
00000330: 20 70 68 6F 74 6F 73 68 6F 70 3A 49 43 43 50 72    .photoshop:ICCPr
00000340: 6F 66 69 6C 65 3D 22 73 52 47 42 20 49 45 43 36    ofile="sRGB.IEC6
00000350: 31 39 36 36 2D 32 2E 31 22 20 78 6D 70 4D 4D 3A    1966-2.1".xmpMM:
00000360: 49 6E 73 74 61 6E 63 65 49 44 3D 22 78 6D 70 2E    InstanceID="xmp.
00000370: 69 69 64 3A 61 39 30 61 62 35 34 32 2D 30 30 39    iid:a90ab542-009
00000380: 63 2D 66 36 34 37 2D 38 66 66 34 2D 39 37 64 30    c-f647-8ff4-97d0
00000390: 37 63 36 62 66 32 64 39 22 20 78 6D 70 4D 4D 3A    7c6bf2d9".xmpMM:
000003a0: 44 6F 63 75 6D 65 6E 74 49 44 3D 22 61 64 6F 62    DocumentID="adob
000003b0: 65 3A 64 6F 63 69 64 3A 70 68 6F 74 6F 73 68 6F    e:docid:photosho
000003c0: 70 3A 34 65 36 64 62 33 63 39 2D 38 66 62 37 2D    p:4e6db3c9-8fb7-
000003d0: 65 39 34 36 2D 38 62 32 61 2D 39 31 38 35 37 33    e946-8b2a-918573
000003e0: 36 34 37 36 63 64 22 20 78 6D 70 4D 4D 3A 4F 72    6476cd".xmpMM:Or
000003f0: 69 67 69 6E 61 6C 44 6F 63 75 6D 65 6E 74 49 44    iginalDocumentID
00000400: 3D 22 78 6D 70 2E 64 69 64 3A 65 66 34 63 62 38    ="xmp.did:ef4cb8
00000410: 30 62 2D 63 32 39 64 2D 39 37 34 63 2D 62 64 35    0b-c29d-974c-bd5
00000420: 64 2D 37 35 64 31 61 33 30 34 36 38 38 37 22 3E    d-75d1a3046887">
00000430: 20 3C 78 6D 70 4D 4D 3A 48 69 73 74 6F 72 79 3E    .<xmpMM:History>
00000440: 20 3C 72 64 66 3A 53 65 71 3E 20 3C 72 64 66 3A    .<rdf:Seq>.<rdf:
00000450: 6C 69 20 73 74 45 76 74 3A 61 63 74 69 6F 6E 3D    li.stEvt:action=
00000460: 22 63 72 65 61 74 65 64 22 20 73 74 45 76 74 3A    "created".stEvt:
00000470: 69 6E 73 74 61 6E 63 65 49 44 3D 22 78 6D 70 2E    instanceID="xmp.
00000480: 69 69 64 3A 65 66 34 63 62 38 30 62 2D 63 32 39    iid:ef4cb80b-c29
00000490: 64 2D 39 37 34 63 2D 62 64 35 64 2D 37 35 64 31    d-974c-bd5d-75d1
000004a0: 61 33 30 34 36 38 38 37 22 20 73 74 45 76 74 3A    a3046887".stEvt:
000004b0: 77 68 65 6E 3D 22 32 30 32 30 2D 31 31 2D 31 36    when="2020-11-16
000004c0: 54 31 36 3A 34 38 3A 32 36 2B 30 38 3A 30 30 22    T16:48:26+08:00"
000004d0: 20 73 74 45 76 74 3A 73 6F 66 74 77 61 72 65 41    .stEvt:softwareA
000004e0: 67 65 6E 74 3D 22 41 64 6F 62 65 20 50 68 6F 74    gent="Adobe.Phot
000004f0: 6F 73 68 6F 70 20 32 31 2E 31 20 28 57 69 6E 64    oshop.21.1.(Wind
00000500: 6F 77 73 29 22 2F 3E 20 3C 72 64 66 3A 6C 69 20    ows)"/>.<rdf:li.
00000510: 73 74 45 76 74 3A 61 63 74 69 6F 6E 3D 22 73 61    stEvt:action="sa
00000520: 76 65 64 22 20 73 74 45 76 74 3A 69 6E 73 74 61    ved".stEvt:insta
00000530: 6E 63 65 49 44 3D 22 78 6D 70 2E 69 69 64 3A 61    nceID="xmp.iid:a
00000540: 39 30 61 62 35 34 32 2D 30 30 39 63 2D 66 36 34    90ab542-009c-f64
00000550: 37 2D 38 66 66 34 2D 39 37 64 30 37 63 36 62 66    7-8ff4-97d07c6bf
00000560: 32 64 39 22 20 73 74 45 76 74 3A 77 68 65 6E 3D    2d9".stEvt:when=
00000570: 22 32 30 32 30 2D 31 31 2D 31 36 54 31 36 3A 34    "2020-11-16T16:4
00000580: 39 3A 30 38 2B 30 38 3A 30 30 22 20 73 74 45 76    9:08+08:00".stEv
00000590: 74 3A 73 6F 66 74 77 61 72 65 41 67 65 6E 74 3D    t:softwareAgent=
000005a0: 22 41 64 6F 62 65 20 50 68 6F 74 6F 73 68 6F 70    "Adobe.Photoshop
000005b0: 20 32 31 2E 31 20 28 57 69 6E 64 6F 77 73 29 22    .21.1.(Windows)"
000005c0: 20 73 74 45 76 74 3A 63 68 61 6E 67 65 64 3D 22    .stEvt:changed="
000005d0: 2F 22 2F 3E 20 3C 2F 72 64 66 3A 53 65 71 3E 20    /"/>.</rdf:Seq>.
000005e0: 3C 2F 78 6D 70 4D 4D 3A 48 69 73 74 6F 72 79 3E    </xmpMM:History>
000005f0: 20 3C 2F 72 64 66 3A 44 65 73 63 72 69 70 74 69    .</rdf:Descripti
00000600: 6F 6E 3E 20 3C 2F 72 64 66 3A 52 44 46 3E 20 3C    on>.</rdf:RDF>.<
00000610: 2F 78 3A 78 6D 70 6D 65 74 61 3E 20 3C 3F 78 70    /x:xmpmeta>.<?xp
00000620: 61 63 6B 65 74 20 65 6E 64 3D 22 72 22 3F 3E CE    acket.end="r"?>N
00000630: 77 9B 24 00 00 00 B8 49 44 41 54 18 95 45 8F 3D    w.$...8IDAT..E.=
00000640: 4A 04 61 14 04 AB FB 7D 8E 08 82 AC A0 A9 99 37    J.a..+{}...,.).7
00000650: 10 0C 0C C4 0B 7A 1A 73 0F 61 26 A6 7A 81 5D 7F    ...D.z.s.a&&z.].
00000660: 96 99 D7 06 B3 68 47 45 05 05 AD E7 FB AB 31 0A    ..W.3hGE..-g{+1.
00000670: 98 E7 05 F8 63 89 AA 1A 96 BA 1B 64 09 B1 B2 24    .g.xc.*..:.d.12$
00000680: 89 EE 76 27 65 DB EA A4 3B E5 B2 E5 84 D5 03 E1    .nv'e[j$;e2e.U.a
00000690: 30 89 90 82 B7 AF E5 73 01 58 E3 11 58 02 E8 6C    0...7/es.Xc.X.hl
000006a0: 3B A7 C3 FE 8F 97 65 75 DA E4 F2 64 EC C3 EB 6E    ;'C~..euZdrdlCkn
000006b0: 7E D9 CE 55 65 89 74 08 43 7A DF E7 FA E9 63 B2    ~YNUe.t.Cz_gzic2
000006c0: 1E CE A7 DB B3 A3 EE 1E A0 10 20 E8 62 D2 E3 CD    .N'[3#n....hbRcM
000006d0: E6 58 FC 04 04 C1 49 DB 96 D4 69 27 77 9B A9 AC    fX|..AI[.Ti'w.),
000006e0: EE 4E A7 CA 43 87 DF 48 02 7D 2F 07 5E FD 2F 1C    nN'JC._H.}/.^}/.
000006f0: AA 69 5D 84 20 45 C0 00 00 00 00 49 45 4E 44 AE    *i]..E@....IEND.
00000700: 42 60 82                                           B`.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
