### ISSUE TITLE
erros after compile GLTFSerialization.sln

### ISSUE THREAD

**Issue by marck0zz** [KhronosGroup/UnityGLTF#618]
Hello!!

I think I following all the steps correctly but I alway gave the same errors after compile the GLTFSerialization.sln.

1.- Clone the rep.
2.- Add and open the UnityGLTF proyect.
3.- Close the project.
4.- Build the GLTFSerialization.sln:
![Build](https://user-images.githubusercontent.com/11354912/100918182-c7b57580-349d-11eb-903b-46821443092d.png)
5.- The "Plugin" file is created.
6.- Open the UnityGLTF proyect and the error comes on.
![Errors](https://user-images.githubusercontent.com/11354912/100918477-237ffe80-349e-11eb-8c50-155c02a7cae5.png)

Variation:

- I'm copy and pasting the original rep and changing the name to "UnityGLTF_Modified00" for version tracking. I'm not think this should be a problem.
- I'm upgrading the unity project to 2019.4.15ver. Could this be the problem?
- I'm changing the original ".NET Framework 4.6." to ".NET Framework 4.6.1". Could this be the problem?

What I'm missing? Please help.

Thank you in advance!!

**Comment by paul-bonnel-fr** [comment]
Same issue

**Comment by bielkinv** [comment]
Same issue

**Comment by goldv72** [comment]
Same issue

**Comment by YeonduBori** [comment]
Didn't you change GLTFSerialization.dll platform?
Try this
In plugin net 3.xx must except UWP, and dll in UWP only include UWP ,except all platform

**Comment by sivatejachigicherla** [comment]
Delete multiple copies of dll's

**Comment by oleksa-oleksa** [comment]
2.- Add and open the UnityGLTF proyect. 
3.- Close the project. 
4.- Build the GLTFSerialization.sln: 

I want just gave a hint that I had exactly the same problems as you and after I have opened Unity project and closed it before build it, the errors are gone. I have still Oculus missing but I can go into play mode.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
