### ISSUE TITLE
Multiple precompiled assemblies

### ISSUE THREAD

**Issue by mohsen123** [KhronosGroup/UnityGLTF#620]
Hey, I get this error after building GLTFSerialization.sln

> PrecompiledAssemblyException: Multiple precompiled assemblies with the same name GLTFSerialization.dll included or the current platform. Only one assembly with the same name is allowed per platform. Assembly paths: 
Assets/UnityGLTF/Runtime/Plugins/net35/GLTFSerialization.dll

the error is for GLTFSerialization.dll and Newtonsoft.Json.dll and unity Cant load scripts.

I know it related to:
`Open the Unity project located in UnityGLTF\.
If the meta file gets overridden, the binaries in UnityGLTF\Assets\UnityGLTF\Runtime\Plugins should be configured for everything but UWP. The binaries in UnityGLTF\Assets\UnityGLTF\Runtime\Plugins\UWP should be configured for UWP.`
but How should I exactly deal with them? if I want to use the plugin for windows, 

thanks

**Comment by mohsen123** [comment]
![error](https://user-images.githubusercontent.com/5547808/105630111-57ebb780-5e5c-11eb-974f-5f4b82917e23.jpg)

any solution?

**Comment by bobbyntigers64** [comment]
Did you ever solve this? I'm having the same problem

**Comment by mohsen123** [comment]
> Did you ever solve this? I'm having the same problem

Yes, but forget how exactly, have you changed and applied all "asmdef" files in unity? I think that was a reason.

**Comment by bobbyntigers64** [comment]
What do you mean change and apply the asmdef files? How do I do that?

Thanks for the reply!

**Comment by mohsen123** [comment]
https://github.com/KhronosGroup/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/Editor/UnityGLTFEditor.asmdef
https://github.com/KhronosGroup/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/Runtime/UnityGLTFScripts.asmdef

these files probably should have a UI in unity,

**Comment by sivatejachigicherla** [comment]
Delete multiple copies of dll's

**Comment by vector-8** [comment]
There are no multiple copies of dll's, but error still occurs. In my cases it's  **Newtonsoft.Json.dll** .

**Comment by hybridherbst** [comment]
Should be fixed on dev and in this PR
- https://github.com/KhronosGroup/UnityGLTF/pull/644
