### ISSUE TITLE
Unity Crash VS2019 / Unity 2019.4.17f1

### ISSUE THREAD

**Issue by A5005** [KhronosGroup/UnityGLTF#621]
Totally impossible to load this project with VS2019 and Unity 2019.4.17f1. Or did anyone manage it?

![crash](https://user-images.githubusercontent.com/44929101/107403956-030b9a80-6b06-11eb-988c-c3cc5453a849.png)

**Comment by ponahoum** [comment]
I'm using 2019.4.17f with the master branch and it works correctly. You have to compile the .sln project and import it into Unity.

**Comment by FaruNuriSonmez** [comment]
> I'm using 2019.4.17f with the master branch and it works correctly. You have to compile the .sln project and import the compiled dlls into Unity.

_Can I use it for version 2020.2.2f1? have you tried before ?_ @ponahoum

**Comment by ponahoum** [comment]
@FaruNuriSonmez haven't tried, but I see no reason why I shouldn't work.

**Comment by sivatejachigicherla** [comment]
@FaruNuriSonmez  yes you can use it with 2020.2.2f1. I'm currently using for export & import both work seamlessly.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
