### ISSUE TITLE
too long loading time

### ISSUE THREAD

**Issue by cszn113** [KhronosGroup/UnityGLTF#622]
I'm new to unity3D. However, when I'm trying to load a building model which has about 130 gltf files, it costs more than 20 minutes on android. Is there any solution for loading many files? Thanks.

**Comment by sivatejachigicherla** [comment]
Optimize the materials and textures of the gltf models, try using multi threading, also make use of GPU, as most of the smartphones comes with GPUs.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
