### ISSUE TITLE
Unity Getting Crash after compiled and generated .dll files from GLTSerialisation on visual studio.

### ISSUE THREAD

**Issue by pradeep-recinfo** [KhronosGroup/UnityGLTF#623]
Hello,
My requirements in short. 
1. I need to upload an IFC building file from mobile in our unity application. 
2. Need to convert it to .GLB format.
3. Need to upload/Download the .GLB models  from AWS server based on user stored models. 
These are my requirements, to achieve this i have gone through some tutorial stated that, we need to convert the .GLB to .GLTF format which gives in lesser size.  For that i am trying this plugin which is throwing compile time error.
Once i have compiled the serialization project on visual studio. My Unity started crashing. Please suggest me any workaround how i can achieve my requirement.

**Comment by sivatejachigicherla** [comment]
Build the project in Visual Studio and go to bin folder in Debug/Release, copy the dll's to plugins folder in Unity project. This solves the crash issue, but if you need to convert from glb to gltf there are other converts available on the internet, which can be easily integrated into AWS

**Comment by hybridherbst** [comment]
Should also be fixed on dev / this PR:
- https://github.com/KhronosGroup/UnityGLTF/pull/644

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
