### ISSUE TITLE
Major memory issue : GLB/GLTF export duplicates vertices when the exported mesh has multiple submeshes

### ISSUE THREAD

**Issue by ponahoum** [KhronosGroup/UnityGLTF#624]
Hi everyone,

It seems that the exporter duplicates the vertices times the number of submeshes.

Let say I export a mesh with 10 materials (so the mesh has 10 submesh), 3 000 000 vertices, 1 000 000 triangles.
The actual exported GLB/GLTF file will contain  3 000 000 * 10 = 30 000 000 vertices, for a maintained amount of 1 000 000 triangles.

Anyone has experienced a similar issue?

**Comment by alexmeister92** [comment]
Hi, 
I have the same problem. Every time I Export a GLB, the size of the exported file is grater than before (without changing anything).

After some tests I noticed that a GLB file with 102 Accessors and 2 BufferViews exported and reimported will have 92 Accessprs amd 92 BufferViews. Then if you do it again it will have 249 Acessors and 249 BufferViews. Then it will not grow anymore (in terms of number of Accessors and BufferViews) while the size of the file will always increase exponentially. Its size starts with 1796KB, then after the first export is 1807 KB, then 3944KB, then 7183KB and so on.

Do uyou have any ideas?

**Comment by pfcDorn** [comment]
Fixed in latest release
