### ISSUE TITLE
Failing to deserialize sparse accessors

### ISSUE THREAD

**Issue by jeoungjukim** [KhronosGroup/UnityGLTF#628]
Good morning.
I am an employee of the Graphic Development Group of Samsung Electronics Mobile Business Unit. I have a problem while building an app using the UnityGltfImporter distributed by Khronos. SparewAccssor not working.
The issue is confirmed to be the same: https://github.com/KhronosGroup/UnityGLTF/issues/587
If you need, i can share our Gltf model.
Any plans to fix this officially?
It works with other renderers distributed by Khronos. Only Unity GltfImporter throws the error.
help anyone...

**Comment by pfcDorn** [comment]
Fixed in latest release
