### ISSUE TITLE
Update glTF specific shader

### ISSUE THREAD

**Issue by sbtron** [KhronosGroup/UnityGLTF#63]
Current one doesn't work on Android and was stripped out.
Need to figure out a better solution.

**Comment by AurL** [comment]
@sbtron I wonder what's the purpose of using a specific glTF shader instead of the Unity's Standard one ?
The only reason I have in mind is that it doesn't require any image processing (unpacking/repacking)
I guess it could fix this issue ?

**Comment by bghgary** [comment]
> doesn't require any image processing (unpacking/repacking)

It's more than that. Unity doesn't multiply the colors against the texture where as glTF does. Unity doesn't support texture coordinate sets where as glTF does. I think we need to think about supporting both.

**Comment by AurL** [comment]
Ok thanks @bghgary . +1 for the texture coordinate sets (but colors are multiplied against texture if I'm right).
Anyway, yes it would makes sense to support both 👍

**Comment by bghgary** [comment]
> colors are multiplied against texture if I'm right

Sorry, yeah, it is multiplied if there is a color in addition to texture, but some properties don't behave this way. For example, metallic factor in glTF is not representable in Unity's standard material if metallic texture is also specified. Another example is for the spec-gloss extension where Unity expects only one of specular color or texture but not both.

**Comment by stevenvergenz** [comment]
This is done.
