### ISSUE TITLE
Can i select GLB format when export scene ?

### ISSUE THREAD

**Issue by pxim** [KhronosGroup/UnityGLTF#631]
![image](https://user-images.githubusercontent.com/5111701/127426721-42cbb1dc-287d-4db1-ad03-d63a2d7b2537.png)
![image](https://user-images.githubusercontent.com/5111701/127426843-8a2125f0-fadd-4478-be28-c9df0e128828.png)

The default file of the exported scene is gltf, bin and  Assets . 
Can i select the GLB format, export only one GLB file .
Like `ExportGLB Selected` .

**Comment by pfcDorn** [comment]
Fixed in latest release
