### ISSUE TITLE
The animation is not export when exportGLB Selected !

### ISSUE THREAD

**Issue by pxim** [KhronosGroup/UnityGLTF#632]
The FBX with animation can be imported into Unity, 
but when the GLB is exported, the animation is not export.

This is the unity example .
https://drive.google.com/file/d/1AY6DyfkfVoEKOQciKTLlAb00jAPJMIvy/view?usp=sharing

**Comment by hybridherbst** [comment]
The dev branch / this PR greatly improve animation export:

- https://github.com/KhronosGroup/UnityGLTF/pull/644

Would be great if you test that out, thanks!
