### ISSUE TITLE
Namespace Cound not be found

### ISSUE THREAD

**Issue by CooperLiumz** [KhronosGroup/UnityGLTF#633]
I Build the project in Visual Studio and the Plugins had been created in unity.
Then PrecompiledAssemblyException happend
![image](https://user-images.githubusercontent.com/67528045/130037575-e5d35b28-2ffd-4573-8afd-ab8a9b24159b.png)
![image](https://user-images.githubusercontent.com/67528045/130037710-c5db2552-cdd5-48fd-b0a3-1b66a6d38936.png)

so I delete fold uap10.0.10586, but othe namaspace cound not found happen

![image](https://user-images.githubusercontent.com/67528045/130037986-e268ebe5-0984-485b-a91d-763545c63e57.png)

visual studio version Microsoft Visual Studio Enterprise 2019 版本 16.10.3
unity version 2019.4.2.f1

**Comment by megha-sen** [comment]
I am also getting errors while adding this project to the asset. Any solution for the following error?
![ErrorGLTF](https://user-images.githubusercontent.com/25484816/133961658-215371aa-1e89-4ee0-98c3-95dfe758b27c.PNG)
s

**Comment by klauskobald** [comment]
same on 2020.3
is this project dead?

**Comment by hybridherbst** [comment]
The visual studio plugin has been merged into the Unity project on the dev branch / this PR:

- https://github.com/KhronosGroup/UnityGLTF/pull/644

Would be great if you test that out, it should fix this issue.
