### ISSUE TITLE
GLB import / export has issues

### ISSUE THREAD

**Issue by havarsa** [KhronosGroup/UnityGLTF#634]
I am experiencing multiple problems with the UnityGLTF component. It is very unfortunate, as we would benefit greatly from having proper GLTF support in our project.

One of the major issues is importing / exporting to GLB. Importing a GLB from Sketchfab, ie, works just fine, and it imports impressive models with no issues. However, creating a few 3D objects in Unity and exporting and then reimporting does reveal issues!

Try this;

1. Create a cube on root. Create a sub object for this cube, say a cylinder. And again, for this cylinder, add a sub object capsule.
You have this object now:
![image](https://user-images.githubusercontent.com/26650492/133069662-669296d7-e65b-4a46-b93f-c97d7538fc00.png)

2. Now; export to GLB using 'GLTF -> ExportGLB Selected'

3. Import it back in. Several problems occur:
      a. Imported object looks like this:
![image](https://user-images.githubusercontent.com/26650492/133069834-ba04e243-4f9e-4bf3-bfbd-b812e5d11110.png)
     The capsule node is lost, but the capsule mesh has merged with the cylinder mesh, and is placed on the cylinder node. This completely messes up the structure of objects.

   b. Additionally, most but not all times I get this exception thrown: 
![image](https://user-images.githubusercontent.com/26650492/133070386-0fb71d2e-ba0d-42bb-b9b3-df4bb931b061.png)
(this example is from a different different test object)

Anyone else experience this?

**Comment by hybridherbst** [comment]
Would be great if you try out the dev branch / this PR, which greatly improves export:

- https://github.com/KhronosGroup/UnityGLTF/pull/644

Thanks!
