### ISSUE TITLE
Is Linux supported?

### ISSUE THREAD

**Issue by farshid2** [KhronosGroup/UnityGLTF#636]
Hi,
I've just installed Unity on a Linux machine  and wanted to ask you how to import assets in .gltf/.glb formats (to Unity under Linux)? 
Many thanks

**Comment by hybridherbst** [comment]
Would you mind trying out the dev branch / this PR?

- https://github.com/KhronosGroup/UnityGLTF/pull/644

There have been changes to improve cross-platform support which should fix Linux as well if I'm not mistaken.

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
