### ISSUE TITLE
WebGL build Libc dll error

### ISSUE THREAD

**Issue by handrianj** [KhronosGroup/UnityGLTF#637]
Has anyone managed to make a webgl build working ? 

I'm on unity 2021.1.24fc1 and whenever I do a WebGL build with the test scenes I end up with the following error:

"Unable to open DLL libc! Dynamic linking is not supported in WebAssembly builds due to limitations to performance and code size. Please statically link in the needed libraries."

Can anyone point me at the steps to solve this error please ?

**Comment by hybridherbst** [comment]
Would be great if you give the dev branch / this PR a try for better WebGL support:

- https://github.com/KhronosGroup/UnityGLTF/pull/644

**Comment by CaizhongQiang** [comment]
Excuse me, how to solve this problem?

**Comment by hybridherbst** [comment]
Please try the dev branch! WebGL works fine as far as I'm aware (both import and export).

**Comment by handrianj** [comment]
> Would be great if you give the dev branch / this PR a try for better WebGL support:
> 
>     * [Culmination of two years of fixes, especially for export #644](https://github.com/KhronosGroup/UnityGLTF/pull/644)

Sorry, I totally forgot about testing that, I'll have a look and let you know!
