### ISSUE TITLE
Misaligned Normal Maps after .glb-export

### ISSUE THREAD

**Issue by Kredithaichen** [KhronosGroup/UnityGLTF#639]
### What happened? 
After exporting a .fbx-file from Unity using UnityGLTF via the ExportGLB selected button the resulting .glb file had its normal maps all misaligned. The diffuse maps were all perfectly right and looked like expected. The alignment issue only extends to the normal maps. It seems like they are flipped along one axis. 

I verified the issue in Babylonjs sandbox and Gestaltor respectively and both show the normal maps incorrectly, so the problem occurs at some point during export. 
It appears that the problem is fixed auto-magically by applying the gltf-transform CLI, so it might be a sanitizing step that fails. 

### What did I do?
- I imported an FBX-file into Unity 
    - with the UnityGLTF-package, 
    - as well as the UniversalRP-package installed.  
- I extracted the textures via the .fbx-importer
    - placed them in a folder named 'Textures' right in the Assets-folder
- I selected the .fbx-file in the scene hierarchy
- I hit 'ExportGLB selected' 
    - under the GLTF-tab in the toolbar
- later I imported the .glb at runtime, that's when I noticed the problem, but as pointed out, the problem was verified in external, independent tools. 

### What did I expect to happen?
I expected the exported .glb-file to have the same material data as the scene object I exported. 

### Attachments
The resulting .glb-file: [Link to Google Drive](https://drive.google.com/file/d/14pNyublVt-KLXWxJPnhQu6zPusbqoN3Z/view?usp=sharing)
A minimal example project to reproduce the project: [Link to Google Drive](https://drive.google.com/drive/folders/1tWZesiuSa4RxjC9Iep86EMLDOF4j-z0I?usp=sharing)
#### Screenshots:
![UnityUnlit](https://user-images.githubusercontent.com/31171070/142616156-6076ff36-d456-4c40-b616-61da1e0dbd00.png)
![BabylonJS](https://user-images.githubusercontent.com/31171070/142616158-d4fa4c40-2918-4ab7-9385-f250d0f8fafa.png)
![Gestaltor](https://user-images.githubusercontent.com/31171070/142616160-3d853cae-80da-4c37-bd91-fcb47a07ce41.png)
![UnityNormalMaps](https://user-images.githubusercontent.com/31171070/142616161-5ea10f52-00e2-4d81-8b5b-31e31371cb45.png)
![UnityLit](https://user-images.githubusercontent.com/31171070/142616165-39767f3c-3a86-46d8-9fb4-f97fbf3e793c.png)

**Comment by hybridherbst** [comment]
Should be fixed in the prefrontal cortex fork (and this PR: https://github.com/KhronosGroup/UnityGLTF/pull/644)
