### ISSUE TITLE
Setup Travis build

### ISSUE THREAD

**Issue by sbtron** [KhronosGroup/UnityGLTF#64]
Work item to track turning on travis build

**Comment by Vytek** [comment]
WARNING!

Please read: https://github.com/KhronosGroup/UnityGLTF/pull/145#issuecomment-372065711

**Comment by sbtron** [comment]
apologies got over aggressive with closing things....

**Comment by blgrossMS** [comment]
Thank you @Vytek . We have builds now and they are deploying to the releases section.
