### ISSUE TITLE
Question, why has the development halted in this repo?

### ISSUE THREAD

**Issue by ItsCubeTime** [KhronosGroup/UnityGLTF#640]
Is it unmaintained or is there simply no reason for updates?

**Comment by yosun** [comment]
really good question

**Comment by wolfyllow** [comment]
In case you are still looking for more active projects for GLTF integration in Unity, these two seem quite interesting: [glTFast](https://github.com/atteneder/glTFast) and [GLTFUtility](https://github.com/Siccity/GLTFUtility)

**Comment by hybridherbst** [comment]
There's also an active fork, https://github.com/prefrontalcortex/UnityGLTF, which will be PR'd into this repository here at some point to at least bring it back into shape and make sure other people benefit from the fixes we did.

**Comment by hybridherbst** [comment]
Update: PR has now been made. If you care about this repo it would be great if you check that –
- https://github.com/KhronosGroup/UnityGLTF/pull/644

Thanks!
