### ISSUE TITLE
Is it possible to export GLTF in WebGL runetime ?

### ISSUE THREAD

**Issue by OctocatPower** [KhronosGroup/UnityGLTF#641]
Hi,
I am actually trying to export a GLTF from WebGL build.
When i try it, i got this error : Could not find a part of the path

I find that there is no access to the file system for security reasons. So, i got this error. Solution is to use WWW class to download the file before being able to parse it. But is it possible to aply this ? Important sripts are in a dll so i can't see what is doing in this ...

**Comment by hybridherbst** [comment]
It's possible with this PR which will be merged in 1-2 weeks unless there's concerns:
- https://github.com/KhronosGroup/UnityGLTF/pull/644
Would be great if you test that out.

**Comment by Vaigo** [comment]
Hi @OctocatPower, Did you find any solution regarding the same issue.?

**Comment by OctocatPower** [comment]
Hi @Vaigo, sadly, i don't got the answer ...
On my web server, i got the error.
But on the client web server, I don't got this error ...
Think it's about web server managment but don't know exactly where.
If it help, I personnaly used "SaveGLBToByteArray" function.

**Comment by hybridherbst** [comment]
Can you please test from this fork which will be merged back here soon:
https://github.com/KhronosGroup/UnityGLTF/issues/641#issuecomment-1092640475

**Comment by Vaigo** [comment]
@hybridherbst, for that, do I need to Checkout the full repo first? or i can check out only the PR branch? please guide me, I am new to this.

**Comment by Vaigo** [comment]
Hi @hybridherbst,  Which method i need to use to export the Gameobject in webgl?
