### ISSUE TITLE
Compiler issues in Unity 2020.3.25f1

### ISSUE THREAD

**Issue by 2-3-5-41** [KhronosGroup/UnityGLTF#642]
# Errors from unity package.

When importing the unitypackage provided in the builds into Unity 2020.3.25f1 LTS, there are compiler errors complaining about multiple precompiled assemblies in the project, these are coming from the two Newtonsoft.json assemblies, one provided in the package, and one provided by unity by default in the package manager.

![image](https://user-images.githubusercontent.com/93025618/154832395-76901bb2-c9c1-4dcc-83da-b3816a7296fc.png)

### Post removal of extra Newtonsoft.json.dll

![image](https://user-images.githubusercontent.com/93025618/154832407-79af1f1e-cfab-4119-ab7c-ea7b7c63fdda.png)

----

# Errors from repo project file.

I've also downloaded the repo and tried opening the "UnityGLTF" project file with Unity 2020.3.25f1 LTS, and was prompted to load in safe mode, upon doing so, I'm presented with numerous compiler errors pertaining to cache, and extensions scripts. Up to 150 unique compiler errors.

![image](https://user-images.githubusercontent.com/93025618/154832370-41febce3-8b58-4932-8531-1d19e6aaecef.png)

**Comment by JuniorBaltazar** [comment]
Same problems in Unity 2020.3.27f1 (LTS)

**Comment by FlintNT** [comment]
Same problems in 2020.3.30f1

**Comment by rycsim** [comment]
me too

**Comment by hybridherbst** [comment]
Hi, this should be fixed on the dev branch and in this PR, a culmination of many fixes:
https://github.com/KhronosGroup/UnityGLTF/pull/644#how-to-test-this-pr

Would be great if you test that out, easy Unity package instructions are included in the link above.

**Comment by Sparks-Lu** [comment]
![Uploading 1650442065(1).png…]()

The fix has been tested. During import, there're three errors. Below are details.
1. Library\PackageCache\org.khronos.unitygltf@55b8a8bf4f\Editor\Scripts\GLTFImporter.cs(169,68): error CS0104: 'Animation' is an ambiguous reference between 'GLTF.Schema.Animation' and 'UnityEngine.Animation'

2. Library\PackageCache\org.khronos.unitygltf@55b8a8bf4f\Editor\Scripts\GLTFImporter.cs(340,16): error CS1501: No overload for method 'ParseJson' takes 2 arguments

3. Plugin 'Assets/Sketchfab For Unity/Dependencies/Libraries/GLTFSerialization.dll' has the same filename as Assembly Definition File 'Packages/org.khronos.unitygltf/Runtime/Plugins/GLTFSerialization/GLTFSerialization.asmdef'. Rename the assemblies to avoid hard to diagnose issues and crashes.

Would you please have a look? Thanks in advance.

**Comment by hybridherbst** [comment]
@Sparks-Lu Thanks, could you let me know which Unity version you're on?

Also, it looks like you have both "Sketchfab for Unity" and "UnityGltf" in the same project. Since the former was built on top of the latter, I don't think this is a usecase that can be reasonably supported, or rather that needs some fixes in "Sketchfab for Unity" - can look at that once the PR is merged.

**Comment by Sparks-Lu** [comment]
> @Sparks-Lu Thanks, could you let me know which Unity version you're on?
My Unity version is 2020.3.25f1c1.

> 
> Also, it looks like you have both "Sketchfab for Unity" and "UnityGltf" in the same project. Since the former was built on top of the latter, I don't think this is a usecase that can be reasonably supported, or rather that needs some fixes in "Sketchfab for Unity" - can look at that once the PR is merged.
I see. Thanks.

**Comment by dayowoo** [comment]
How did you solve it?

**Comment by dayowoo** [comment]
> Hi, this should be fixed on the dev branch and in this PR:
> 
> * [Culmination of two years of fixes, especially for export #644](https://github.com/KhronosGroup/UnityGLTF/pull/644)
> 
> Would be great if you test that out, easy Unity package instructions are included in the link above.

I installed this package, but the error is still.
How did i solve it?

**Comment by hybridherbst** [comment]
@dayowoo you installed which package? Did you use the git package as instructed on the readme from the prefrontal cortex fork, or the outdated .unitypackage from this repo here?
