### ISSUE TITLE
Animations are not exported in build

### ISSUE THREAD

**Issue by hierro** [KhronosGroup/UnityGLTF#650]
Hi, I do export correctly glb with animations from editor, but when i tried with th built project glb has no animations,not sure is an issue but some kind of my error, any hints?

**Comment by christianstamati** [comment]
Hi @hierro I downloaded UnityGIT from this link: https://github.com/prefrontalcortex/UnityGLTF.git?path=/UnityGLTF/Assets/UnityGLTF via Package Manager. In Project Settings Export animations is enabled but when I Export is not working... Could you please explain how you exported the animations form Editor?)

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
