### ISSUE TITLE
Where/What is the most recent version

### ISSUE THREAD

**Issue by glaporteavatar** [KhronosGroup/UnityGLTF#653]
Hello,

Great plugin for a great format.

I want to support gltf 2.0 or at least the most recent version.
Inside this GIT, where is the last version outside the master branch.
It is tag: release/1.0.2 or 1.1.1 ?
Last commit is 2 years old, any incoming update ? (gltf 2.0 released 1 year ago.)

Thank you.

**Comment by hybridherbst** [comment]
See https://github.com/KhronosGroup/UnityGLTF/pull/644 - feel free to try, feedback welcome! Getting closer to merging back in.
