### ISSUE TITLE
GLTF model broken in Unity Editor

### ISSUE THREAD

**Issue by fashioncoolwan** [KhronosGroup/UnityGLTF#654]
I have two models build with sketckup and export to gltf by blender.
[dooronly.zip](https://github.com/KhronosGroup/UnityGLTF/files/9120498/dooronly.zip)
[baseonly1.zip](https://github.com/KhronosGroup/UnityGLTF/files/9120521/baseonly1.zip)

They looks fine will in Blender、Three.js、Babaylon.js.
Blender view:
![image](https://user-images.githubusercontent.com/31815474/179216917-2ab118fb-1871-4f3a-b9ab-cc6fd18bf1b2.png)
![image](https://user-images.githubusercontent.com/31815474/179217336-29b10ead-8705-42ea-99f7-8fae236d0d1a.png)

But when i import them into Unity Editor, if i don't check “Generate Lightmap UVs”, the models are fine:
![image](https://user-images.githubusercontent.com/31815474/179217596-7adefe69-6acb-486a-8b24-3a6b44ee34c2.png)
![image](https://user-images.githubusercontent.com/31815474/179217642-96f88cd3-e9e0-4e83-a778-2a45ec9878cd.png)
But when i checked “Generate Lightmap UVs”, the models became so weird:
![image](https://user-images.githubusercontent.com/31815474/179218212-56f28e49-d994-47f2-b9d1-c3f97663ea20.png)
![image](https://user-images.githubusercontent.com/31815474/179218187-c50d8624-35f0-4b31-bc14-a1b82cd950b0.png)

Any guys konw what is going on?

**Comment by hybridherbst** [comment]
Followed up in the other thread - unfortunately this is a Unity bug (which I reported), we'll see if/when they fix this.
