### ISSUE TITLE
Assembly Assets/UnityGLTF/Plugins/net35/GLTFSerialization.dll will not be loaded due to errors

### ISSUE THREAD

**Issue by viol3** [KhronosGroup/UnityGLTF#663]
plugin cannot be imported in 2021.3.5f1
Newtonsoft.Json.dll files colliding and when net3.5 deleted, it gives this error:
![image](https://user-images.githubusercontent.com/10374743/219878466-f53087ea-b1b6-4554-bdd8-a1bcf1782833.png)

**Comment by hybridherbst** [comment]
Should be fixed on latest release.
