### ISSUE TITLE
saveGLB file textures filtering problem 

### ISSUE THREAD

**Issue by stadoblech** [KhronosGroup/UnityGLTF#664]
When i export model with `saveGLTF` method everything looks as it should 
![image](https://user-images.githubusercontent.com/5820599/220104968-d72a5605-8551-44fa-9c37-17e0c845931a.png)

But when i export model with `saveGLB `method textures filtering is different 
![image](https://user-images.githubusercontent.com/5820599/220105626-9e64f585-e61e-4a42-b0a2-69c6222d7092.png)

Same model, same settings only difference is between used method.  
I tried everything but nothing seems works. Any ideas why this is happening? 
Thank you

**Comment by pfcDorn** [comment]
can you please test it with the current version again?

**Comment by stadoblech** [comment]
> can you please test it with the current version again?

Sorry im not working at company anymore. I wish i had better repro
