### ISSUE TITLE
Repository maintenance

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/UnityGLTF#666]
To my understanding, this repository has been unmaintained about three years. Given Khronos' interest in a strong glTF ecosystem, and the potentially negative impact of an unmaintained "official" UnityGLTF, I think it would be strongly advisable for one of two things to happen:

- (A) The repository should be kept in sync with active forks, if interested maintainers can be found.
- (B) The repository should be archived, and users directed to the active forks.

Context:

- https://github.com/KhronosGroup/UnityGLTF/pull/644

**Comment by hybridherbst** [comment]
Plan is to finally merge that PR next week. prefrontal cortex is willing to continue reasonable maintenance of UnityGltf on the KhronosGroup repo.

**Comment by hybridherbst** [comment]
"Next week" turned into "a few months later" but here we are: https://github.com/KhronosGroup/UnityGLTF/releases/tag/release%2F2.9.0-rc
