### ISSUE TITLE
Import: Scale factor doesn't effect bounding boxes correctly

### ISSUE THREAD

**Issue by kipash** [KhronosGroup/UnityGLTF#669]
Adjusting the scaling factor will result in unwanted frustrum culling visible on screen. In other words, the bounding box is not updated correctly. _Perhaps there's a chance that it isn't updated at all? That it is based on the original mesh?_

With scale factor **1** and object scale 1
![image](https://user-images.githubusercontent.com/30328735/231438732-aa19280e-10cf-4a89-bccc-f16280969182.png)

With scale factor **2** and obeject scale 0.5
![image](https://user-images.githubusercontent.com/30328735/231438920-423c0314-0c53-41c5-aa54-6b4b23e415ce.png)

If i lower the view just a bit, the pot becomes visible:
![image](https://user-images.githubusercontent.com/30328735/231438980-9a40672c-a8b4-49c1-98d9-115770c55ee0.png)

Model: https://sketchfab.com/3d-models/plants-are-nice-52704c1bafd44bfd9e98538276ad5614
Or the exact one i used:
[Model.zip](https://github.com/KhronosGroup/UnityGLTF/files/11210593/Model.zip)

## Info
Unity: 2020.3.38f1
URP: 10.10.1
Unity GLTF: 1.24.0-pre.3 via Needle registry

**Comment by pfcDorn** [comment]
Should be fixed. Please update to the latest version and open a new issue if the problem persists. Thanks!
