### ISSUE TITLE
Import error, "Cannot perform upm operation: Unable to add package", Unity 2021.3

### ISSUE THREAD

**Issue by nickyonge** [KhronosGroup/UnityGLTF#672]
When attempting to import the UnityGLTF package via the Package Manager, I get an error:

> [Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/prefrontalcortex/UnityGLTF.git]:
>   [https://github.com/prefrontalcortex/UnityGLTF.git] does not point to a valid package. No package manifest was found. [NotFound].
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

followed by a second, more general error:

> [Package Manager Window] Error adding package: https://github.com/prefrontalcortex/UnityGLTF.git.
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

This happens when following the default [Installation](https://github.com/KhronosGroup/UnityGLTF/tree/dev#installation) process. Namely, adding the given package as a git url:
```
https://github.com/prefrontalcortex/UnityGLTF.git
```

It looks like the issue is with the supplied URL.

Specifically, I'm using Unity 2021.3.15f1 Personal on Windows 11. If you need any other info, do lemme know. Thanks!

Images of the console and Package Manager, respectively. It's a fresh project with nothing except some Unity default assets (.mat and .scene files) and one .glb in the directory. Issue still happens if the .glb isn't present.

![image](https://github.com/KhronosGroup/UnityGLTF/assets/2841909/2e4f4e32-d188-4dc9-9507-75fb59ed9153)

![image](https://github.com/KhronosGroup/UnityGLTF/assets/2841909/be665b6f-0375-46e2-b24b-04a6fe3fa35e)

**Comment by nickyonge** [comment]
Edit, based off of the /dev branch, got redirected to it and didn't notice =_= closing this issue

**Comment by hybridherbst** [comment]
Thank you, just wanted to send you to the fork to raise an issue :)
Fwiw the fork _will_ be merged back, but there have been a few runtime issues that we identified last minute.

**Comment by nickyonge** [comment]
Oh okay, thanks @hybridherbst! I got a bit confuddled by the branch setup, and then realized that the URL could still be fixed in dev. I'm throwing up a PR for it, and leave it to your discretion whether to merge it or wait to resolve the runtime issues.
