### ISSUE TITLE
Android package can't load streaming model, however project can running on the computer. How to setting or changing, about this problem?

### ISSUE THREAD

**Issue by shanshan1405** [KhronosGroup/UnityGLTF#674]
Android package can't load streaming model, however project can running on the computer. How to setting or changing, about this problem?

**Comment by hybridherbst** [comment]
I believe this is fixed on the latest release, would be great if you can test that!

**Comment by AlexRVillalobos** [comment]
Version 2.9.0-rc  load on Android, from URL and from local path.
