### ISSUE TITLE
AfterNodeExport but no BeforeNodeExport?

### ISSUE THREAD

**Issue by andybak** [KhronosGroup/UnityGLTF#677]
I'm trying to figure out the best way to customize the export for Open Brush.

Our problem is that the runtime scene graph isn't neccesarily the same structure we want to export. In fact we probably want to configure the export somewhat. 

At runtime the user's sketch is divided into layers (like Photoshop layers). Inside a layer there is a "batch" for each type of brush which is a single mesh. When a batch exceeds the Unity vertex limit, a new one is started.

There is also the concept of "groups" which are a convenient way to group stokes within a layer from the user's perspective. These don't exist in the Unity hierarchy.

So - I think our best approach is to run through a regular export to generate all the node that aren't brush stroke (imported models, images etc) but catch all the brush stroke nodes in a separate data structure and then on AfterSceneExport go through and generate nodes for groups and/or strokes (probably user configurable).

We also transform the vertex layout at this point. We ditch some of the uv channels that are for runtime use and optionally add some data that can be useful for exported meshes (for example timestamps so that the drawing of strokes can be animated).

So ideally I'd like a BeforeNodeExport that allowed me to either skip the node creation entirely (but record the parent for later use) or to skip the mesh creation.

**Comment by andybak** [comment]
@hybridherbst - any thoughts on this?

**Comment by andybak** [comment]
Ah. Seems to be resolved recently by a new commit to #644 - I had assumed the big merge was already complete on the dev branch. Seems not!

**Comment by hybridherbst** [comment]
Sorry for the delay!
The Big Merge comes any week now hopefully 😶‍🌫️

**Comment by andybak** [comment]
Is there a forum or something to keep track of plans? There's not a lot of discussion happening directly on Github and it would be helpful to follow along with whatever discussions are going on.
