### ISSUE TITLE
UnityGLTF as project package

### ISSUE THREAD

**Issue by jajanpreet** [KhronosGroup/UnityGLTF#678]
Hi,

I want to know if this project can be added as Unity Project dependency in existing project. I cannot find the package information

**Comment by marwie** [comment]
You can find the package in a subdirectory in this repository. 

https://github.com/KhronosGroup/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/package.json

**Comment by jajanpreet** [comment]
It ends up in this folder with a weird name and is not detected by Unity Project Viewer or Visual studio runtime environment
![image](https://github.com/KhronosGroup/UnityGLTF/assets/116213974/719d1385-252e-4053-892c-ec3452d16725)
![image](https://github.com/KhronosGroup/UnityGLTF/assets/116213974/07a06147-83e6-442e-a075-0c456f7b3118)
![image](https://github.com/KhronosGroup/UnityGLTF/assets/116213974/b4c65d8f-d8f8-4b56-b949-d16a35e945ac)

**Comment by marwie** [comment]
You need to enter the path in the git url to the subfolder, see https://docs.unity3d.com/Manual/upm-git.html#subfolder

**Comment by jajanpreet** [comment]
Now the package is under a folder but throws namespace errors. Can someone from the team please verify this with Sample unity project
![image](https://github.com/KhronosGroup/UnityGLTF/assets/116213974/ea08a68c-6a00-4477-a4ab-e63b7942f6a7)

**Comment by jajanpreet** [comment]
@marwie Can I please know if this can be addressed?

**Comment by marwie** [comment]
Try with this fork https://github.com/prefrontalcortex/UnityGLTF

**Comment by hybridherbst** [comment]
Readme instructions have been updated to show the installation flow. Thanks!
