### ISSUE TITLE
Build fails only for GLTFSerializationUWPTests

### ISSUE THREAD

**Issue by S-Togawa** [KhronosGroup/UnityGLTF#679]
Open GLTFSerialization.sln
I'm trying to do a Release build.
Build fails only for GLTFSerializationUWPTests.

At that time, only GLTFSerialization of GLTFSerializationUWPTests
A warning appears saying "The project 'GLTFSerialization' cannot be referenced. GLTFSerializationUWPTests".
![image](https://github.com/KhronosGroup/UnityGLTF/assets/89629355/f9310a6b-ce42-45f4-b7dc-f26196603243)

If you ignore the warning and proceed with the Release build
The following error will occur.
![image](https://github.com/KhronosGroup/UnityGLTF/assets/89629355/a79df33d-22d5-4693-906b-b871fb41412e)

If such a problem occurs
What are the possible causes?
Please give me some advice.

Development environment
・Visual Studio Community 2019
・.NET SDK Ver 5.0.408

**Comment by hybridherbst** [comment]
Can you try on the dev branch please?
Building GLTFSerialization.sln manually isn't required anymore.

**Comment by S-Togawa** [comment]
I cloned the dev branch.

I opened the "Test" project using UnityHub.
A simple project like the one below is displayed.
![image](https://github.com/KhronosGroup/UnityGLTF/assets/89629355/6f0937f5-b6dc-4f68-81d3-5c10a055ebb7)
Is what I'm doing right?

By the way, follow the method written in "Installation" in README.md.
When I try to install the package
An error like the one below occurred.
![image](https://github.com/KhronosGroup/UnityGLTF/assets/89629355/18302a43-4caa-45c2-96f3-50b9431272d1)

**Comment by hybridherbst** [comment]
@S-Togawa that "Test" project doesn't exist anymore. The repo _is_ the package.

You're getting an error because you're trying to add the main branch as git package, which has not been updated yet.
Please use
- `https://github.com/prefrontalcortex/UnityGLTF.git#dev` or 
- `https://github.com/prefrontalcortex/UnityGLTF.git#release/2.7.1-exp`

**Comment by S-Togawa** [comment]
glb file loaded!

Thank you for your detailed explanation!
