### ISSUE TITLE
README supported extensions out of date?

### ISSUE THREAD

**Issue by andybak** [KhronosGroup/UnityGLTF#680]
Example: KHR_materials_pbrSpecularGlossiness doesn't seem to be listed but it is in the codebase.

**Comment by hybridherbst** [comment]
The [KHR_materials_pbrSpecularGlossiness](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Archived/KHR_materials_pbrSpecularGlossiness/README.md) extension has been archived and should no longer be used, so we're not pointing it out in the Readme anymore.

It is superseded by [KHR_materials_specular](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_specular/README.md) which is partially supported (data roundtrip for import and export works fine but the shader in Unity doesn't look correct yet).
