### ISSUE TITLE
HumanoidSetup needs to check "isHuman"

### ISSUE THREAD

**Issue by FujiSunflower** [KhronosGroup/UnityGLTF#681]
# Before
If HumanDescription is wrong, the avatar is not human but generic as "isValid".
https://github.com/KhronosGroup/UnityGLTF/blob/d9ed104fd3ecc10265c7836484cd68e34cbedc13/Editor/Scripts/Internal/HumanoidSetup.cs#L25

# Aftar
So we will fix it like this.
`if (!avatar.isValid || !avatar.isHuman)`

# References
https://docs.unity3d.com/ScriptReference/Avatar-isHuman.html
https://docs.unity3d.com/ScriptReference/Avatar-isValid.html

**Comment by pfcDorn** [comment]
i have fixed it with 5363224499393edf03d7177a40139618a5907273
Thx!
