### ISSUE TITLE
UnityMeshData.MorphTargetNormals[i] may need to check null on Import

### ISSUE THREAD

**Issue by FujiSunflower** [KhronosGroup/UnityGLTF#682]
# Problem
UnityMeshData.MorphTargetNormals[i] may need to check null on import.
https://github.com/KhronosGroup/UnityGLTF/blob/d9ed104fd3ecc10265c7836484cd68e34cbedc13/Runtime/Scripts/SceneImporter/ImporterMeshes.cs#L908

# References
It is because the array has null check on AddBlendShapesToMesh in ConstructUnityMesh.
 https://github.com/KhronosGroup/UnityGLTF/blob/d9ed104fd3ecc10265c7836484cd68e34cbedc13/Runtime/Scripts/SceneImporter/ImporterMeshes.cs#L554

**Comment by pfcDorn** [comment]
`if (targets[i].TryGetValue(SemanticProperties.NORMAL, out var tarAttrNorm)`

**Comment by pfcDorn** [comment]
I don't think this is needed, because we already check if there is a attribute for the morphtargetnormals.

**Comment by pfcDorn** [comment]
![image](https://github.com/KhronosGroup/UnityGLTF/assets/118285915/b76f6bf7-188f-43bd-ad43-b8b765ca6f18)

**Comment by hybridherbst** [comment]
@FujiSunflower out of curiosity, where was that file created / what software was it created with?

**Comment by FujiSunflower** [comment]
Maybe it was made by UniVRM as Refererence's url. I re-tested by UniVRM. I found the file uses Sparse Accessor.
If UniVRM use no Sparse Accessor, the file is success.
If UniVRM use Sparse Accessor, the file is failure..
Perhaps UniVRM has any problem in Sparse Accessor. But I don't know the detail.

**Comment by hybridherbst** [comment]
Thank you! I believe the file is perfectly valid, it's just unusual that some blend shapes include normals and others not, so was curious where it comes from / what the reasoning is.
