### ISSUE TITLE
[One line of code fix] Unnecessary color space correction is applied when swapping from Unity's metallic-smoothness textures

### ISSUE THREAD

**Issue by gpablo-genies** [KhronosGroup/UnityGLTF#692]
The [dev branch](https://github.com/KhronosGroup/UnityGLTF/tree/dev) currently applies a shader pass to transform metallic-smoothness textures used in Unity's URP Lit material to the roughness-metallic glTF specification. [This is the shader](https://github.com/KhronosGroup/UnityGLTF/blob/dev/Runtime/Resources/MetalGlossChannelSwap.shader) used to apply that transformation and it currently outputs incorrect results when having the project in the Linear color space setting.

The following `#ifdef` block starting at line 59 should be removed:
```ShaderLab
#ifdef UNITY_COLORSPACE_GAMMA
#else
// hack for linear color space, need to figure out
// right way to sample textures.
result.xyz = GammaToLinearSpace(result.xyz);
#endif
return result;
```

There is no need to perform the GammaToLinearSpace conversion since the metallic-smoothness maps should already come in linear space. Even if they don't, Unity already samples textures marked as sRGB in linear space when using the linear space in project settings.

I have tested exporting glTF models using both linear and sRGB metallic-smoothness textures and it always outputs an incorrect map. It is fixed whenever I remove the manual correction from the shader.

**Comment by hybridherbst** [comment]
> it always outputs an incorrect map

The colorspaces for exported textures have underwent pretty rigorous testing for linear color space correctness, including automated tests. Could you add a model where you see that issue and a video of it? Thanks!

**Comment by gpablo-genies** [comment]
Will try to provide the models this week, but may delay to next. Anyways I want to point out that the returned color by the tex2D sampler method will always be in linear space when the project is set to linear mode. So it really makes no sense to make the GammaToLinearSpace correction here (maybe it should be at the other side of the #ifdef?)

**Comment by gpablo-genies** [comment]
## [UnityGLTF-Smoothness2Roughness-Test.zip](https://github.com/KhronosGroup/UnityGLTF/files/14222868/UnityGLTF-Smoothness2Roughness-Test.zip) (2022.3.17f1)

@hybridherbst I'm including a zip with a testing project. It contains a scene with a simple quad using the URP/Lit material with a plain metallic-smoothness map (metallic set to 1 and smoothness to 0.2). The project contains the dev branch of UnityGLTF as an embedded local package in the Packages folder, with no modifications (except a test Debug.Log to see when we use the gloss-roughness swap material to process a texture).

I did two glTF exports of the quad that you can find in the `Assets/_Exports` folder:
* __CurrentExport__: the quad exported with no modifications on the UnityGLTF package. Put it on the scene and compare to the original quad, you will see how the roughness looks different.
* __FixedExport__: he quad exported with the `GammaToLinearSpace` line removed from the shader. It looks identical to the original quad.
* __GLB-Export__: for some reason GLB exports are not using the shader so removing the line will do nothing here. GLB exports are also exporting the roughness incorrectly.

Screenshots of original vs current vs fixed exports:
| Original | Current Export | Fixed Export |
| -- | -- | -- |
| ![image](https://github.com/KhronosGroup/UnityGLTF/assets/102548945/29a2ad3b-dee4-4856-a4f3-ab84594edc71) | ![image](https://github.com/KhronosGroup/UnityGLTF/assets/102548945/5018e62b-8a47-4d2e-8f8c-3823122a5c3c) | ![image](https://github.com/KhronosGroup/UnityGLTF/assets/102548945/442852d7-48a6-4c13-a014-533e2dd7c7ee) |

Notes: I cannot share the models that I used originally to debug this issue, but I would like to mention that in that case the roughness difference is huge (a character with a really glossy skin when exported).

**Comment by pfcDorn** [comment]
Hey, can you please retest it with the new latest version? 
I tested it with your sample and it seems to works fine now :)

**Comment by gpablo-genies** [comment]
I can confirm that the issue is fixed in the latest HEAD from the dev branch. Thank you so much!

**Comment by pfcDorn** [comment]
Happy to hear :)
