### ISSUE TITLE
Incorrect import result for quantized model by gltfpack

### ISSUE THREAD

**Issue by wayne-wu** [KhronosGroup/UnityGLTF#693]
I'm trying to get UnityGLTF to work with files compressed using `gltfpack` but have been getting incorrect results.

For example, [this rigged character](https://sketchfab.com/3d-models/naruto-rigged-775848d87b054a0ca7a181d32f0b79c2) does not get imported correctly after running gltfpack whereas both [gltf Viewer](https://gltf-viewer.donmccurdy.com/) and gltFast import the model correctly before and after quantization. Even something as simple as the [Avocado](https://github.com/KhronosGroup/glTF-Sample-Assets/blob/main/Models/Avocado/README.md) has different results before and after quantization. 

| UnityGLTF (Original) | UnityGLTF (Quantized) | gltFast (Quantized)
| ------------- | ------------- | ------------- | 
| <img width="200" alt="image" src="https://github.com/KhronosGroup/UnityGLTF/assets/77313916/5e6268d7-e95b-45c5-a62e-469086aac01e"> | <img width="200" alt="image" src="https://github.com/KhronosGroup/UnityGLTF/assets/77313916/1699dc76-a2c5-457e-b557-ecf6b9fc78c1">  | <img width="220" alt="image" src="https://github.com/KhronosGroup/UnityGLTF/assets/77313916/2c0d0050-9ac6-44e4-8737-e94a5fddf4c8">

I'm guessing it has something to do with quantization and the extra node transform that's applied by `gltfpack`, but I can't be sure yet. If I run gltfpack with `-noq` (disable quantization) then it imports fine.

Unity Version: 2021.3.31f1
UnityGLTF Version: 2.9.0-rc

Any insights would be appreciated!

**Comment by pfcDorn** [comment]
I guess you are right. Mesh is there, but it get not rendered. But also not in Scene view. I will take a closer look 
![image](https://github.com/KhronosGroup/UnityGLTF/assets/118285915/41972d85-cb56-4a50-a7bf-371711cb709a)

**Comment by pfcDorn** [comment]
hm...it seems to be more an scale issue here. When i set the import scale to 65000, then it has the same size as the gltfast import. So maybe it's a quantization issue here

**Comment by hybridherbst** [comment]
Please only close PRs when the fix has actually landed in a release!
