### ISSUE TITLE
'Texture2D' does not contain a definition for 'isDataSRGB'

### ISSUE THREAD

**Issue by umeraamir-arthur** [KhronosGroup/UnityGLTF#695]
I've imported this package in Unity 2021.3.15f1 and URP enabled using multiple ways including git URL and manual import. It works fine but when I import KTX package it has an error that Texture2D class has no isDataSRGB.

![image](https://github.com/KhronosGroup/UnityGLTF/assets/149570800/64b8bc33-44d8-4daf-ad63-36b57b094f0e)

It is listed in the supported versions list in Unity docs but not able to find it in its implementation.

![image](https://github.com/KhronosGroup/UnityGLTF/assets/149570800/d4fa04e6-9426-4a80-9b7e-2aedb6ba862e)
![image](https://github.com/KhronosGroup/UnityGLTF/assets/149570800/ecbba99b-f387-48ee-8e01-25611ced14c2)

Edit: Colorspace is linear

**Comment by umeraamir-arthur** [comment]
@hybridherbst can you suggest something here.... Thankyou

**Comment by pfcDorn** [comment]
hey, i have already a PR for this: https://github.com/KhronosGroup/UnityGLTF/pull/689
For a fast solution now: just update unity 2021.3.15f to 2021.1.35f :)

**Comment by umeraamir-arthur** [comment]
Thankyou for the reply @pfcDorn 

I searched through the issues list but missed the PRs list. :D

In that case, I would need to ask everyone to upgrade the Unity version. Also we've a production code with lots of people uploading different types of GLBs. Which solution do you recommend in this scenario.

**Comment by pfcDorn** [comment]
hm...good question :D 
maybe you can make a fork of unityGltf and merge the branch into it ...? I don't know at the moment when it gets merged into the official khronos repo.

**Comment by hybridherbst** [comment]
I can look at it early next week.

**Comment by umeraamir-arthur** [comment]
@hybridherbst that would be great because upgrading Unity version might not be feasible for me because it'll cause everyone to forcefully do an unplanned upgrade.

@pfcDorn I suppose that if I fork and merge on my side then every time when a new update is available on this main repo, I might have to update my forked repo manually. Is it going to be the case? In that case, it would be better to wait for @hybridherbst to merge the PR.

**Comment by pfcDorn** [comment]
when it's get merged to the main repo, you no longer need to use your fork. But of course, maybe just wait :)

**Comment by umeraamir-arthur** [comment]
That makes sense. Thankyou for your response 🥇

**Comment by umeraamir-arthur** [comment]
Yessssssssss....... it solved the issue @hybridherbst 
Thankyou for asking <3
