### ISSUE TITLE
Add .unitypackage Release

### ISSUE THREAD

**Issue by robertlong** [KhronosGroup/UnityGLTF#7]
When its ready, it'd be nice to include a downloadable .unitypackage in the releases section.

**Comment by DDReaper** [comment]
Any update on this Issue?  Any plans to provide a downloadable .Asset package
(asking for a friend :P )

**Comment by wandergis** [comment]
Can not agree more!!!

**Comment by blgrossMS** [comment]
Just added the first built unitypackage in the releases
