### ISSUE TITLE
Encounter object export errors when using package

### ISSUE THREAD

**Issue by hanyaonian** [KhronosGroup/UnityGLTF#700]
I encountered some export errors while using the dev branch package: 
"Curve of animated property has no property type, can not validate [xxx] on [xxx]." 

The object with animation works fine at runtime, but it doesn't play animation after exporting as glb/gltf. Additionally, I exported a large number of GameObject with same operations, but a few of them reported this errors, the others works well. I apologize that I am a web developer and not very familiar with Unity.

Can anyone give some help or advice? Q_Q

**Comment by hybridherbst** [comment]
Please post a unitypackage with the models and animations that cause the issue here so that we can reproduce it.

Also please note
- the full error message – it contains info what exactly can't be exported/validated
- Unity version
- SRP (e.g. URP or BiRP)
- if you have KHR_animation_pointer enabled or not

**Comment by hanyaonian** [comment]
> Please post a unitypackage with the models and animations that cause the issue here so that we can reproduce it.
> 
> Also please post
> 
> * the full error message – it contains info what exactly can't be exported/validated
> * Unity version
> * SRP (e.g. URP or BiRP)
> * if you have KHR_animation_pointer enabled or not

Thank you for your reply. I apologize for the late response, as I was waiting approval from game developers. They do not want me to upload any Unity resources to external platforms, so this issue can be closed. If I manage to solve the problem through any means, I will update the solution here. Thank you again for your help. ^ ^

**Comment by hanyaonian** [comment]
> @hanyaonian If needed I can set up a secure Drive folder for upload / NDA for specific projects.

Thank you. I have suggested to the game developers that providing you an NDA and sharing some resources will be helpful, but I am still waiting for response.

There were new characters in the game, so I re-exported them using the latest version of the UnityGLTF package, but the ouput can not play animation properly. I checked out the older package, 2.6.0 exp (from commit 122f9910693111afce6ccfa044a8af22b7faf7be), then everything went smoothly. (the export function in the menu bar and the export function in script)

Perhaps there have been some changes in the animation section?

**Comment by hybridherbst** [comment]
@hanyaonian we really need models that reproduce the issue to see what is going wrong there, this is not enough information.

Between 2.6.0 and 2.10.0 there have been various changes to the plugin infrastructure, I recommend you double-check that KHR_animation_pointer plugin isn't enabled if your target software(s) don't support that extension. It's disabled by default but maybe you have turned it on?
