### ISSUE TITLE
Creating animation on runtime, from scratch

### ISSUE THREAD

**Issue by KenneyNL** [KhronosGroup/UnityGLTF#702]
Hey! I'd like to know if it's possible to create a new animation from scratch, and add it to the exporter.

Currently I'm doing this, however the GLB file will not be readable (without adding the animation, it remains readable);

```
var adjustedSettings = Object.Instantiate(GLTFSettings.GetOrCreateSettings());
			adjustedSettings.ExportDisabledGameObjects = true;
			adjustedSettings.ExportAnimations = true;
		
		var _exporter = new GLTFSceneExporter(new Transform[]{ ManagerSkeleton.instance.root }, new ExportOptions(adjustedSettings));
		
		GLTFAnimation _animationA = new GLTFAnimation();
		_animationA.Name = "TestA";
		
		_exporter.AddAnimationData(ManagerSkeleton.instance.root, "Test", _animationA, new float[]{ 0 }, new Object[]{});
		
		_exporter.GetRoot().Animations.Add(_animationA);
		
		_exporter.SaveGLB(Application.dataPath + "/..", "export-character");
```

**Comment by pfcDorn** [comment]
Hey, 
this should work (i also tested it right now)
But...
First: Make sure when you call AddAnimationData the new float[]  and new Object[] have the same array length,
Second: Make sure the property for ManagerSkeleton.instance.root is supported, maybe you should also using the Animationpointer plugin.

Can you share the not readable exported file?

**Comment by hybridherbst** [comment]
Hi Kenney, glad to see you here!

Your code is almost correct but what may be a bit counterintuitive is that exporting additional animation data should happen in the `AfterSceneExport` callback – this way, the hierarchy and nodes where animation is applied is already captured and node IDs can be properly resolved.

Also note that typically when you want to export custom animations .ExportAnimations should be false, unless you want Animation/Animator components in your scene to also export their animation clips.

```cs
var adjustedSettings = Object.Instantiate(GLTFSettings.GetOrC
adjustedSettings.ExportDisabledGameObjects = true;
adjustedSettings.ExportAnimations = false;

var exportContext = new ExportContext(adjustedSettings);
var _exporter = new GLTFSceneExporter(new Transform[]{transfo

exportContext.AfterSceneExport += (scene, root) =>
{
    GLTFAnimation _animationA = new GLTFAnimation();
    _animationA.Name = "TestA";
    _exporter.AddAnimationData(e, "translation", _animationA,
    _exporter.GetRoot().Animations.Add(_animationA);
};

_exporter.SaveGLB(@"D:\", "export-character");
```

For reference you can also look at the `GLTFRecorder` API – which allows you to basically record arbitrary animated hierarchies into a file. It is used for the `RecorderComponent` and `RecorderTrack/RecorderClip` but you can also use it from your own scripts.

**Comment by KenneyNL** [comment]
Hey, well - thank you for working on this and willing to help me! Your code works perfectly, I indeed had to move it to the after scene export (and update my version of UnityGLTF as I was missing ExportContext from my version).

However, my goal was to create animations and export them on run-time in a build. Currently this code works perfectly in the Unity editor during run-time, but when making a build it doesn't export the animations anymore. I was under the impression that this method should work in a build?

**Comment by hybridherbst** [comment]
Hm, the GLTFRecorder works fine at runtime with basically the same code (that's what it's designed for) – @pfcDorn can you check?

**Comment by KenneyNL** [comment]
Yeah! That's why I thought it was weird that the build doesn't create the animations while in the editor (at runtime) it does. The reason I'm not using GLTFRecorder is because (and could be a mistake on my side) I'd want multiple animations to be exported in my GLB file and I'm not sure if that's possible with just GLTFRecorder. Hence I'm kind of "coding" my own animations, which honestly is also kind of fun to mess around with.

**Comment by KenneyNL** [comment]
There's something very strange going on, while a few hours ago the code at least worked in the editor it doesn't work at all anymore. I'm utterly confused because I didn't change a thing, just closed and re-opened the project.

As what I'm trying to animate; it's just a game object position. There's no other code in the project than that shown above so it's really strange...

**Comment by KenneyNL** [comment]
That did the trick! Both in editor, and in the build! Thank you so much!

Any way I can donate?

**Comment by pfcDorn** [comment]
Happy to hear :)

**Comment by hybridherbst** [comment]
@KenneyNL regarding donations, development is currently a joint effort between prefrontal cortex and Needle (I'm part of both) – with Needle leveraging UnityGLTF for all exporting, and thus ongoing heavy real-world testing. 

There's a donations page here: https://engine.needle.tools/donate/ 

I wanted to talk to you anyways about bringing more of your content to people in an interactive way :)
