### ISSUE TITLE
ShaderGraph dependency problem for OpenUPM install

### ISSUE THREAD

**Issue by from2001** [KhronosGroup/UnityGLTF#704]
I got the following error when I install UnityGLTF using OpenUPM

```
openupm add org.khronos.unitygltf

WARN 404 version 10.0.0 is not a valid choice of 0.1.8, 0.1.9, 0.1.17, 1.0.0-beta, 1.1.1-preview, 1.1.2-preview, 1.1.3-preview, 1.1.4-preview, 1.1.6-preview, 1.1.9-preview, 1.1.8-preview, 1.1.5-preview, 2.0.1-preview, 2.0.3-preview, 2.0.4-preview, 2.0.4-preview.1, 2.0.5-preview, 3.0.0-preview, 2.0.6-preview, 2.0.7-preview, 2.0.8-preview, 3.1.0-preview, 3.3.0-preview, 4.0.0-preview, 4.0.1-preview, 5.0.0-preview, 4.1.0-preview, 4.2.0-preview, 5.1.0, 4.3.0-preview, 5.2.0, 5.2.1, 5.2.2, 4.6.0-preview, 5.2.3, 4.8.0-preview, 4.9.0-preview, 5.3.1, 4.10.0-preview, 5.6.1, 5.7.2, 5.8.2, 5.9.0, 5.10.0, 5.13.0, 6.5.3, 6.5.2, 6.7.1, 5.16.1, 6.9.0, 7.0.0, 7.0.1, 6.9.1, 7.1.1, 7.1.2, 6.9.2, 7.1.5, 7.1.6, 7.1.7, 7.1.8, 7.2.0, 7.2.1, 8.0.1, 7.3.1, 9.0.0-preview.14, 8.1.0, 7.4.1, 9.0.0-preview.34, 8.2.0, 10.0.0-preview.27, 7.4.2, 7.4.3, 9.0.0-preview.55, 7.5.1, 10.1.0, 9.0.0-preview.72, 10.2.0, 8.3.1, 10.2.1, 7.5.2, 10.2.2, 10.3.1, 7.5.3, 10.3.2, 10.4.0, 7.6.0, 10.5.0, 7.7.0, 10.5.1, 10.6.0, 7.7.1, 10.7.0, 10.8.0, 10.8.1, 10.9.0, 10.10.0, 10.10.1
notice suggest to install com.unity.shadergraph@10.0.0 or a replaceable version manually
ERR! missing dependencies please resolve the issue or run with option -f to ignore the warning
```

The package has a dependency of ["com.unity.modules.imageconversion": "1.0.0"](https://github.com/KhronosGroup/UnityGLTF/blob/8aed9a87f08e9e939e108a3ee49c009978f38a5e/package.json#L22), but the version is not valid.

**Comment by hybridherbst** [comment]
Hey, thanks for the report. This looks like a regression in Unity, 10.0.0 should simply resolve to the latest supported version.

Which Unity version are you using?

**Comment by from2001** [comment]
I got the error with Unity 2022.3.18

**Comment by hybridherbst** [comment]
OK, thanks. I'll try to reproduce. It works fine on 2022.3.17f1 and 2022.3.20f1.
Have you changed the package resolution settings for your project by any chance? (https://docs.unity3d.com/Manual/upm-manifestPrj.html#resolutionStrategy)

**Comment by hybridherbst** [comment]
This is a bug in the OpenUPM CLI:
- https://github.com/openupm/openupm/issues/4772

As a workaround, run `openupm add org.khronos.unitygltf -f`, the defined dependencies in package.json work just fine.

**Comment by from2001** [comment]
Thanks. I'll use -f option until the bug is fixed. I encountered the bug with a different package and posted the issue in the repository. 
https://github.com/openupm/openupm-cli/issues/19#issuecomment-1871057403
