### ISSUE TITLE
how to get progress (while loading) runtime.?

### ISSUE THREAD

**Issue by lalamax3d** [KhronosGroup/UnityGLTF#707]
precisely, its not issue, but question.

How to get progress while loading glb (runtime) from weburi (http://localhost/cases/1/1.glb)

in my case.. this works fine, except no progress.
```csharp
string glbUrl = Path.Combine(modelsURL, glbFileName);
Debug.Log("GLB URL: " + glbUrl);

// Create an ImportOptions object
var importOptions = new ImportOptions();

// Create a GLTFSceneImporter and a GLTFSceneImporter object
var loader = new WebRequestLoader(glbUrl);
var sceneImporter = new GLTFSceneImporter(
  Path.GetFileName(glbUrl),
  loader
);
// Create a GLTFSceneImporter object
var sceneImporter = new GLTFSceneImporter(
  glbUrl,
  importOptions
);
        
// Load the GLB model (approach 01) no progress
yield return sceneImporter.LoadScene(-1);
```
i tried (after some searching) but failing..
```chsarp
// approach 02 v2
//sceneImporter.progressChanged += OnProgressChanged;
  while (sceneImporter.progress < 1f) {
    Debug.Log($"Progress: {sceneImporter.progress}");  
    yield return null;
}
```

progressChanged doesn't exists plus sceneimporter.progress is private.?? any ideas..
thanks in advance.

**Comment by pfcDorn** [comment]
Hey, with LoadSceneAsync
 `public async Task LoadSceneAsync(int sceneIndex = -1, bool showSceneObj = true, Action<GameObject, ExceptionDispatchInfo> onLoadComplete = null, CancellationToken cancellationToken = default(CancellationToken), IProgress<ImportProgress> progress = null)`
 you can use the IProgress<ImportProgress> interface. On the LoadScene Method is it currently missing. 
 When you need it in a coroutine you can use the Task extension "AsCoroutine" as is used in the LoadScene method: 
![image](https://github.com/KhronosGroup/UnityGLTF/assets/118285915/57f8806e-8662-48f5-9f98-4498bbe6688a)

**Comment by lalamax3d** [comment]
@pfcDorn, huge thanks. 

for me, approach 02 worked like this.
```cs
using System.Threading; // Add this line at the top of your file

// then inside loading function...
var progress = new Progress<ImportProgress>();
progress.ProgressChanged += (s, e) => {
            // Replace e.PercentComplete with the correct property or method
            Debug.Log($"Progress: {e.Progress}%"); // This is just an example. Replace e.Progress with the correct property or method.
};

// Load the GLB model asynchronously and report progress
yield return sceneImporter.LoadSceneAsync(-1, true, null, default(CancellationToken), progress).AsCoroutine();
```
