### ISSUE TITLE
Incorrect material texture offset value on KTX2-based compressed GLB import

### ISSUE THREAD

**Issue by umeraamir-arthur** [KhronosGroup/UnityGLTF#709]
Hi @hybridherbst @pfcDorn 

I'm trying to import a GLB using UnityGLTF. I've the latest version of it installed through a forked repo of mine. I've a GLB which I've compressed using gltf-transform. I've only compressed its textures to KTX2. This same GLB is perfectly working with GLTFast but it's UVs are not mapped correctly with UnityGLTF.

After some research, I found out that this issue is not with UVs import but it is the offset of the textures which was not imported correctly. As shown in pictures below.
![image](https://github.com/KhronosGroup/UnityGLTF/assets/149570800/748b7950-843c-484c-aa22-1cf5bd3893e4)
![image](https://github.com/KhronosGroup/UnityGLTF/assets/149570800/1b2e32db-7847-49a5-a733-649f290c29da)

I've also attached the GLB. Can you guys please guide me on what should be the possible quick fix for this issue. Really appreciate your response.
[Santa_compressed.zip](https://github.com/KhronosGroup/UnityGLTF/files/14559456/Santa_compressed.zip)

**Comment by pfcDorn** [comment]
Hi! Thanks for the test file! 
Your are correct, the offset was wrong. Was only correct when there is a TextureTransform extension on it.

**Comment by umeraamir-arthur** [comment]
Thankyou @pfcDorn 
You guys are a gem.... :)
