### ISSUE TITLE
KtxTexture AssertionException

### ISSUE THREAD

**Issue by wayne-wu** [KhronosGroup/UnityGLTF#710]
I'm getting an error for a model with KTX textures: 
```
AssertionException: KtxTexture in invalid state. Open has to be called first.
```
It seems to work fine with gltFast which also uses KtxUnity.

KTX textures were generated using gltfpack.

Here's a model that you can test with: 
[AvocadoCompressed.zip](https://github.com/KhronosGroup/UnityGLTF/files/14563147/AvocadoCompressed.zip)

Unity Version: 2021.3.31f1
UnityGLTF Version: 2.10.0-rc.2

Thanks!

**Comment by pfcDorn** [comment]
hey, 
hm... i don't get any errors with this file. 
how exactly do you load it? Or do you just import it in unity?

**Comment by wayne-wu** [comment]
I'm just dragging it into the editor. Let me see if it's something on my end.

**Comment by pfcDorn** [comment]
i updated to the latest KTX Version 3.3.0, and now i have the same issue. I will investigate it :)
As short fix for you, with this KTX version it works:  https://github.com/atteneder/KtxUnity

**Comment by pfcDorn** [comment]
Found the issue... ktx.dispose get unnecessary called. I guess in the latest KTX Version they added this throw message to .Dispose.

**Comment by wayne-wu** [comment]
Can confirm that it works after removing the `.Dispose`. Thanks!
