### ISSUE TITLE
Textures are loading twice in memory causing doubled CPU spike and memory usage

### ISSUE THREAD

**Issue by umeraamir-arthur** [KhronosGroup/UnityGLTF#713]
Hi @hybridherbst @pfcDorn 

I'm loading a GLB through code using default settings provided by the API. I wonder why is there loading of a texture is twice when a GLB is loaded. Can we change it to use single texture instead?

![image](https://github.com/KhronosGroup/UnityGLTF/assets/149570800/93359a6d-cbd8-47e7-836c-9958e68bb29f)
![image](https://github.com/KhronosGroup/UnityGLTF/assets/149570800/8a000e61-e252-4fe3-a80b-a9b3a0945911)

There are 2 crucial issues because of this.
1. CPU spike gets doubled because it first calls LoadImage() and then Object.Instantiate() both in a same frame.
2. Memory usage gets doubled because both textures resides in memory until a GLB is destroyed.

![image](https://github.com/KhronosGroup/UnityGLTF/assets/149570800/97585fb4-c37d-41fa-babb-154a1622e30b)

Looking forward for your reply.... Thankyou

**Comment by pfcDorn** [comment]
Hey, 
that is as intended. At line 505, it will only be created when the previous created texture has other sampler settings (like filterMode or WarpMode). 
When they have both the same sampler settings, it's likely a bug.

**Comment by umeraamir-arthur** [comment]
Can we just change sampler settings of first one and assign it to the second one? As the first one (I suppose) has no use here after...

**Comment by pfcDorn** [comment]
So the first created Texture is not in use? Maybe you can share the file here?

**Comment by umeraamir-arthur** [comment]
It is the same case for any GLB it'll load the texture twice.... First one has only 1 reference which is (I guess) ImageCache list... and the second one is assigned to materials and has a proper use
![image](https://github.com/KhronosGroup/UnityGLTF/assets/149570800/663c8d02-07ce-4a97-94db-681511e48903)

**Comment by pfcDorn** [comment]
i will check! that's very likely a bug :)

**Comment by umeraamir-arthur** [comment]
It is a very old bug since first build which I once resolved as well but wasn't able to share at that time unfortunately.

Basically, the problem is that when you load any GLB from code using GLTFComponent in a build and then if you use memory profiler by Unity then it'll show that every texture is loaded 2 times. First texture has only 1 reference and the second has proper use of it. Also if you use CPU profiler then you can see big spikes when a texture is loaded because it once load a texture through LoadImage() and then Object.Instantiate() on same frame. Above mentioned places are the exact points which I found after profiling.

Hope these information help.

**Comment by pfcDorn** [comment]
Still needs some tests, but should prevent this behaviour now: 73f7b66cb2311630445999ccff71177d1649b5af

**Comment by umeraamir-arthur** [comment]
Hi @pfcDorn... Thankyou for sharing the implementation

I managed to brought back my implementation of the issue.

I would prefer older implementation because of many reasons

- If isFirstInstance is null then there might be issues to call Object.Instantiate(null) in that case
- isFirstInstance can't be null because of if (!source) return; at line 427
- No if-else needed for Object.Instantiate so it is a simpler version of it
- I've tested this on few test cases and was working fine on previous version

[Here is the commit I made.](https://github.com/prefrontalcortex/UnityGLTF/compare/main...arthur-technologies:UnityGLTF-forked-prefrontalcortex:UmerAamir/optimization-texture-duplication-GLB)

**Comment by pfcDorn** [comment]
With your solution you just removed completly the support for multiple sampler settings on a single texture. In Unity we need to duplicate a texture when we have in the gltf different sampler settings for the same texture. 
Lets say we use Texture A in Material 1 and in Material 2. In Material 1 the texture will have WrapMode Repeat, and in Material 2 it will set to Clamp.  So in this case we must dublicate the texture on import to support this. Otherwise one material will not be displayed correctly.

**Comment by umeraamir-arthur** [comment]
Yes but this statement is true for both of the above solutions I suppose.

The issue was that if you've 1 texture and 1 material it was still loading the texture twice.

**Comment by pfcDorn** [comment]
thats the reason why i added the isFirstInstance, so it only create the texture twice or more when it's needed (in case of multiple sampler states)

**Comment by umeraamir-arthur** [comment]
But I think isFirstInstance might always be true because of the lines on 429 and 430 ???

```
var source = _assetCache.ImageCache[sourceId];
if (!source) return;
```

Which means matchSamplerState on line 491 will always be false

**Comment by umeraamir-arthur** [comment]
@pfcDorn did you manage to find a work around?

**Comment by umeraamir-arthur** [comment]
Oops! I was missing a point there... Thankyou
