### ISSUE TITLE
Default range for imported punctual lights is too high.

### ISSUE THREAD

**Issue by andybak** [KhronosGroup/UnityGLTF#718]
(tested on spot lights but I presume this applies to point lights also)

When an imported light doesn't have a range, the spec says it's range should be infinite. Unity doesn't support infinite range. 

Currently the assigned range is 3.402823e+38 but it seems that this ends up being treated as 0 by Unity. The cutoff is somewhere around 3.402823e+7 - that gives you a light with a very long range whereas 3.402823e+8 gives you a light with no range.

**Comment by andybak** [comment]
ooops. potentially some user error here.

Closing until I can investigate properly.

**Comment by hybridherbst** [comment]
Interesting – I believe I noted a similar issue a while back. Please update when you have more findings and potentially a test model!
