### ISSUE TITLE
Freeze frame during runtime loading in Android

### ISSUE THREAD

**Issue by ChocolateRacoon** [KhronosGroup/UnityGLTF#720]
Hello, 

Could you please tell me if there is any way to get rid of freeze frames?

As far as I understand, the use of IDeferAgent is intended specifically for loading multiple models and increases the frame rate by queuing. Freeze frames occur even when loading one model.

**Comment by hybridherbst** [comment]
Hi, please include more information when making a bug report.

- a model that reproduces the issue
- Unity version
- SRP version
- runtime platform and device

Otherwise we can't reproduce. Thanks!

**Comment by ChocolateRacoon** [comment]
- Model (glb): https://sketchfab.com/3d-models/warcraft-3-alliance-footmanfanmade-201452e568064aedadccfafb668ef6a5
- Unity version 2022.3.16f1
- Package version 6.0.1
- URP 14.0.9
- Meta Quest 3, Oculus Quest 2

**Comment by ChocolateRacoon** [comment]
I've update version of gltfast 6.0.1 -> 6.2.0, and that didn't solve the problem with freeze frame.

**Comment by ChocolateRacoon** [comment]
As I understand, parameter 
`
GenerateMipMaps = true
`

is very hard for the app. 

Setting this parameter to False reduced the peaks (according to the profiler data), but it still doesn't look good. Below I present the profiler data when loading GLTF via gltf fast

**GenerateMipMaps = true**

![with_mip_maps](https://github.com/KhronosGroup/UnityGLTF/assets/108283613/1f364e2b-dc08-4556-99fc-9f7922346264)


**GenerateMipMaps = false**


![without_mip_maps](https://github.com/KhronosGroup/UnityGLTF/assets/108283613/87d6b256-231c-40e6-b594-bea24ba2e192)

**Comment by pfcDorn** [comment]
So you are using gltFast? This is the Repo for UnityGltf, that's a completly other import/export solution for gltf ;)
