### ISSUE TITLE
Mesh with tangents has validation errors and breaking compression

### ISSUE THREAD

**Issue by marwie** [KhronosGroup/UnityGLTF#726]
Model exported with UnityGLTF has thousands of tangent validation error

draco compression fails with access out of memory exception for these models

[model.zip](https://github.com/KhronosGroup/UnityGLTF/files/14873695/model.zip)

![image](https://github.com/KhronosGroup/UnityGLTF/assets/5083203/8ba44880-b073-4e60-a07f-84f217c70bb2)

**Comment by hybridherbst** [comment]
Potentially related:
- https://github.com/prefrontalcortex/UnityGLTF/issues/121

**Comment by pfcDorn** [comment]
Should not be related. The sign error was a Meta Avatar specific issue. 
But i will take a look now.

**Comment by pfcDorn** [comment]
Ok, after some investigation, i would say it's a Unity Draco bug. The Tangent support is new in draco, maybe there are still some issues. Currently i can't test it with gltFast, because it's not using the new com.unity.cloud.draco package (only this is supporting tangents)
I will contact Atteneder for this issue :)

**Comment by marwie** [comment]
I think got it with or without draco compression when exporting with UnityGLTF

**Comment by pfcDorn** [comment]
Edit: no, Draco works fine. But he need to change the code documentation for proper use of the tangents. :D I found a hint in the draco changelog how to handle it correctly, now it works fine!

**Comment by marwie** [comment]
Sounds good - so export for draco compressed meshes is fixed?
I can't reproduce anymore with non-compressed meshes too so that would be the only issue
