### ISSUE TITLE
i build and run my unity project and i found only pink object. if someone know please help me.

### ISSUE THREAD

**Issue by KoaLa2425** [KhronosGroup/UnityGLTF#735]
![image](https://github.com/KhronosGroup/UnityGLTF/assets/112968878/9f468a14-93bf-44e2-baf4-3fdd665495fe)

as u can see it all a pink

![image](https://github.com/KhronosGroup/UnityGLTF/assets/112968878/04d6a1d4-c837-4849-a32f-8a6242ed797f)
here is a player log
i try to add a UnityGLTF/PBRGraph into a shader variant but i cant found it anywhere in my unity project.

**Comment by KoaLa2425** [comment]
1. My unity version is 2022.3.15f1
2. i dont know that.i a very newbie in unity sorry.
3. My UnityGLTF version is 2.11.0-rc
4.now i build in window 

![image](https://github.com/KhronosGroup/UnityGLTF/assets/112968878/0723f264-5d22-43d5-86dc-c45c885c52fc)al
all my package

**Comment by KoaLa2425** [comment]
![image](https://github.com/KhronosGroup/UnityGLTF/assets/112968878/51af3b15-ffb7-429c-a218-08621a5dd310)

**Comment by KoaLa2425** [comment]
no one help me than

**Comment by andybak** [comment]
I'm not sure how quickly you expected someone to help but you closed this only 4 days after the last reply. If you need support on open source faster than that then you might need to hire someone. On the whole people are helping out as volunteers and not getting paid to provide support.

**Comment by hybridherbst** [comment]
Plus there's vacations, sick childs, general live things...
Someone will look at it :)

Most likely reason is that some shader variants are missing in the build, and need to be added via Shader Variant Collection. Another reason could be that you have both GLTFUtility and UnityGLTF (but they should be able to coexist).

**Comment by pfcDorn** [comment]
When i look into the Package Manager, i would guess he is using the BuildIn RP. My suggestion would be to switch to URP :)

**Comment by MarcusGT076** [comment]
So i had the same problems already in Unity. You have to put the PBRGraph normaly in the allways include shaders. But thats also a bad idea because the PBRGraph will now Compile over 200k of shader variants. The best way until now is to place the shader on an object in the scene who holds a reference to this PBRGraph and PBRGraph unlit.

**Comment by pfcDorn** [comment]
I will close this issue. 

With the latest update you can find two predefined ShaderVariantCollection: one for BuildIn RP and one for URP/HDRP. Just add the correct one to the project settings/graphics. That should include all UnityGltf shader variants for runtime loading. 

![image](https://github.com/user-attachments/assets/178da860-67bd-4f9d-9622-2a4b5c276af9)


When there is still an issue, please create a new one. Thanks :)
