### ISSUE TITLE
File Names are wrong

### ISSUE THREAD

**Issue by Kraaven** [KhronosGroup/UnityGLTF#737]
Whenever i export scene as GLTF, it renames the textures into the wrong file extensions
<img width="421" alt="ExportError" src="https://github.com/KhronosGroup/UnityGLTF/assets/106032882/5ee3fe47-15d8-4620-9569-7dfaf5f520ba">

**Comment by hybridherbst** [comment]
Hey, please post

- Unity version
- SRP version
- UnityGLTF version
- reproduction file (e.g. .unitypackage)

Thank you!

**Comment by pfcDorn** [comment]
is fixed with: d1ffc441def00d73c9f9dc677d1eefd0e38e50f1
