### ISSUE TITLE
Sample file that demonstrates the use of animation pointers and texture transform

### ISSUE THREAD

**Issue by andybak** [KhronosGroup/UnityGLTF#740]
I've tried the only two I can find:

https://github.com/KhronosGroup/glTF-Sample-Assets/tree/PotOfCoalsAnimationPointer/Models/PotOfCoalsAnimationPointer/glTF-Binary

https://github.com/KhronosGroup/glTF-Sample-Assets/blob/AnimationPointerUVs/Models/AnimationPointerUVs/glTF-Binary/

and neither seem to work with latest HEAD (as of 15 hours ago from the time of this post)

**Comment by hybridherbst** [comment]
Animation Pointer sample files are still stuck in this PR: https://github.com/KhronosGroup/glTF-Sample-Assets/pull/106
@pfcDorn please take a look as to why the above file doesn't import properly – thanks!
