### ISSUE TITLE
CameraSampling for Volume and Transmission is upside down!

### ISSUE THREAD

**Issue by MarcusGT076** [KhronosGroup/UnityGLTF#746]
When i import a gltf with volume and transmission in unity editor the plugin is working as planned. 
The Reflection inside the object is correct.
But when i export the scene to webgl and build it the reflection inside the object is upside down.
Its this function :

void SampleSceneColor_float(float2 uv, float lod, out float3 color)

Can you assist in this case ?
I tried alreade to flip the uv coordinates in this function with uv.y = 1.0 - uv.y and its working. 
But i dont know why this behaves different from the editor and the webgl build.

Can you assist here ?
Cheers!

**Comment by hybridherbst** [comment]
Thanks for the report – @pfcDorn would be great if you can take a look! Likely there needs to be a flip depending on if the RT is flipped (there should be a shader constant for that)
