### ISSUE TITLE
Textures with huge amount of allocating memory in Unity

### ISSUE THREAD

**Issue by MarcusGT076** [KhronosGroup/UnityGLTF#747]
Hello there,

i discovered somethin very weird in the textures. So i importet a scene in WebGL at runtime. The textures that i am going to import are .jpg. They are 4096x4096 and 24 bit in depth. On Harddisk they have memory about 4-6 MB. 

I used the memory profiler to track the memory and realized each of those texture are allocating 128MB of ram.
![Textures_Error](https://github.com/KhronosGroup/UnityGLTF/assets/173642845/ac96a56f-5f8b-4793-afde-dffee06715d0)

Is this a normal behavior ? Or where the huge ammount from the textures are come from ? Did i miss something on the realtime import when i import the file at runtime ?

Cheers
Marcus

**Comment by pfcDorn** [comment]
hey, you should set on the importer the KeepCPUCopyOfTexture to false. Otherwise the textures will be also exist on the RAM.
When it's not solving your problem, please come back :)

**Comment by MarcusGT076** [comment]
Hello there,
Yes it did the job. And of course the compression i was looking at. Thank you :)

**Comment by pfcDorn** [comment]
In a future release there will be also this option on the asset importer, i already has made a PR for this :)
So your issue was helpful to take another look to that :)
