### ISSUE TITLE
Tangent vector problem

### ISSUE THREAD

**Issue by gildor2** [KhronosGroup/UnityGLTF#75]
Hi,

I'm one of developers of glTF pipeline for CAD / Unity integration. I've used UnityGLTF project as a reference code for our Unity importer which generates meshes, materials, prefabs etc during glTF import. I found one problematic place in your code / math.

The problem is that your tangent vector looks incorrect. Code first (part of Accessor.cs):

		public Vector3[] AsVertexArray(ref NumericArray contents, byte[] bufferData)
		{
			if (contents.AsVertices != null) return contents.AsVertices;

			var arr = AsVector3Array(ref contents, bufferData);
			for (var i = 0; i < arr.Length; i++)
			{
				arr[i].Z *= -1;
			}
		...
		public Vector3[] AsNormalArray(ref NumericArray contents, byte[] bufferData)
		{
			if (contents.AsNormals != null) return contents.AsNormals;

			var arr = AsVector3Array(ref contents, bufferData);
			for (var i = 0; i < arr.Length; i++)
			{
				arr[i].Z *= -1;
			}
		...
		public Vector4[] AsTangentArray(ref NumericArray contents, byte[] bufferData)
		{
			if (contents.AsTangents != null) return contents.AsTangents;

			var arr = AsVector4Array(ref contents, bufferData);
			for (var i = 0; i < arr.Length; i++)
			{
				arr[i].W *= -1;
			}
		...

Here you may see that you're flipping Z coordinate for position and normal vectors, but not for tangent. If tangent vector is supposed to be orthogonal to normal, this orthogonality will be lost after this math. Inverting tangent's W flips handedness of the coordinate system - inverts binormal vector, but does nothing with tangent (vec3) itself. I think this is wrong.

I used special script which visualizes normal and tangent vectors (I can provide one for debugging purposes, but it works only in editor, not at runtime). I've played with all models from Kronos's glTF samples repository - with those who have tangents. Tangent vectors are good with some meshes, and bad with others. In fact, only models which has

	"generator": "glTF Tools for Unity"

are "good" after importing with your math, other models are bad. I.e. "good" are models generated with your code.

I've reviewed glTF specification for tangent space and didn't find any reference that tangent's Z should be negated, i.e. glTF uses "classic" orthogonal tangent space. Could you please review your code for possible problems?

Thanks,
Konstantin

**Comment by gildor2** [comment]
#69

**Comment by bghgary** [comment]
Thanks for the report on this @gildor2.

I'm the author of the "glTF tools for Unity" exporter. I've recently found the same bug in my exporter and have fixed it in this commit: https://github.com/bghgary/glTF-Tools-for-Unity/commit/6c4b37d923ab76024b24ff246311b39de7e83dcf, but I have not updated the models in the samples repo.

I will update the samples in the samples repo.

@robertlong @MSblgross @stevenvergenz We need to fix the code in this repo as well.

**Comment by gildor2** [comment]
Thank you very much @bghgary for pointing me at the fix - at least I see that my assumption was correct :)

**Comment by bghgary** [comment]
@gildor2 If you're up for it, feel free to open a PR with a fix for the tangent.

**Comment by gildor2** [comment]
@bghgary I think it's too much mess making a PR for adding just one line of code :)

Also it was mentioned in #69 this plugin now have a layer of abstraction, and it would be nice to move all Unity-specific math to "upper" layer, keeping base glTF C# code clean.

**Comment by bghgary** [comment]
@gildor2 Okay, no problem :) We'll look into it!

**Comment by amenzies** [comment]
I've just created an issue for what I think is a similar bug when flipping the Y component of texture coordinates.
