### ISSUE TITLE
Humanoid import bone mapping is missing a specific direct mapping

### ISSUE THREAD

**Issue by Phlegmati** [KhronosGroup/UnityGLTF#751]
I am using **UnityGLTF 2.12.0** for Importing .glb model files in **Unity 2022.3.23f1**

I've got several model files:
1.) One, which is rigged & skinned with the mecanim humanoid bone hierarchy (Hips > Ribs > Chest > etc ...)
2.) Another, which is rigged & skinned with meta avatar bone hierarchy (Spine.001 > Spine.002 > Spine.003 > etc ...)

If I export those files as .fbx and import it in Unity (editor, not runtime), I can choose "Humanoid" rig configuration and may need to retarget some spine bones - but both files are getting retargeted really well.

If I export those files as .glb and import it in Unity (editor, not runtime), I can choose "Mecanim Humanoid" and it always fails, stating that the "Hips"-bone is missing [It is not]. 

Did I miss a step configuring/exporting in Blender, in the Unity Editor or am I missing an extension?  
As stated in the changelogs for version 2.11.0: "- add: support for humanoid import for Meta avatar bone hierarchies" - there should be a working solution for that.

Thank you guys in advance and for your work so far. I will appreciate any advice given!

**Comment by Phlegmati** [comment]
Sorry, found out myself:

The ErrorMsg is a bit misleading, it states that the Bone named „Hips“ is not found - when the importer itself actually has a lookup table, with different naming conventions:

hips -> Hips
Hips_jnt -> Hips
mixamorig:Hips -> Hips

but never actually looks for „Hips“ with a capital Letter „H“.

To be sure your bone hierarchy is readable for the importer, take a look at „AvatarUtils.cs“ which has the dictionary „HumanSkeletonNames“ with different naming conventions.

**Comment by pfcDorn** [comment]
hey @Phlegmati, can you please test your scenario with this [comment](https://github.com/KhronosGroup/UnityGLTF/commit/ebc6ea421b4095104adb4d33ec3fd9c3525481f5)? That should be fix it :)

**Comment by pfcDorn** [comment]
Nice, good to hear :)
