### ISSUE TITLE
Critical Bug: Namespace "System" missing in GLTFComponent for UWP

### ISSUE THREAD

**Issue by ArDevKarl** [KhronosGroup/UnityGLTF#757]
![Screenshot 2024-07-12 103056](https://github.com/user-attachments/assets/9651c499-b7b8-404b-9559-8e56f8350969)

This makes it impossible to compile a UWP build.

This should be added to the usings in GLTFComponent.cs:

`
#if WINDOWS_UWP
using System;
#endif
`

Happens in release 2.12.0

**Comment by pfcDorn** [comment]
thanks for opening this issue! i have added it :)

**Comment by ArDevKarl** [comment]
@pfcDorn Is it possible to get this hotfixed this week, so the UnityPackage can be used properly? Otherwise I need to do a rollback until this is fixed.
