### ISSUE TITLE
How to export skin animation to gltf model?

### ISSUE THREAD

**Issue by flowerdance** [KhronosGroup/UnityGLTF#76]
Sorry， My English is so bad.  

    I drag the "dude.fbx " that it is a  model with the mesh skin animation in unity and export it.  the tools can't export the skin animation to gltf model.
   Please help me. thanks!

**Comment by MSblgross** [comment]
@flowerdance  We do not currently support exporting animations. We do welcome contributions!

**Comment by flowerdance** [comment]
I see. I will do! thanks

**Comment by longde123** [comment]
support exporting animations any?

**Comment by pfcDorn** [comment]
It's supported :)
