### ISSUE TITLE
Help with Callback on onLoadComplete

### ISSUE THREAD

**Issue by TurretProblems** [KhronosGroup/UnityGLTF#760]
Hello, I am rather new to the concept of UnityAcitons and I have a function waiting on a GLTFComponent, the model needs to be finished loading before I can continue the code so I am asking how do I detect/ fire an event when the model is complete?

(Still learning github, am I not able to set my posts tags to mark it as help?)

**Comment by hybridherbst** [comment]
Did you get it to work? :)
