### ISSUE TITLE
Animation Pointer Error

### ISSUE THREAD

**Issue by hierro** [KhronosGroup/UnityGLTF#761]
Hi all I'm exporting GLB from unity with animation, in unity the model is animated, when i test it on https://gltf-viewer.donmccurdy.com/  , the animation is listed , but doesnt play and I have this in log:

- many warnings:  "VALUE_NOT_IN_LIST	Invalid value 'pointer'. Valid values are ('translation', 'rotation', 'scale', 'weights').	/animations/0/channels/0/target/path"

- info messages:" UNSUPPORTED_EXTENSION	Cannot validate an extension as it is not supported by the validator: 'KHR_animation_pointer'.	/extensionsUsed/2"
NODE_EMPTY	Empty node encountered.	/nodes/3
NODE_EMPTY	Empty node encountered.	/nodes/9
NODE_EMPTY	Empty node encountered.	/nodes/14
NODE_EMPTY	Empty node encountered.	/nodes/24

Im suing mixamo animations, and i noticede that when I drop exported glb into viewer, i cant see the legs of skeleton, still in unity all works fine.

I considered this an issue since it was working fine with previous versions of UnityGLTF, still dont get what im doing wrong, any hint ?

Thanks a lot in advance

**Comment by marwie** [comment]
@hierro you can disable KHR_animation_pointer export in the UnityGLTF settings.

![image](https://github.com/user-attachments/assets/be1db889-65d7-4d2b-816f-a8f0245c1d63)

Not every viewer supports this extension - but it allows you to animate basically anything inside the glTF. We heavily use it in Needle Engine and it will work in https://viewer.needle.tools for example

**Comment by hierro** [comment]
Thank you for your reply and knowledge, I will try and make comparison also
with needle, btw very interesting engine, thanks !
