### ISSUE TITLE
Imported GLB with sheen does not have sheen anymore in Unity

### ISSUE THREAD

**Issue by marwie** [KhronosGroup/UnityGLTF#766]
See attached glTF file - when imported into Unity there's no sheen effect anymore.

[shaderball.zip](https://github.com/user-attachments/files/16709199/shaderball.zip)

Expected: 
Sheen is being rendered in Unity

STRP:

1) Download glTF (shaderball2.glb is uncompressed, shaderball.glb is the same mesh but draco compressed)
2) Import into Unity (make sure you have compression packages for draco support enabled)
3) Set importer to UnityGLTF
4) See sheen is not rendered in Unity

![image](https://github.com/user-attachments/assets/1cf64d67-0a89-4450-97d4-31923f06e44e)

![image](https://github.com/user-attachments/assets/6936ac4c-9135-40d4-986b-37e382051dc5)

**Comment by pfcDorn** [comment]
Hey, Sheen is currently not supported. I already worked on it, but the PBRGraph Shader is already in the Keyword Limit. So adding more features to it is now not possible. Need to find a solution for that :/

**Comment by pfcDorn** [comment]
The latest version now supports Sheen :)
