### ISSUE TITLE
Importer: Show glTF / GLB meta information

### ISSUE THREAD

**Issue by marwie** [KhronosGroup/UnityGLTF#773]
It would be great if the model importer would allow me to inspect glTF meta information inside the `json.assets` object - especially in regards of  author, source and licensing information but also which generator was used to produce the file with the glTF file version

Importer:
![image](https://github.com/user-attachments/assets/5d3997e0-0489-49fc-9981-3bfe672d9b57)

Example meta:

https://cloud.needle.tools/api/v1/public/9283996/105938669/mustang_sunglasses_-_mu_1683.glb

![image](https://github.com/user-attachments/assets/f592a1bc-4c68-4dd0-a934-09554f17b2e2)

**Comment by hybridherbst** [comment]
Any particular wish on how you'd want to see that? E.g. would "I see the .asset part of the JSON in the importer" be enough?

**Comment by pfcDorn** [comment]
Hey, you can take a look if this is what you wished for: [PR Meta Informations](https://github.com/KhronosGroup/UnityGLTF/pull/774)

**Comment by pfcDorn** [comment]
I would close this issue, because the latest version includes all the requested meta information :) 

![image](https://github.com/user-attachments/assets/5dc48e51-f72a-47cc-8d7a-74898da22b0f)
