### ISSUE TITLE
Loaded figure malformed. Looks fine when loading same .glb into Blender

### ISSUE THREAD

**Issue by utahman** [KhronosGroup/UnityGLTF#778]
![image](https://github.com/user-attachments/assets/951f748c-04ce-4071-9ca7-2dfe010050f0)
Download .glb: https://1drv.ms/u/s!AoYauzEoBUeDivp-TaPfg3zWjuof1Q?e=6JVDox

**Comment by hybridherbst** [comment]
Scary!

Please provide
- Unity version
- Render pipeline and version
- UnityGLTF version
- whether you're loading in the editor or at runtime

Thanks!

**Comment by pfcDorn** [comment]
yeah, more informations are needed, i can't get it reproduce this issue.

**Comment by utahman** [comment]
All latest versions. Unity 2023.2.6f1
Create HDRP project.
In Package Manager press + then Install Package by Name.
Enter "com.unity.cloud.gltfast".
Add button. Add on click method:

    using GLTFast;

    public async void OnImportClick()
    {
        string path = "...";

        try
        {
            byte[] data = File.ReadAllBytes(path);
            var gltf = new GltfImport();
            bool loadSuccess = await gltf.LoadGltfBinary(data, new Uri(path));

            if (loadSuccess)
            {
                bool instantiateSuccess = await InstantiateGltfAsync(gltf);
                if (instantiateSuccess)
                {
                    Debug.Log("GLTF model loaded and instantiated successfully.");
                }
                else
                {
                    Debug.LogError("Failed to instantiate the GLTF model.");
                }
            }
            else
            {
                Debug.LogError("Failed to load the GLTF file.");
            }
        }
        catch (Exception e)
        {
            Debug.LogError($"An error occurred: {e.Message}");
        }
    }

    private async Task<bool> InstantiateGltfAsync(GltfImport gltf)
    {
        try
        {
            // Start the asynchronous operation
            bool result = await gltf.InstantiateMainSceneAsync(transform);
            return result;
        }
        catch (Exception e)
        {
            Debug.LogError($"Error during GLTF instantiation: {e.Message}");
            return false;
        }
    }
