### ISSUE TITLE
Lightmaps for gltf models are reset when reloading the scene.

### ISSUE THREAD

**Issue by Greenf1re** [KhronosGroup/UnityGLTF#787]
### Describe the bug 💬

After baking lightmaps, if I reload or export the scene the lightmaps are reset. It does not happen if I use Unity's meshes or FBX files. Might be an issue with generate Lighmap UVs.

https://github.com/user-attachments/assets/0003132d-58dc-4d51-8dff-8052b12f43dd

### Steps to reproduce 🔢

1. Download files
2. Place a point light inside one of the enclosed areas; set to Mixed or Baked.
3. Bake Lightmaps.
4. Reopen the scene, export, or cause the scene to be reloaded in any way.
5. The lightmaps are reset and the enclosed area is dark again.

### Files to reproduce the issue ♻

[r111_t.zip](https://github.com/user-attachments/files/17160067/r111_t.zip)

### Editor Version 🎲

2021.3

### Render Pipeline and version

URP 12.1.15

### UnityGLTF Version

2.13.0

### Operating System 👩‍💻

Windows

### When does this problem happen?

- [ ] Editor Import
- [ ] Runtime Import
- [X] Editor Export
- [X] Runtime Export

### Validations 🩹

- [X] I have [searched existing issues](https://github.com/KhronosGroup/UnityGLTF/issues): no issue already exist that reports the same problem.
- [X] I follow the [Code of Conduct](https://www.khronos.org/about/code-of-conduct)
- [X] I provided a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), including files when necessary.

**Comment by pfcDorn** [comment]
Hey,
i can't get it to reproduce it. Also the Gltf part should not have any influence on baked lightmaps after inporting. The imported assets will end up in standard Unity Assets like Mesh and Texture2d. 
Can you check if your baked lightmaps are still exist in den Scene folder? And also check the GameObject MeshRenderers for lightmap informations?

**Comment by hybridherbst** [comment]
Thanks for the follow-up! Did you happen to report this bug to Bakery so they can fix it?
