### ISSUE TITLE
Upgrade to Unity 2017.1?

### ISSUE THREAD

**Issue by sbtron** [KhronosGroup/UnityGLTF#79]
Currently the library works with Unity 5.6. Should we upgrade it to 2017.1?
Anyone have a requirement to support Unity 5.6 as min version?

@stevenvergenz ?

**Comment by stevenvergenz** [comment]
I don't know if it's a hard/fast requirement, but as a guiding principle we should shoot to support as many Unity versions as possible, right? Are there 2017-specific features we want to use?

**Comment by JeckleCed** [comment]
Side note : One the file wasn't compiling under Unity 21017 ( Batch.cs ), I have a PR active to fix it.

**Comment by stevenvergenz** [comment]
As of today, the Unity automatic upgrade works up to 2017.2, so it's probably good enough.
