### ISSUE TITLE
[Question] Is support lightmap?

### ISSUE THREAD

**Issue by sonygod** [KhronosGroup/UnityGLTF#84]
support lightmap?
before download and test  ,I want to ask some question about lightmap 
1:is that support ?
2:if support ,is convert hdr to ldr?  format from exr to png or something? or keep originally format?
3:can unity runtime import that assets which export from gltf? any platform? or only export tool?

**Comment by stevenvergenz** [comment]
No, as of now glTF does not support lightmaps. There is an [extension proposal](https://github.com/KhronosGroup/glTF/pull/1017) for this feature, but nothing that's ready yet.
