### ISSUE TITLE
.glb binary support

### ISSUE THREAD

**Issue by Tshadow05** [KhronosGroup/UnityGLTF#86]
I am not seeing any option for exporting to .glb instead of multiple files. Is this something that is possible? Do I need to manually package the binary?

**Comment by Tshadow05** [comment]
Same thing for importing as well.

**Comment by stevenvergenz** [comment]
Glb is supported for import. Export is entirely broken right now I think (unless someone corrects me). Once it's fixed though, I agree we should support glb. Lots of options there.

**Comment by Tshadow05** [comment]
I do see that there is code in the project for importing .glb files but it doesn't seem to work for me. I have tried using the example importer with one of the sample assets and am getting an error.

System.Exception: Error loading asset. Assimp returns: [GLTF: Unsupported binary glTF version]
  at TriLib.AssetLoader.LoadFromFile (System.String filename, TriLib.AssetLoaderOptions options, UnityEngine.GameObject wrapperGameObject) [0x0005c]

**Comment by RPSpicer** [comment]
I'd like to get runtime GLB export working to support a project I'm working on. I've written my own C# class to successfully combine the .gltf and .bin files output by `GLTFSceneExporter` into a .glb that loads with `GLTFSceneImporter` by following the spec.

I think the next step would be to modify `GLTFSceneExporter` to export the GLB directly as a call (eg: `sceneExporter.SaveGLB(string path, string filename)` -- any reason I should not write the code and submit a PR?  A bit worried I may be missing some subtlety of the spec -- if it were that easy why hasn't it been implemented yet?

**Comment by RPSpicer** [comment]
Pull request #155 is a first stab at addressing this.
